using System;
using System.Text;
using System.Windows;
using System.Windows.Controls;

namespace Awl { partial class Shell {
 void EnsureBuilderBlockSchema(BuilderBlock block){if(block==null)return;if(block.type=="access.time"){if(!block.parameters.ContainsKey("preset"))block.parameters["preset"]=new BuilderValue{value="24-hour with seconds"};if(!block.parameters.ContainsKey("format"))block.parameters["format"]=new BuilderValue{value="HH:MM:SS"};}}
 object BuilderRawParameter(BuilderBlock block,string key,object fallback){BuilderValue value;return block!=null&&block.parameters.TryGetValue(key,out value)&&value.value!=null?value.value:fallback;}
 string BuilderTimeFormat(BuilderBlock block){string preset=Convert.ToString(BuilderRawParameter(block,"preset","24-hour with seconds"));string custom=Convert.ToString(BuilderRawParameter(block,"format","HH:MM:SS"));if(preset=="12-hour")return "hh:MM a";if(preset=="12-hour with seconds")return "hh:MM:SS a";if(preset=="24-hour")return "HH:MM";if(preset=="Date and time")return "WWW, DD NNN · HH:MM";return preset=="Custom"?custom:"HH:MM:SS";}
 string FormatBuilderTime(DateTime time,string format){if(String.IsNullOrEmpty(format))format="HH:MM:SS";var output=new StringBuilder();for(int i=0;i<format.Length;){char c=format[i];if(c=='\\'&&i+1<format.Length){output.Append(format[i+1]);i+=2;continue;}int count=1;while(i+count<format.Length&&format[i+count]==c)count++;string token=new string(c,count),value=null;if(c=='D'||c=='d')value=count==1?time.Day.ToString():time.Day.ToString("00");else if(c=='H')value=count==1?time.Hour.ToString():time.Hour.ToString("00");else if(c=='h'){int hour=time.Hour%12;if(hour==0)hour=12;value=count==1?hour.ToString():hour.ToString("00");}else if(c=='M'||c=='m')value=count==1?time.Minute.ToString():time.Minute.ToString("00");else if(c=='S'||c=='s')value=count==1?time.Second.ToString():time.Second.ToString("00");else if(c=='A')value=time.ToString("tt");else if(c=='a')value=time.ToString("tt").ToLowerInvariant();else if(c=='N'||c=='n')value=count>=3?time.ToString(count>=4?"MMMM":"MMM"):(count==1?time.Month.ToString():time.Month.ToString("00"));else if(c=='Y'||c=='y')value=count<=2?time.ToString("yy"):time.ToString("yyyy");else if(c=='W'||c=='w')value=time.ToString(count>=4?"dddd":"ddd");output.Append(value??token);i+=count;}return output.ToString();}
 void ShowTimeFormatHelp(){var window=new Window{Title="Time format help",Width=430,Height=520,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=System.Windows.Media.Brushes.Transparent,Owner=builderWindow,WindowStartupLocation=WindowStartupLocation.CenterOwner,ShowInTaskbar=false};var host=new StackPanel();host.Children.Add(BuilderHeading("Custom time format"));foreach(string line in new[]{"D / DD   day (4 / 04)","H / HH   24-hour (7 / 07)","h / hh   12-hour (7 / 07)","M / MM   minute (5 / 05)","S / SS   second (9 / 09)","A / a   AM or am","N / NN   month number","NNN / NNNN   Sep or September","YY / YYYY   year","WWW / WWWW   Wed or Wednesday","\\x   insert a token letter literally","Other characters remain unchanged.","Example: DD-hh-MM a  →  11-10-08 pm"})host.Children.Add(BuilderSub(line));host.Children.Add(BuilderPrimaryButton("close","Close",()=>window.Close()));window.Content=new Border{Background=panelBrush,BorderBrush=accentBrush,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(18),Padding=new Thickness(18),Child=host};window.ShowDialog();}
} }
