using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace Awl { partial class Shell {
 void RenderBuilderLogicTree(){if(logicCanvas==null)return;logicCanvas.Children.Clear();builderLiveReporterLabels.Clear();var referenced=new HashSet<string>(builderProject.logic_graph.Where(x=>!String.IsNullOrEmpty(x.next)).Select(x=>x.next));foreach(var block in builderProject.logic_graph)foreach(var id in block.body)referenced.Add(id);var roots=builderProject.logic_graph.Where(x=>x.type.StartsWith("events.")).Concat(builderProject.logic_graph.Where(x=>!referenced.Contains(x.id)&&!x.type.StartsWith("events."))).Distinct().ToArray();var host=new StackPanel{Margin=new Thickness(28),Width=Math.Max(360,logicCanvas.ActualWidth-70)};if(roots.Length==0)host.Children.Add(BuilderSub("Add a block from the palette. Drag it into a body or next slot."));foreach(var root in roots){host.Children.Add(BuilderFlowBlock(root,new HashSet<string>(),0));host.Children.Add(new Border{Height=20});}var scroll=new ScrollViewer{Content=host,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,Width=Math.Max(100,logicCanvas.ActualWidth),Height=Math.Max(100,logicCanvas.ActualHeight)};logicCanvas.Children.Add(scroll);}
 FrameworkElement BuilderFlowBlock(BuilderBlock block,HashSet<string> visited,int depth){if(block==null||!visited.Add(block.id))return BuilderSub("Circular flow blocked");var group=new StackPanel{Margin=new Thickness(Math.Min(60,depth*18),0,0,0),HorizontalAlignment=HorizontalAlignment.Left};var card=new Border{Width=290,MinHeight=54,CornerRadius=new CornerRadius(block.type.StartsWith("events.")?18:10),Background=BuilderBlockBrush(block.type),Padding=new Thickness(12,9,12,9),Cursor=Cursors.Hand,AllowDrop=true,BorderBrush=block==builderSelectedBlock?Brushes.White:new SolidColorBrush(Color.FromArgb(50,255,255,255)),BorderThickness=new Thickness(block==builderSelectedBlock?2:1),ToolTip=BuilderBlockDescription(block.type)};var content=new DockPanel();content.Children.Add(BuilderSvgIcon(BuilderBlockIcon(block.type),20,Brushes.White));content.Children.Add(new TextBlock{Text=BuilderBlockLabel(block.type),Foreground=Brushes.White,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(10,0,8,0)});var output=new TextBlock{Text=BuilderReporterPreview(block),Foreground=new SolidColorBrush(Color.FromArgb(190,255,255,255)),FontSize=11,VerticalAlignment=VerticalAlignment.Center};if(!BuilderSequenceBlock(block.type))builderLiveReporterLabels[block.id]=output;DockPanel.SetDock(output,Dock.Right);content.Children.Add(output);card.Child=content;card.MouseLeftButtonDown+=delegate(object sender,MouseButtonEventArgs e){builderSelectedBlock=block;DrawBuilderBlockProperties();e.Handled=true;};card.PreviewMouseMove+=delegate(object sender,MouseEventArgs e){if(e.LeftButton==MouseButtonState.Pressed)DragDrop.DoDragDrop(card,"logic:"+block.id,DragDropEffects.Move);};card.Drop+=delegate(object sender,DragEventArgs e){AttachBuilderFlow(block,e,false);};group.Children.Add(card);
  if(block.type=="control.if"||block.type=="control.for_each"||block.type=="control.while_loop"){var bodyHeader=new DockPanel{Margin=new Thickness(18,5,0,3)};bodyHeader.Children.Add(BuilderSvgIcon("branch",15,mutedBrush));bodyHeader.Children.Add(new TextBlock{Text="Body",Foreground=mutedBrush,Margin=new Thickness(7,0,0,0)});group.Children.Add(bodyHeader);if(block.body.Count>0){var body=builderProject.logic_graph.FirstOrDefault(x=>x.id==block.body[0]);if(body!=null)group.Children.Add(BuilderFlowBlock(body,new HashSet<string>(visited),depth+1));}else group.Children.Add(BuilderLogicDropSlot(block,true));}
  if(!String.IsNullOrEmpty(block.next)){var next=builderProject.logic_graph.FirstOrDefault(x=>x.id==block.next);if(next!=null){group.Children.Add(BuilderFlowConnector());group.Children.Add(BuilderFlowBlock(next,new HashSet<string>(visited),depth));}}else if(BuilderSequenceBlock(block.type))group.Children.Add(BuilderLogicDropSlot(block,false));return group;}
 string BuilderBlockLabel(string type){string name=type.Contains(".")?type.Substring(type.IndexOf('.')+1):type;return name.Replace('_',' ');}
 FrameworkElement BuilderFlowConnector(){return new Border{Width=3,Height=12,Background=accentBrush,HorizontalAlignment=HorizontalAlignment.Left,Margin=new Thickness(26,0,0,0)};}
 FrameworkElement BuilderLogicDropSlot(BuilderBlock parent,bool body){var slot=new Border{Width=270,Height=34,CornerRadius=new CornerRadius(9),BorderBrush=new SolidColorBrush(Color.FromArgb(100,170,210,205)),BorderThickness=new Thickness(1),Margin=new Thickness(body?28:10,4,0,4),AllowDrop=true,Background=new SolidColorBrush(Color.FromArgb(28,120,180,175)),Child=BuilderIconLabel(body?"branch":"logic",body?"Drop child block":"Drop next block",mutedBrush,15)};slot.Drop+=delegate(object sender,DragEventArgs e){AttachBuilderFlow(parent,e,body);};return slot;}
 void AttachBuilderFlow(BuilderBlock parent,DragEventArgs e,bool body){string data=Convert.ToString(e.Data.GetData(typeof(string)));if(!data.StartsWith("logic:"))return;var child=builderProject.logic_graph.FirstOrDefault(x=>x.id==data.Substring(6));if(AttachBuilderFlowBlocks(parent,child,body)){RenderBuilderLogicTree();DrawBuilderBlockProperties();e.Handled=true;}}
 bool AttachBuilderFlowBlocks(BuilderBlock parent,BuilderBlock child,bool body){if(child==null||parent==null||child==parent||!BuilderSequenceBlock(child.type)||BuilderFlowContains(child,parent.id,new HashSet<string>()))return false;DetachBuilderFlow(child.id);if(body){string old=parent.body.FirstOrDefault();parent.body.Clear();parent.body.Add(child.id);if(!String.IsNullOrEmpty(old)&&String.IsNullOrEmpty(child.next))child.next=old;}else{string old=parent.next;parent.next=child.id;if(!String.IsNullOrEmpty(old)&&String.IsNullOrEmpty(child.next))child.next=old;}SnapshotBuilder();return true;}
 void DetachBuilderFlow(string id){foreach(var block in builderProject.logic_graph){if(block.next==id)block.next=null;block.body.Remove(id);}}
 FrameworkElement BuilderReporterSocket(BuilderValue value,FrameworkElement editor){var socket=new Border{AllowDrop=true,CornerRadius=new CornerRadius(10),BorderBrush=value!=null&&!String.IsNullOrEmpty(value.binding)&&value.binding.StartsWith("block:")?accentBrush:new SolidColorBrush(Color.FromArgb(80,160,200,195)),BorderThickness=new Thickness(1),Padding=new Thickness(3),Background=new SolidColorBrush(Color.FromArgb(26,100,170,165)),Child=editor};socket.Drop+=delegate(object sender,DragEventArgs e){string data=Convert.ToString(e.Data.GetData(typeof(string)));if(!data.StartsWith("logic:"))return;var reporter=builderProject.logic_graph.FirstOrDefault(x=>x.id==data.Substring(6));if(AttachBuilderReporter(value,reporter)){DrawBuilderBlockProperties();e.Handled=true;}};socket.ToolTip="Drop a value block here";return socket;}
 bool AttachBuilderReporter(BuilderValue value,BuilderBlock reporter){if(value==null||reporter==null||BuilderSequenceBlock(reporter.type))return false;value.binding="block:"+reporter.id;value.value=null;SnapshotBuilder();return true;}
 bool BuilderFlowContains(BuilderBlock root,string id,HashSet<string> seen){if(root==null||!seen.Add(root.id))return false;if(root.id==id)return true;if(!String.IsNullOrEmpty(root.next)&&BuilderFlowContains(builderProject.logic_graph.FirstOrDefault(x=>x.id==root.next),id,seen))return true;foreach(string child in root.body)if(BuilderFlowContains(builderProject.logic_graph.FirstOrDefault(x=>x.id==child),id,seen))return true;return false;}
} }
