using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;

namespace Awl { partial class Shell {
 FrameworkElement BuilderProgressVisual(double width,double height,string style,string direction,double value,double maximum,double thickness,Brush fill,Brush track,int dashes){double ratio=Math.Max(0,Math.Min(1,maximum<=0?0:value/maximum));if(style=="line")return BuilderLineProgress(width,height,direction,ratio,thickness,fill,track);var canvas=new Canvas{Width=width,Height=height};double radius=Math.Max(4,Math.Min(width,height)/2-thickness),cx=width/2,cy=height/2;if(style=="dashes"){int count=Math.Max(4,dashes),lit=(int)Math.Round(count*ratio);for(int i=0;i<count;i++){double angle=-90+360.0*i/count,radians=angle*Math.PI/180;var dash=new Line{X1=cx+Math.Cos(radians)*(radius-thickness),Y1=cy+Math.Sin(radians)*(radius-thickness),X2=cx+Math.Cos(radians)*radius,Y2=cy+Math.Sin(radians)*radius,Stroke=i<lit?fill:track,StrokeThickness=Math.Max(2,thickness/2),StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round};canvas.Children.Add(dash);}return canvas;}double sweep=style=="arc"?270:359.8,start=style=="arc"?-225:-90;if(direction=="counterclockwise")sweep=-sweep;canvas.Children.Add(BuilderArc(cx,cy,radius,start,sweep,track,thickness));if(ratio>0)canvas.Children.Add(BuilderArc(cx,cy,radius,start,sweep*ratio,fill,thickness));return canvas;}
 FrameworkElement BuilderLineProgress(double width,double height,string direction,double ratio,double thickness,Brush fill,Brush track){bool vertical=direction=="up"||direction=="down";var grid=new Grid{Width=width,Height=height};var rail=new Border{Background=track,CornerRadius=new CornerRadius(thickness/2),Width=vertical?thickness:width,Height=vertical?height:thickness,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};grid.Children.Add(rail);var bar=new Border{Background=fill,CornerRadius=new CornerRadius(thickness/2),Width=vertical?thickness:Math.Max(0,width*ratio),Height=vertical?Math.Max(0,height*ratio):thickness,HorizontalAlignment=vertical?HorizontalAlignment.Center:(direction=="right-to-left"?HorizontalAlignment.Right:HorizontalAlignment.Left),VerticalAlignment=!vertical?VerticalAlignment.Center:(direction=="down"?VerticalAlignment.Top:VerticalAlignment.Bottom)};grid.Children.Add(bar);return grid;}
 Path BuilderArc(double cx,double cy,double radius,double start,double sweep,Brush brush,double thickness){double a=start*Math.PI/180,b=(start+sweep)*Math.PI/180;var from=new Point(cx+radius*Math.Cos(a),cy+radius*Math.Sin(a));var to=new Point(cx+radius*Math.Cos(b),cy+radius*Math.Sin(b));var figure=new PathFigure{StartPoint=from,IsClosed=false};figure.Segments.Add(new ArcSegment{Point=to,Size=new Size(radius,radius),IsLargeArc=Math.Abs(sweep)>180,SweepDirection=sweep>=0?SweepDirection.Clockwise:SweepDirection.Counterclockwise});return new Path{Data=new PathGeometry(new[]{figure}),Stroke=brush,StrokeThickness=thickness,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round};}
} }
