using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Threading;
using System.Web.Script.Serialization;

namespace Awl { partial class Shell {
 WidgetBuilderDesktopState builderDesktopState;
 Dictionary<string,Window> builderDesktopWindows=new Dictionary<string,Window>();
 DispatcherTimer builderDesktopTimer;
 string BuilderDesktopFile { get { return Path.Combine(Root,"desktop-widgets.json"); } }

 void StartBuilderDesktop(){
  if(builderDesktopState!=null)return;
  try{builderDesktopState=File.Exists(BuilderDesktopFile)?new JavaScriptSerializer().Deserialize<WidgetBuilderDesktopState>(File.ReadAllText(BuilderDesktopFile)):null;}catch{builderDesktopState=null;}
  if(builderDesktopState==null)builderDesktopState=new WidgetBuilderDesktopState();
  foreach(var item in builderDesktopState.widgets.Where(x=>x.enabled&&x.project!=null).ToArray())ShowBuilderDesktop(item);
  builderDesktopTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};
  builderDesktopTimer.Tick+=delegate{RefreshBuilderDesktop();};builderDesktopTimer.Start();
 }
 void SaveBuilderDesktop(){Directory.CreateDirectory(Path.GetDirectoryName(BuilderDesktopFile));File.WriteAllText(BuilderDesktopFile,Pretty(new JavaScriptSerializer().Serialize(builderDesktopState)));}
 void LoadBuilderDesktopState(){try{builderDesktopState=File.Exists(BuilderDesktopFile)?new JavaScriptSerializer().Deserialize<WidgetBuilderDesktopState>(File.ReadAllText(BuilderDesktopFile)):null;}catch{builderDesktopState=null;}if(builderDesktopState==null)builderDesktopState=new WidgetBuilderDesktopState();}
 void ReloadBuilderDesktop(){if(builderDesktopTimer!=null){builderDesktopTimer.Stop();builderDesktopTimer=null;}foreach(var window in builderDesktopWindows.Values.ToArray())window.Close();builderDesktopWindows.Clear();builderDesktopExecutions.Clear();builderDesktopState=null;StartBuilderDesktop();}
 void SignalBuilderDesktopReload(){try{System.Threading.EventWaitHandle.OpenExisting("Local\\AwlWidgetReload").Set();}catch{}}
 WidgetBuilderProject CloneBuilderProject(WidgetBuilderProject project){var serializer=new JavaScriptSerializer();return serializer.Deserialize<WidgetBuilderProject>(serializer.Serialize(project));}
 void DeployBuilderWidget(){
  var errors=ValidateBuilder();if(errors.Count>0){MessageBox.Show(builderWindow,String.Join("\n",errors),"Fix before adding");return;}
  if(builderDesktopState==null){if(standaloneWidgetBuilder)LoadBuilderDesktopState();else StartBuilderDesktop();}var copy=CloneBuilderProject(builderProject);double width=DesktopBuilderNumber(copy,copy.ui_tree,"width",360),height=DesktopBuilderNumber(copy,copy.ui_tree,"height",180);
  var deployment=new WidgetBuilderDeployment{name=copy.name,project=copy,x=SystemParameters.WorkArea.Left+(SystemParameters.WorkArea.Width-width)/2,y=SystemParameters.WorkArea.Top+(SystemParameters.WorkArea.Height-height)/2};
  builderDesktopState.widgets.Add(deployment);SaveBuilderDesktop();if(standaloneWidgetBuilder)SignalBuilderDesktopReload();else ShowBuilderDesktop(deployment);
 }
 void ShowBuilderDesktop(WidgetBuilderDeployment deployment){
  if(deployment==null||deployment.project==null||deployment.project.ui_tree==null)return;Window existing;if(builderDesktopWindows.TryGetValue(deployment.id,out existing)){DrawBuilderDesktop(deployment);existing.Show();return;}
  var window=new Window{Title="Awl Widget · "+deployment.name,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,ShowInTaskbar=false,ShowActivated=false,Topmost=false};builderDesktopWindows[deployment.id]=window;
  window.SourceInitialized+=delegate{var h=new WindowInteropHelper(window).Handle;Native.SetWindowLong(h,-20,Native.GetWindowLong(h,-20)|0x80|0x08000000);};
  EnableDesktopWidgetDrag(window,()=>deployment.locked,(x,y)=>{deployment.x=x;deployment.y=y;deployment.relative_x=WidgetPositionRatio(x,true,window.Width);deployment.relative_y=WidgetPositionRatio(y,false,window.Height);SaveBuilderDesktop();});
  var menu=new ContextMenu();ThemeContextMenu(menu);var edit=new MenuItem{Header="Edit in Widget Builder"};edit.Click+=delegate{OpenWidgetBuilder();builderProject=CloneBuilderProject(deployment.project);builderSelected=builderProject.ui_tree;builderHistory.Clear();builderHistoryIndex=-1;SnapshotBuilder(false);builderTab="UI";DrawBuilder();};menu.Items.Add(edit);
  var locked=new MenuItem{Header="Lock movement",IsCheckable=true,IsChecked=deployment.locked};locked.Click+=delegate{deployment.locked=locked.IsChecked;SaveBuilderDesktop();};menu.Items.Add(locked);
  var hide=new MenuItem{Header="Hide when covered",IsCheckable=true,IsChecked=deployment.hide_when_covered};hide.Click+=delegate{deployment.hide_when_covered=hide.IsChecked;SaveBuilderDesktop();};menu.Items.Add(hide);menu.Items.Add(new Separator());
  var remove=new MenuItem{Header="Remove from desktop"};remove.Click+=delegate{RemoveBuilderDeployment(deployment.id);};menu.Items.Add(remove);window.ContextMenu=menu;
  window.Closed+=delegate{builderDesktopWindows.Remove(deployment.id);};DrawBuilderDesktop(deployment);window.Show();
 }
 void RemoveBuilderDeployment(string id){Window window;if(builderDesktopWindows.TryGetValue(id,out window))window.Close();builderDesktopExecutions.Remove(id);if(builderDesktopState!=null)builderDesktopState.widgets.RemoveAll(x=>x.id==id);SaveBuilderDesktop();}
 void RefreshBuilderDesktop(){if(builderDesktopState==null)return;foreach(var deployment in builderDesktopState.widgets.Where(x=>x.enabled&&x.project!=null).ToArray()){Window window;if(!builderDesktopWindows.TryGetValue(deployment.id,out window)){ShowBuilderDesktop(deployment);continue;}bool covered=deployment.hide_when_covered&&BuilderDesktopCovered(window);if(covered)window.Hide();else{DrawBuilderDesktop(deployment);if(!window.IsVisible)window.Show();}}}
 void DrawBuilderDesktop(WidgetBuilderDeployment deployment){Window window;if(!builderDesktopWindows.TryGetValue(deployment.id,out window))return;var project=deployment.project;var runtime=TickBuilderDesktopRuntime(deployment);double width=Math.Max(20,DesktopBuilderNumber(project,project.ui_tree,"width",360,runtime)),height=Math.Max(20,DesktopBuilderNumber(project,project.ui_tree,"height",180,runtime));double widgetScale=SurfaceScale("Widgets");window.Width=width*widgetScale;window.Height=height*widgetScale;window.Left=deployment.relative_x>=0?WidgetPositionFromRatio(deployment.relative_x,true,window.Width):Clamp(deployment.x,SystemParameters.VirtualScreenLeft,SystemParameters.VirtualScreenLeft+SystemParameters.VirtualScreenWidth-width);window.Top=deployment.relative_y>=0?WidgetPositionFromRatio(deployment.relative_y,false,window.Height):Clamp(deployment.y,SystemParameters.VirtualScreenTop,SystemParameters.VirtualScreenTop+SystemParameters.VirtualScreenHeight-height);var builderFace=RenderDesktopBuilderNode(project.ui_tree,project,runtime);ApplySurfaceScale(builderFace,"Widgets");window.Content=builderFace;}
 Dictionary<string,object> DesktopBuilderRuntime(WidgetBuilderProject project){var values=new Dictionary<string,object>();foreach(var variable in project.variables)values[variable.name]=variable.initial;values["time"]=DateTime.Now.ToString("HH:mm:ss");values["date"]=DateTime.Now.ToString("ddd, d MMM");values["cpu_usage"]=(DateTime.Now.Second*7)%91+5;values["ram_usage"]=62.0;if(!values.ContainsKey("running_apps"))values["running_apps"]=new[]{"Browser","Editor","Music"};return values;}
 object DesktopBuilderResolved(WidgetBuilderProject project,BuilderNode node,string key,object fallback,Dictionary<string,object> runtime){BuilderValue property;if(!node.properties.TryGetValue(key,out property))return fallback;if(!String.IsNullOrEmpty(property.binding)){if(property.binding.StartsWith("block:")){var state=new BuilderDesktopExecution{values=runtime};return DesktopReporterValue(project,state,project.logic_graph.FirstOrDefault(x=>x.id==property.binding.Substring(6)))??fallback;}string name=property.binding.StartsWith("var:")?property.binding.Substring(4):property.binding;object value;return runtime.TryGetValue(name,out value)?value:fallback;}return property.value??fallback;}
 double DesktopBuilderNumber(WidgetBuilderProject project,BuilderNode node,string key,double fallback,Dictionary<string,object> runtime=null){try{return Convert.ToDouble(DesktopBuilderResolved(project,node,key,fallback,runtime??DesktopBuilderRuntime(project)));}catch{return fallback;}}
 string DesktopBuilderString(WidgetBuilderProject project,BuilderNode node,string key,string fallback,Dictionary<string,object> runtime){return Convert.ToString(DesktopBuilderResolved(project,node,key,fallback,runtime)??fallback);}
 FrameworkElement RenderDesktopBuilderNode(BuilderNode node,WidgetBuilderProject project,Dictionary<string,object> runtime){
  double width=DesktopBuilderNumber(project,node,"width",140,runtime),height=DesktopBuilderNumber(project,node,"height",90,runtime),spacing=DesktopBuilderNumber(project,node,"item_spacing",8,runtime);Panel layout=node.type=="row"?(Panel)new StackPanel{Orientation=Orientation.Horizontal}:node.type=="column"?(Panel)new StackPanel{Orientation=Orientation.Vertical}:node.type=="grid"?(Panel)new UniformGrid{Columns=Math.Max(1,(int)DesktopBuilderNumber(project,node,"columns",3,runtime)),Rows=Math.Max(0,(int)DesktopBuilderNumber(project,node,"rows",0,runtime))}:(Panel)new Canvas();layout.Width=width;layout.Height=height;layout.ClipToBounds=true;
  foreach(var child in node.children){var visual=RenderDesktopBuilderNode(child,project,runtime);if(layout is Canvas){Canvas.SetLeft(visual,DesktopBuilderNumber(project,child,"x",20,runtime));Canvas.SetTop(visual,DesktopBuilderNumber(project,child,"y",20,runtime));}else visual.Margin=new Thickness(spacing/2);layout.Children.Add(visual);}DesktopBuilderBoundChildren(node,project,runtime,layout,spacing);
  FrameworkElement content=layout;string label=DesktopBuilderString(project,node,"content",node.type,runtime);var foreground=new SolidColorBrush(Parse(DesktopBuilderString(project,node,"color","#FFFFFF",runtime),Colors.White));
  if(node.type=="text"||node.type=="icon"||node.type=="label"||node.type=="rich_text")content=new TextBlock{Text=label,FontFamily=new FontFamily(DesktopBuilderString(project,node,"font_family","Segoe UI",runtime)),FontSize=DesktopBuilderNumber(project,node,"font_size",15,runtime),Foreground=foreground,Width=width,Height=height,TextWrapping=TextWrapping.Wrap,VerticalAlignment=VerticalAlignment.Center};
  else if(node.type=="button")content=new TextBlock{Text=label,Foreground=foreground,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
  else if(node.type=="dropdown")content=new TextBlock{Text=label+"   ▾",Foreground=foreground,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(10,0,0,0)};
  else if(node.type=="slider")content=new ProgressBar{Minimum=0,Maximum=100,Value=62,Height=8,Margin=new Thickness(10),VerticalAlignment=VerticalAlignment.Center,Foreground=accentBrush,Background=cardBrush};else if(node.type=="progress_bar")content=BuilderProgressVisual(width,height,DesktopBuilderString(project,node,"progress_style","line",runtime),DesktopBuilderString(project,node,"direction","left-to-right",runtime),DesktopBuilderNumber(project,node,"value",62,runtime),DesktopBuilderNumber(project,node,"maximum",100,runtime),DesktopBuilderNumber(project,node,"thickness",8,runtime),foreground,new SolidColorBrush(Parse(DesktopBuilderString(project,node,"track_color","#395155",runtime),Color.FromRgb(57,81,85))),(int)DesktopBuilderNumber(project,node,"dash_count",18,runtime));
  else if(node.type=="toggle")content=new Border{Width=42,Height=22,CornerRadius=new CornerRadius(11),Background=accentBrush,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
  else if(node.type=="divider")content=new Border{Height=1,Background=foreground,VerticalAlignment=VerticalAlignment.Center};
  else if(node.type=="image")content=new TextBlock{Text="▧",Foreground=foreground,FontSize=28,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
  else if(node.type=="prefab_instance"){string id=DesktopBuilderString(project,node,"prefab_id","",runtime);var prefab=project.prefabs.FirstOrDefault(x=>x.id==id);if(prefab!=null&&prefab.root!=null)content=RenderDesktopBuilderNode(prefab.root,project,runtime);}
  var border=new Border{Width=width,Height=height,Child=content,Opacity=Math.Max(0,Math.Min(1,DesktopBuilderNumber(project,node,"opacity",1,runtime))),CornerRadius=new CornerRadius(DesktopBuilderNumber(project,node,"corner_radius",0,runtime)),Background=new SolidColorBrush(Parse(DesktopBuilderString(project,node,"background","#00000000",runtime),Colors.Transparent)),BorderBrush=new SolidColorBrush(Parse(DesktopBuilderString(project,node,"border","#00000000",runtime),Colors.Transparent)),BorderThickness=new Thickness(1)};
  var transforms=new TransformGroup();transforms.Children.Add(new ScaleTransform(DesktopBuilderNumber(project,node,"scale",1,runtime),DesktopBuilderNumber(project,node,"scale",1,runtime)));transforms.Children.Add(new RotateTransform(DesktopBuilderNumber(project,node,"rotation",0,runtime),width/2,height/2));border.RenderTransform=transforms;return border;
 }
 void DesktopBuilderBoundChildren(BuilderNode node,WidgetBuilderProject project,Dictionary<string,object> runtime,Panel layout,double spacing){string binding=DesktopBuilderString(project,node,"children_binding","",runtime);if(String.IsNullOrWhiteSpace(binding))return;string key=binding.StartsWith("var:")?binding.Substring(4):binding;object source;if(!runtime.TryGetValue(key,out source))return;var values=source as IEnumerable;if(values==null||source is string)return;string prefabId=DesktopBuilderString(project,node,"template_prefab","",runtime);var prefab=project.prefabs.FirstOrDefault(x=>x.id==prefabId||x.name==prefabId);foreach(object value in values){BuilderNode item=prefab!=null&&prefab.root!=null?CloneBuilderNode(prefab.root):NewBuilderNode("text");DesktopApplyItem(item,value);var visual=RenderDesktopBuilderNode(item,project,runtime);visual.Margin=new Thickness(spacing/2);layout.Children.Add(visual);}}
 void DesktopApplyItem(BuilderNode node,object value){string text=Convert.ToString(value);if(node.type=="text"||node.type=="label"||node.type=="button")SetBuilder(node,"content",text);else if(node.type=="icon")SetBuilder(node,"content",String.IsNullOrEmpty(text)?"•":text.Substring(0,1).ToUpperInvariant());if(node.children.Count>0)DesktopApplyItem(node.children[0],value);}
 bool BuilderDesktopCovered(Window window){if(window==null||!window.IsVisible||new WindowInteropHelper(window).Handle==IntPtr.Zero)return false;Point point=window.PointToScreen(new Point());var source=PresentationSource.FromVisual(window);var scale=source==null?Matrix.Identity:source.CompositionTarget.TransformToDevice;var bounds=new Rect(point,new Size(window.Width*scale.M11,window.Height*scale.M22));bool covered=false;Native.EnumWindows(delegate(IntPtr h,IntPtr unused){if(!Native.IsWindowVisible(h)||Native.IsIconic(h)||(Native.GetWindowLong(h,-20)&0x80)!=0)return true;uint pid;Native.GetWindowThreadProcessId(h,out pid);if(pid==System.Diagnostics.Process.GetCurrentProcess().Id)return true;int cloaked;Native.DwmGetWindowAttribute(h,14,out cloaked,4);if(cloaked!=0)return true;var name=new System.Text.StringBuilder(128);Native.GetClassName(h,name,128);if(name.ToString()=="Progman"||name.ToString()=="WorkerW"||name.ToString().Contains("TrayWnd"))return true;Native.RECT rect;if(Native.GetWindowRect(h,out rect)&&bounds.IntersectsWith(new Rect(rect.Left,rect.Top,rect.Right-rect.Left,rect.Bottom-rect.Top))){covered=true;return false;}return true;},IntPtr.Zero);return covered;}
} }
