using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;

namespace Awl { partial class Shell {
 void ShowBuilderExamples(){var popup=new Window{Title="Widget Builder examples",Width=430,Height=390,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=System.Windows.Media.Brushes.Transparent,Owner=builderWindow,WindowStartupLocation=WindowStartupLocation.CenterOwner,ShowInTaskbar=false};var host=new StackPanel();host.Children.Add(BuilderHeading("Starter widgets"));host.Children.Add(BuilderSub("Choose a complete UI, variables, and mock logic graph. This replaces the current builder project."));foreach(string name in new[]{"Recent apps dock","Clipboard hover panel","Calendar","System monitor"}){string example=name;host.Children.Add(BuilderPrimaryButton("sparkles",example,()=>{LoadBuilderExample(example);popup.Close();}));}host.Children.Add(BuilderPrimaryButton("close","Cancel",()=>popup.Close()));popup.Content=new Border{Background=panelBrush,BorderBrush=accentBrush,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(18),Padding=new Thickness(16),Child=host};popup.ShowDialog();}
 void LoadBuilderExample(string name){var project=new WidgetBuilderProject{name=name};var root=NewBuilderNode("panel");root.name=name;SetBuilder(root,"width",name=="Calendar"?500.0:560.0);SetBuilder(root,"height",name=="System monitor"?210.0:320.0);SetBuilder(root,"background","#18383C");SetBuilder(root,"corner_radius",22.0);project.ui_tree=root;
  if(name=="Recent apps dock"){var column=NewBuilderNode("column");column.name="app sections";SetBuilder(column,"x",20.0);SetBuilder(column,"y",20.0);SetBuilder(column,"width",520.0);SetBuilder(column,"height",280.0);root.children.Add(column);foreach(string label in new[]{"Pinned apps","Running apps"}){var grid=NewBuilderNode("grid");grid.name=label;SetBuilder(grid,"width",500.0);SetBuilder(grid,"height",118.0);SetBuilder(grid,"columns",5.0);SetBuilder(grid,"children_binding","var:running_apps");SetBuilder(grid,"template_prefab","prefab_app_template");column.children.Add(grid);}var item=NewBuilderNode("panel");item.name="app template";SetBuilder(item,"width",82.0);SetBuilder(item,"height",82.0);var icon=NewBuilderNode("icon");icon.name="icon";SetBuilder(icon,"content","◆");SetBuilder(icon,"x",24.0);SetBuilder(icon,"y",18.0);item.children.Add(icon);project.prefabs.Add(new BuilderPrefab{id="prefab_app_template",name="app template",root=item,exposed_params={new BuilderPrefabParam{name="icon",target_node=icon.id,property="content"}}});project.variables.Add(new BuilderVariable{name="running_apps",type="list",scope="widget",initial=new[]{"Browser","Editor","Music"}});var load=new BuilderBlock{type="events.on_load",x=50,y=60};var interval=new BuilderBlock{type="events.on_interval",x=250,y=60};load.next=interval.id;project.logic_graph.Add(load);project.logic_graph.Add(interval);}
  else if(name=="Clipboard hover panel"){var stack=NewBuilderNode("stack");stack.name="hover states";SetBuilder(stack,"x",20.0);SetBuilder(stack,"y",20.0);SetBuilder(stack,"width",520.0);SetBuilder(stack,"height",280.0);root.children.Add(stack);var collapsed=NewBuilderNode("panel");collapsed.name="collapsed";SetBuilder(collapsed,"width",70.0);SetBuilder(collapsed,"height",70.0);var icon=NewBuilderNode("icon");SetBuilder(icon,"content","▣");collapsed.children.Add(icon);stack.children.Add(collapsed);var expanded=NewBuilderNode("column");expanded.name="clipboard entries";SetBuilder(expanded,"x",84.0);SetBuilder(expanded,"width",410.0);SetBuilder(expanded,"height",250.0);SetBuilder(expanded,"children_binding","var:clipboard_items");stack.children.Add(expanded);project.variables.Add(new BuilderVariable{name="clipboard_items",type="list",scope="widget",initial=new[]{"Copied text","Previous value"}});project.logic_graph.Add(new BuilderBlock{type="events.on_interval",x=60,y=60,parameters={{"seconds",new BuilderValue{value=1.0}}}});}
  else if(name=="Calendar"){var grid=NewBuilderNode("grid");grid.name="days";SetBuilder(grid,"x",20.0);SetBuilder(grid,"y",55.0);SetBuilder(grid,"width",460.0);SetBuilder(grid,"height",235.0);SetBuilder(grid,"columns",7.0);SetBuilder(grid,"rows",5.0);root.children.Add(grid);for(int i=1;i<=31;i++){var day=NewBuilderNode("button");day.name="day "+i;SetBuilder(day,"content",i.ToString());SetBuilder(day,"width",56.0);SetBuilder(day,"height",38.0);grid.children.Add(day);}project.variables.Add(new BuilderVariable{name="selected_day",type="number",scope="widget",initial=1.0});project.logic_graph.Add(new BuilderBlock{type="events.on_load",x=60,y=60});}
  else {var row=NewBuilderNode("row");row.name="metrics";SetBuilder(row,"x",15.0);SetBuilder(row,"y",15.0);SetBuilder(row,"width",530.0);SetBuilder(row,"height",180.0);root.children.Add(row);foreach(string metric in new[]{"CPU","RAM","Disk"}){var panel=NewBuilderNode("panel");panel.name=metric;SetBuilder(panel,"width",162.0);SetBuilder(panel,"height",160.0);var label=NewBuilderNode("label");SetBuilder(label,"content",metric+" 34%");SetBuilder(label,"x",15.0);SetBuilder(label,"y",15.0);SetBuilder(label,"width",130.0);panel.children.Add(label);row.children.Add(panel);}project.variables.Add(new BuilderVariable{name="cpu_usage",type="number",scope="global",initial=34.0});project.variables.Add(new BuilderVariable{name="ram_usage",type="number",scope="global",initial=62.0});project.logic_graph.Add(new BuilderBlock{type="events.on_interval",x=60,y=60,parameters={{"seconds",new BuilderValue{value=1.0}}}});}
  builderProject=project;builderSelected=root;builderSelectedBlock=null;builderHistory.Clear();builderHistoryIndex=-1;SnapshotBuilder(false);SaveBuilderProject(BuilderFile);builderTab="UI";DrawBuilder();}
} }
