using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Rectangle=System.Windows.Shapes.Rectangle;
using System.Windows.Threading;
using Forms=System.Windows.Forms;

namespace Awl { partial class Shell {
 [DllImport("user32.dll")]static extern bool SetWindowDisplayAffinity(IntPtr window,uint affinity);
 [StructLayout(LayoutKind.Sequential)]struct CURSORINFO{public int Size,Flags;public IntPtr Handle;public Native.POINT Position;}
 [DllImport("user32.dll")]static extern bool GetCursorInfo(ref CURSORINFO info);
 [DllImport("user32.dll")]static extern IntPtr CopyIcon(IntPtr icon);
 [DllImport("user32.dll")]static extern IntPtr GetDC(IntPtr window);
 [DllImport("user32.dll")]static extern int ReleaseDC(IntPtr window,IntPtr dc);
 [DllImport("gdi32.dll")]static extern bool BitBlt(IntPtr target,int x,int y,int width,int height,IntPtr source,int sourceX,int sourceY,uint operation);

 Window captureWindow,captureOverlay,captureRecordWindow,captureReviewWindow;string captureSource="Region",captureReviewPath="";bool captureReviewKeep;IntPtr captureTarget;ScreenRecorder activeRecorder;RollingRecorder rollingRecorder;DispatcherTimer captureUiTimer;DateTime captureStarted;List<Window> captureHiddenWindows=new List<Window>();IntPtr desktopIcons;
 string CaptureRuntime(){string directory=Path.Combine(Root,"CaptureRuntime");string executable=Path.Combine(directory,"ffmpeg.exe");if(File.Exists(executable))return executable;Directory.CreateDirectory(directory);var assembly=typeof(Shell).Assembly;foreach(string resource in assembly.GetManifestResourceNames().Where(x=>x.StartsWith("Awl.Capture.",StringComparison.Ordinal))){string name=resource.Substring("Awl.Capture.".Length);string destination=Path.Combine(directory,name);using(var input=assembly.GetManifestResourceStream(resource))using(var output=File.Create(destination))input.CopyTo(output);}return File.Exists(executable)?executable:null;}
 void ExcludeCaptureWindow(Window window){window.SourceInitialized+=delegate{try{SetWindowDisplayAffinity(new WindowInteropHelper(window).Handle,0x11);}catch{}};}
 Button CaptureChoice(string icon,string label,bool selected,Action action){var button=Action("",action,selected);var stack=new StackPanel{HorizontalAlignment=HorizontalAlignment.Center};var art=BuilderSvgIcon(icon,30,selected?new SolidColorBrush(Color.FromRgb(87,218,173)):ink);art.HorizontalAlignment=HorizontalAlignment.Center;stack.Children.Add(art);var text=Text(label,11,button.Foreground);text.FontWeight=FontWeights.SemiBold;text.HorizontalAlignment=HorizontalAlignment.Center;text.Margin=new Thickness(0,5,0,0);stack.Children.Add(text);button.Content=stack;button.MinWidth=78;button.Height=78;return button;}
 Button CaptureMenuItem(string icon,string title,string detail,Action action){var button=Action("",action);button.HorizontalContentAlignment=HorizontalAlignment.Stretch;button.MinWidth=238;var row=new Grid();row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(34)});row.ColumnDefinitions.Add(new ColumnDefinition());var art=BuilderSvgIcon(icon,24,accentBrush);art.VerticalAlignment=VerticalAlignment.Center;row.Children.Add(art);var labels=new StackPanel();var name=Text(title,13);name.FontWeight=FontWeights.SemiBold;labels.Children.Add(name);if(!String.IsNullOrEmpty(detail))labels.Children.Add(Text(detail,10,mutedBrush));Grid.SetColumn(labels,1);row.Children.Add(labels);button.Content=row;return button;}
 Button CaptureAction(string icon,string label,Action action){var button=Action("",action);button.MinHeight=44;button.Padding=new Thickness(13,10,13,10);button.Cursor=Cursors.Hand;button.Content=BuilderIconLabel(icon,label,button.Foreground,23);return button;}
 FrameworkElement CaptureToolbarButton(){var button=Button("","Capture · Alt + Shift + R",ShowCaptureTool);button.Content=BuilderSvgIcon("camera",19,ink);return button;}
 Popup CaptureDropdown(FrameworkElement anchor,IEnumerable<Tuple<string,string,string,Action>> entries){var list=new StackPanel();Popup popup=null;foreach(var entry in entries){var value=entry;list.Children.Add(CaptureMenuItem(value.Item1,value.Item2,value.Item3,()=>{if(popup!=null)popup.IsOpen=false;value.Item4();}));}popup=new Popup{PlacementTarget=anchor,Placement=PlacementMode.Bottom,VerticalOffset=7,AllowsTransparency=true,StaysOpen=false,Child=PopupSurface(list,14)};popup.Opened+=delegate{appMenuOpen=true;};popup.Closed+=delegate{appMenuOpen=false;};popup.IsOpen=true;return popup;}
 void ShowCaptureTool(){if(captureWindow!=null&&captureWindow.IsVisible){captureWindow.Activate();return;}captureWindow=new Window{Title="Awl Capture",Width=640,Height=118,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,Topmost=true,ShowInTaskbar=false,WindowStartupLocation=WindowStartupLocation.Manual};ExcludeCaptureWindow(captureWindow);captureWindow.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.Key==Key.Escape)captureWindow.Close();};captureWindow.Closed+=delegate{captureWindow=null;};DrawCaptureStart(false);captureWindow.Show();PlaceCaptureWindow(captureWindow);}
 void PlaceCaptureWindow(Window window){window.Left=SystemParameters.WorkArea.Left+(SystemParameters.WorkArea.Width-window.Width)/2;window.Top=SystemParameters.WorkArea.Top+14;}
 void SetCaptureContent(Window window,FrameworkElement content,string surface,double width,double height){double scale=SurfaceScale(surface);ApplySurfaceScale(content,surface);window.Width=width*scale;window.Height=height*scale;window.Content=content;}
 bool CaptureWindowContains(Window window,Point point){return window!=null&&window.IsVisible&&point.X>=window.Left&&point.X<=window.Left+window.ActualWidth&&point.Y>=window.Top&&point.Y<=window.Top+window.ActualHeight;}
 void DiscardCaptureReview(){if(captureReviewWindow!=null)captureReviewWindow.Close();}
 void DrawCaptureStart(bool settings){if(captureWindow==null)return;if(settings){var panel=new StackPanel{Width=360};var head=new DockPanel();var back=Button("","Back",()=>DrawCaptureStart(false));back.Content=BuilderSvgIcon("undo",18,ink);back.Width=42;DockPanel.SetDock(back,Dock.Right);head.Children.Add(back);var title=Text("Hide from recording",16);title.FontWeight=FontWeights.SemiBold;head.Children.Add(title);panel.Children.Add(head);panel.Children.Add(Switch("Awl UI",cfg.CaptureHideShell,v=>{cfg.CaptureHideShell=v;SaveConfig();}));panel.Children.Add(Switch("Mouse cursor",cfg.CaptureHideCursor,v=>{cfg.CaptureHideCursor=v;SaveConfig();}));panel.Children.Add(Switch("Desktop icons",cfg.CaptureHideDesktopIcons,v=>{cfg.CaptureHideDesktopIcons=v;SaveConfig();}));var note=Text("Desktop icon hiding may vary by Windows build.",10,mutedBrush);note.Margin=new Thickness(5,2,0,0);panel.Children.Add(note);SetCaptureContent(captureWindow,PopupSurface(panel,18),"Capture chooser",410,264);PlaceCaptureWindow(captureWindow);return;}var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(CaptureChoice("region","Region",captureSource=="Region",()=>{captureSource="Region";DrawCaptureStart(false);}));row.Children.Add(CaptureChoice("window","Window",captureSource=="Window",ShowCaptureWindowMenu));row.Children.Add(CaptureChoice("fullscreen","Full screen",captureSource=="Full screen",()=>{captureSource="Full screen";DrawCaptureStart(false);}));row.Children.Add(new Border{Width=1,Height=48,Background=cardBrush,Margin=new Thickness(7,9,7,9)});row.Children.Add(CaptureChoice("screenshot","Screenshot",false,()=>BeginCapture(false)));row.Children.Add(CaptureChoice("record","Record",false,()=>BeginCapture(true)));Button history=null;history=CaptureChoice("history","Last 30s",false,()=>ShowLast30Menu(history));history.ToolTip="Save the previous 30 seconds";row.Children.Add(history);var settingsButton=CaptureChoice("wrench","",false,()=>DrawCaptureStart(true));settingsButton.MinWidth=48;row.Children.Add(settingsButton);var close=Button("","Close capture",()=>captureWindow.Close());close.Content=BuilderSvgIcon("close",18,ink);close.Width=34;close.Height=34;close.Margin=new Thickness(2,17,0,0);row.Children.Add(close);SetCaptureContent(captureWindow,PopupSurface(row,18),"Capture chooser",760,130);PlaceCaptureWindow(captureWindow);}
 void ShowCaptureWindowMenu(){captureSource="Window";var entries=new List<Tuple<string,string,string,Action>>();foreach(var item in AltTabCandidates().Take(16)){var candidate=item;entries.Add(Tuple.Create("window",item.Item2,"Select this window",(Action)(()=>{captureTarget=candidate.Item1;DrawCaptureStart(false);})));}CaptureDropdown(captureWindow,entries);DrawCaptureStart(false);}
 void ShowLast30Menu(FrameworkElement anchor){var rect=TargetScreen().Bounds;var entries=CapturePresets(rect).Select(value=>{string preset=value;var settings=PresetValues(preset,rect);string detail=settings.Item1+" × "+settings.Item2+(settings.Item4>0?" · "+FileSize(settings.Item4)+" limit":"");return Tuple.Create("history",preset,detail,(Action)(()=>SaveLast30(preset)));}).ToList();CaptureDropdown(anchor,entries);}
 async void SaveLast30(string preset){cfg.CapturePreset=preset;SaveConfig();if(captureWindow!=null)captureWindow.Hide();string output=Path.Combine(Path.GetTempPath(),"Awl-last-30s-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".mp4");var progressWindow=new Window{Title="Saving last 30 seconds",Width=330,Height=92,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,Topmost=true,ShowInTaskbar=false,WindowStartupLocation=WindowStartupLocation.CenterScreen};ExcludeCaptureWindow(progressWindow);var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(BuilderSvgIcon("history",24,accentBrush));var label=Text("Encoding the last 30 seconds…",13);label.Margin=new Thickness(12,0,0,0);row.Children.Add(label);SetCaptureContent(progressWindow,PopupSurface(row,18),"Recording controls",330,92);progressWindow.Show();bool saved=false;try{if(rollingRecorder==null)StartRollingCapture();var recorder=rollingRecorder;rollingRecorder=null;if(recorder!=null)await Task.Run(()=>recorder.Stop());saved=await Task.Run(()=>EncodeRollingCapture(recorder,preset,output));StartRollingCapture();}catch(Exception error){Log("Last 30 seconds: "+error.Message);}progressWindow.Close();if(saved)ShowCaptureReview(output,true,TimeSpan.FromSeconds(30));else{MessageBox.Show("The rolling buffer does not contain a complete frame yet. Leave Awl running for a few seconds, then try again.","Last 30 seconds");if(captureWindow!=null)captureWindow.Show();}}
 void StartRollingCapture(){if(rollingRecorder!=null)return;try{string runtime=CaptureRuntime();if(String.IsNullOrEmpty(runtime))return;string directory=Path.Combine(Root,"CaptureBuffer");Directory.CreateDirectory(directory);foreach(string file in Directory.GetFiles(directory,"segment-*.mp4"))try{File.Delete(file);}catch{}var rect=TargetScreen().Bounds;rollingRecorder=new RollingRecorder(this,runtime,rect,directory);rollingRecorder.Start();}catch(Exception error){Log("Rolling capture: "+error.Message);}}
 bool EncodeRollingCapture(RollingRecorder recorder,string preset,string output){if(recorder==null)return false;var ordered=recorder.Files().OrderBy(x=>File.GetLastWriteTimeUtc(x)).ToList();var files=ordered.Skip(Math.Max(0,ordered.Count-6)).ToList();if(files.Count==0)return false;string list=Path.Combine(Path.GetDirectoryName(files[0]),"concat-"+Guid.NewGuid().ToString("N")+".txt");File.WriteAllLines(list,files.Select(x=>"file '"+x.Replace("'","'\\''")+"'"));var settings=PresetValues(preset,TargetScreen().Bounds);string args="-y -f concat -safe 0 -i \""+list+"\" -vf scale="+settings.Item1+":"+settings.Item2+":flags=lanczos -r 15 -c:v libopenh264 -b:v "+settings.Item3+" -maxrate "+settings.Item3+" -bufsize "+(settings.Item3*2)+" -pix_fmt yuv420p -movflags +faststart \""+output+"\"";var process=Process.Start(new ProcessStartInfo(CaptureRuntime(),args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true});process.StandardError.ReadToEnd();process.WaitForExit();try{File.Delete(list);}catch{}return process.ExitCode==0&&File.Exists(output)&&new FileInfo(output).Length>1000;} Forms.Screen TargetScreen(){return Forms.Screen.PrimaryScreen;}
 System.Drawing.Rectangle CaptureRectangle(){if(captureSource=="Window"&&captureTarget!=IntPtr.Zero){Native.RECT value;if(Native.GetWindowRect(captureTarget,out value))return System.Drawing.Rectangle.FromLTRB(value.Left,value.Top,value.Right,value.Bottom);}return TargetScreen().Bounds;}
 async void BeginCapture(bool record){if(captureSource=="Window"&&captureTarget==IntPtr.Zero){ShowCaptureWindowMenu();return;}if(captureSource=="Region"){ShowRegionSelector(rect=>{if(rect.Width>4&&rect.Height>4){if(record)ShowRecordingBar(rect);else TakeScreenshot(rect);}});return;}if(captureSource=="Window"){if(captureWindow!=null)captureWindow.Hide();if(Native.IsIconic(captureTarget))Native.ShowWindowAsync(captureTarget,9);Native.SetForegroundWindow(captureTarget);await Task.Delay(240);}var rectangle=CaptureRectangle();if(record)ShowRecordingBar(rectangle);else TakeScreenshot(rectangle);}
 void ShowRegionSelector(Action<System.Drawing.Rectangle> selected){if(captureWindow!=null)captureWindow.Hide();var bounds=Forms.SystemInformation.VirtualScreen;captureOverlay=new Window{Title="Select capture region",Left=bounds.Left,Top=bounds.Top,Width=bounds.Width,Height=bounds.Height,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=new SolidColorBrush(Color.FromArgb(86,0,0,0)),Topmost=true,ShowInTaskbar=false,Cursor=Cursors.Cross};ExcludeCaptureWindow(captureOverlay);var canvas=new Canvas();var outline=new Rectangle{Stroke=accentBrush,StrokeThickness=2,Fill=new SolidColorBrush(Color.FromArgb(24,90,230,180)),Visibility=Visibility.Collapsed};canvas.Children.Add(outline);captureOverlay.Content=canvas;Point start=new Point();captureOverlay.MouseLeftButtonDown+=delegate(object sender,MouseButtonEventArgs e){start=e.GetPosition(canvas);outline.Visibility=Visibility.Visible;Canvas.SetLeft(outline,start.X);Canvas.SetTop(outline,start.Y);captureOverlay.CaptureMouse();};captureOverlay.MouseMove+=delegate(object sender,MouseEventArgs e){if(e.LeftButton!=MouseButtonState.Pressed)return;var now=e.GetPosition(canvas);Canvas.SetLeft(outline,Math.Min(start.X,now.X));Canvas.SetTop(outline,Math.Min(start.Y,now.Y));outline.Width=Math.Abs(now.X-start.X);outline.Height=Math.Abs(now.Y-start.Y);};captureOverlay.MouseLeftButtonUp+=delegate(object sender,MouseButtonEventArgs e){var now=e.GetPosition(canvas);var a=captureOverlay.PointToScreen(start);var b=captureOverlay.PointToScreen(now);var rect=System.Drawing.Rectangle.FromLTRB((int)Math.Min(a.X,b.X),(int)Math.Min(a.Y,b.Y),(int)Math.Max(a.X,b.X),(int)Math.Max(a.Y,b.Y));captureOverlay.ReleaseMouseCapture();captureOverlay.Close();captureOverlay=null;selected(rect);};captureOverlay.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.Key==Key.Escape){captureOverlay.Close();captureOverlay=null;if(captureWindow!=null)captureWindow.Show();}};captureOverlay.Show();captureOverlay.Activate();}
 System.Drawing.Bitmap CaptureBitmap(System.Drawing.Rectangle rect,bool resize=false,int width=0,int height=0){var source=new System.Drawing.Bitmap(rect.Width,rect.Height,System.Drawing.Imaging.PixelFormat.Format32bppArgb);using(var graphics=System.Drawing.Graphics.FromImage(source)){IntPtr desktop=GetDC(IntPtr.Zero),target=graphics.GetHdc();bool copied=false;try{if(desktop!=IntPtr.Zero)copied=BitBlt(target,0,0,rect.Width,rect.Height,desktop,rect.Left,rect.Top,0x40CC0020);}finally{graphics.ReleaseHdc(target);if(desktop!=IntPtr.Zero)ReleaseDC(IntPtr.Zero,desktop);}if(!copied)try{graphics.CopyFromScreen(rect.Left,rect.Top,0,0,rect.Size,System.Drawing.CopyPixelOperation.SourceCopy);}catch{}if(!cfg.CaptureHideCursor)DrawMouse(graphics,rect);}if(!resize||width==rect.Width&&height==rect.Height)return source;var result=new System.Drawing.Bitmap(width,height,System.Drawing.Imaging.PixelFormat.Format32bppArgb);using(var graphics=System.Drawing.Graphics.FromImage(result)){graphics.InterpolationMode=System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;graphics.DrawImage(source,0,0,width,height);}source.Dispose();return result;}
 void DrawMouse(System.Drawing.Graphics graphics,System.Drawing.Rectangle area){var info=new CURSORINFO{Size=Marshal.SizeOf(typeof(CURSORINFO))};if(!GetCursorInfo(ref info)||info.Flags!=1||!area.Contains(info.Position.X,info.Position.Y))return;IntPtr copy=CopyIcon(info.Handle);if(copy==IntPtr.Zero)return;try{using(var icon=System.Drawing.Icon.FromHandle(copy))graphics.DrawIcon(icon,info.Position.X-area.Left,info.Position.Y-area.Top);}finally{Native.DestroyIcon(copy);}}
 void HideCapturedSurfaces(){captureHiddenWindows.Clear();if(cfg.CaptureHideShell)foreach(Window window in Current.Windows.Cast<Window>().ToArray()){if(window==captureRecordWindow||window==captureOverlay||window==captureReviewWindow||window==captureWindow||!window.IsVisible)continue;captureHiddenWindows.Add(window);window.Hide();}if(captureWindow!=null)captureWindow.Hide();if(cfg.CaptureHideDesktopIcons){desktopIcons=FindWindowEx(Native.FindWindow("Progman",null),IntPtr.Zero,"SHELLDLL_DefView",null);if(desktopIcons!=IntPtr.Zero)Native.ShowWindow(desktopIcons,0);}}
 void RestoreCapturedSurfaces(){foreach(var window in captureHiddenWindows.ToArray())try{window.Show();}catch{}captureHiddenWindows.Clear();if(desktopIcons!=IntPtr.Zero){Native.ShowWindow(desktopIcons,5);desktopIcons=IntPtr.Zero;}}
 async void TakeScreenshot(System.Drawing.Rectangle rect){HideCapturedSurfaces();await Task.Delay(160);string path=Path.Combine(Path.GetTempPath(),"Awl-shot-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".png");try{using(var image=CaptureBitmap(rect))image.Save(path,System.Drawing.Imaging.ImageFormat.Png);RestoreCapturedSurfaces();ShowCaptureReview(path,false,TimeSpan.Zero);}catch(Exception error){RestoreCapturedSurfaces();MessageBox.Show(error.Message,"Screenshot failed");if(captureWindow!=null)captureWindow.Show();}}
 string[] CapturePresets(System.Drawing.Rectangle rect){var values=new List<string>{"Discord Free","Discord Basic","Discord Nitro"};if(rect.Height>=480)values.Add("480p");if(rect.Height>=720)values.Add("720p");if(rect.Height>=1080)values.Add("1080p");if(rect.Height>=1440)values.Add("1440p");if(rect.Height>=2160)values.Add("4K");values.Add("Native · "+rect.Width+"×"+rect.Height);return values.Distinct().ToArray();}
 Tuple<int,int,int,long> PresetValues(string preset,System.Drawing.Rectangle source){int height=source.Height,bitrate=6000000;long limit=0;if(preset=="Discord Free"){height=Math.Min(720,height);bitrate=900000;limit=10L*1000*1000;}else if(preset=="Discord Basic"){height=Math.Min(1080,height);bitrate=3500000;limit=50L*1000*1000;}else if(preset=="Discord Nitro"){bitrate=10000000;limit=500L*1000*1000;}else if(preset=="480p"){height=Math.Min(480,height);bitrate=1200000;}else if(preset=="720p"){height=Math.Min(720,height);bitrate=2800000;}else if(preset=="1080p"){height=Math.Min(1080,height);bitrate=6000000;}else if(preset=="1440p"){height=Math.Min(1440,height);bitrate=11000000;}else if(preset=="4K"){height=Math.Min(2160,height);bitrate=22000000;}int width=(int)Math.Round(source.Width*(height/(double)source.Height));width=Math.Max(2,width/2*2);height=Math.Max(2,height/2*2);return Tuple.Create(width,height,bitrate,limit);}
 void ShowRecordingBar(System.Drawing.Rectangle rect){
  if(captureWindow!=null)captureWindow.Hide();captureRecordWindow=new Window{Title="Awl recording",Width=640,Height=110,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,Topmost=true,ShowInTaskbar=false,WindowStartupLocation=WindowStartupLocation.Manual};ExcludeCaptureWindow(captureRecordWindow);
  var row=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var time=Text("● 00:00",13);time.Margin=new Thickness(4,0,8,0);row.Children.Add(time);
  var pause=Button("","Pause",()=>{if(activeRecorder!=null)activeRecorder.Paused=!activeRecorder.Paused;});pause.Content=BuilderSvgIcon("pause",27,ink);pause.Width=52;pause.Height=52;pause.IsEnabled=false;row.Children.Add(pause);
  var micButton=Button("","Microphone capture is unavailable in this standalone recorder",()=>{});micButton.Content=BuilderSvgIcon("microphone",27,ink);micButton.IsEnabled=false;micButton.Opacity=.45;micButton.Width=52;micButton.Height=52;row.Children.Add(micButton);
  var shot=Button("","Take screenshot",()=>{string p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures),"Awl-shot-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".png");using(var image=CaptureBitmap(rect))image.Save(p,System.Drawing.Imaging.ImageFormat.Png);});shot.Content=BuilderSvgIcon("screenshot",27,ink);shot.Width=52;shot.Height=52;shot.IsEnabled=false;row.Children.Add(shot);
  Button preset=null;var presetText=Text(cfg.CapturePreset+"  0 MB  ⌄",14);presetText.FontWeight=FontWeights.SemiBold;preset=Action("",()=>{if(activeRecorder!=null)return;var entries=CapturePresets(rect).Select(value=>{string option=value;var values=PresetValues(option,rect);return Tuple.Create("record",option,values.Item1+" × "+values.Item2,(Action)(()=>{cfg.CapturePreset=option;SaveConfig();presetText.Text=option+"  0 MB  ⌄";}));}).ToList();CaptureDropdown(preset,entries);});var presetRow=new StackPanel{Orientation=Orientation.Horizontal};presetRow.Children.Add(BuilderSvgIcon("record",24,accentBrush));presetText.Margin=new Thickness(8,0,0,0);presetRow.Children.Add(presetText);preset.Content=presetRow;preset.MinWidth=245;preset.MinHeight=52;preset.Padding=new Thickness(15,10,15,10);row.Children.Add(preset);
  long sizeLimit=0;Action toggle=null;var recordButton=Button("","Start recording",()=>toggle());recordButton.Content=BuilderSvgIcon("play",29,Brushes.White);recordButton.Width=58;recordButton.Height=58;recordButton.FontSize=20;recordButton.Foreground=Brushes.White;recordButton.Background=accentBrush;row.Children.Add(recordButton);
  toggle=()=>{if(activeRecorder!=null){StopRecording();return;}string ffmpeg=CaptureRuntime();if(String.IsNullOrEmpty(ffmpeg)){MessageBox.Show("The embedded recording runtime could not be extracted.","Recording unavailable");return;}var settings=PresetValues(cfg.CapturePreset,rect);sizeLimit=settings.Item4;HideCapturedSurfaces();string output=Path.Combine(Path.GetTempPath(),"Awl-recording-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".mp4");activeRecorder=new ScreenRecorder(this,ffmpeg,rect,settings.Item1,settings.Item2,settings.Item3,output);captureStarted=DateTime.Now;activeRecorder.Start();pause.IsEnabled=true;shot.IsEnabled=true;recordButton.Content=BuilderSvgIcon("stop",29,Brushes.White);recordButton.ToolTip="Stop recording";recordButton.Background=new SolidColorBrush(Color.FromRgb(239,91,89));captureUiTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};captureUiTimer.Tick+=delegate{if(activeRecorder==null)return;long bytes=activeRecorder.Size;var elapsed=DateTime.Now-captureStarted;time.Text="● "+elapsed.ToString(@"mm\:ss");presetText.Text=cfg.CapturePreset+"  "+FileSize(bytes)+"  ⌄";preset.Background=sizeLimit>0&&bytes>sizeLimit?Brushes.Goldenrod:cardBrush;};captureUiTimer.Start();};
  SetCaptureContent(captureRecordWindow,PopupSurface(row,40),"Recording controls",640,110);captureRecordWindow.PreviewKeyDown+=delegate(object sender,KeyEventArgs e){if(e.Key==Key.Escape){CancelRecording();e.Handled=true;}};captureRecordWindow.Show();captureRecordWindow.Activate();PlaceCaptureWindow(captureRecordWindow);
 } string FileSize(long bytes){return bytes<1048576?(bytes/1024.0).ToString("0.0")+" KB":(bytes/1048576.0).ToString("0.0")+" MB";}
 public string CaptureSelfTest(){try{string runtime=CaptureRuntime();if(String.IsNullOrEmpty(runtime))return "FAILED: capture runtime missing";string output=Path.Combine(Path.GetTempPath(),"Awl-capture-test.mp4");var process=Process.Start(new ProcessStartInfo(runtime,"-y -f rawvideo -pixel_format bgra -video_size 64x64 -framerate 10 -i pipe:0 -an -c:v libopenh264 -b:v 180000 -pix_fmt yuv420p \""+output+"\""){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardError=true});process.ErrorDataReceived+=delegate{};process.BeginErrorReadLine();var frame=new byte[64*64*4];for(int i=0;i<20;i++){for(int p=0;p<frame.Length;p+=4){frame[p]=(byte)(i*9);frame[p+1]=(byte)(80+i*4);frame[p+2]=120;frame[p+3]=255;}process.StandardInput.BaseStream.Write(frame,0,frame.Length);}process.StandardInput.Close();process.WaitForExit();bool valid=process.ExitCode==0&&File.Exists(output)&&new FileInfo(output).Length>1000;try{File.Delete(output);}catch{}return valid?"Capture runtime encodes standalone MP4":"FAILED: capture runtime encoding";}catch(Exception error){return "FAILED: "+error.Message;}}
 public string RollingCaptureSelfTest(){try{string directory=Path.Combine(Path.GetTempPath(),"Awl-rolling-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var recorder=new RollingRecorder(this,CaptureRuntime(),new System.Drawing.Rectangle(0,0,64,64),directory,true);recorder.Start();Thread.Sleep(6200);recorder.Stop();var files=recorder.Files();string output=Path.Combine(directory,"export.mp4");bool valid=files.Length>0&&files.Sum(x=>new FileInfo(x).Length)>1000&&EncodeRollingCapture(recorder,"480p",output)&&File.Exists(output)&&new FileInfo(output).Length>1000;try{Directory.Delete(directory,true);}catch{}return valid?"Rolling capture retains and exports playable segments":"FAILED: rolling capture export";}catch(Exception error){return "FAILED: "+error.Message;}}
 async void CancelRecording(){var recorder=activeRecorder;activeRecorder=null;if(captureUiTimer!=null){captureUiTimer.Stop();captureUiTimer=null;}if(recorder!=null)await Task.Run(()=>recorder.Stop());RestoreCapturedSurfaces();if(captureRecordWindow!=null){captureRecordWindow.Close();captureRecordWindow=null;}if(recorder!=null)try{File.Delete(recorder.Output);}catch{}if(captureWindow!=null){captureWindow.Show();PlaceCaptureWindow(captureWindow);}}
 async void StopRecording(){if(activeRecorder==null)return;var recorder=activeRecorder;activeRecorder=null;if(captureUiTimer!=null){captureUiTimer.Stop();captureUiTimer=null;}await Task.Run(()=>recorder.Stop());RestoreCapturedSurfaces();if(captureRecordWindow!=null){captureRecordWindow.Close();captureRecordWindow=null;}ShowCaptureReview(recorder.Output,true,DateTime.Now-captureStarted);}
 void ShowCaptureReview(string path,bool video,TimeSpan duration){
  captureReviewPath=path;captureReviewKeep=false;captureReviewWindow=new Window{Title="Capture saved",Width=500,Height=video?410:340,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,Topmost=true,ShowInTaskbar=false,WindowStartupLocation=WindowStartupLocation.CenterScreen};ExcludeCaptureWindow(captureReviewWindow);var panel=new StackPanel();var preview=new Border{Height=video?210:185,Background=cardBrush,CornerRadius=new CornerRadius(14),ClipToBounds=true};DispatcherTimer playbackTimer=null;MediaElement mediaView=null;
  if(video){mediaView=new MediaElement{Source=new Uri(path),Stretch=Stretch.Uniform,LoadedBehavior=MediaState.Manual,UnloadedBehavior=MediaState.Close,ScrubbingEnabled=true};preview.Child=mediaView;}else preview.Child=new Image{Source=FileImage(path),Stretch=Stretch.Uniform};panel.Children.Add(preview);
  if(video){var controls=new DockPanel{Margin=new Thickness(0,9,0,2)};var play=CaptureAction("pause","Pause",()=>{});play.Width=104;DockPanel.SetDock(play,Dock.Left);controls.Children.Add(play);var timeLabel=Text("00:00 / 00:00",12,mutedBrush);timeLabel.Width=94;timeLabel.TextAlignment=TextAlignment.Right;timeLabel.VerticalAlignment=VerticalAlignment.Center;DockPanel.SetDock(timeLabel,Dock.Right);controls.Children.Add(timeLabel);var seek=new Slider{Minimum=0,Maximum=Math.Max(1,duration.TotalSeconds),Margin=new Thickness(10,0,10,0),VerticalAlignment=VerticalAlignment.Center,Cursor=Cursors.Hand};StyleSlider(seek);controls.Children.Add(seek);bool playing=true,seeking=false;Action updateTime=()=>{var total=TimeSpan.FromSeconds(Math.Max(0,seek.Maximum));var current=TimeSpan.FromSeconds(Math.Max(0,seek.Value));timeLabel.Text=current.ToString(@"mm\:ss")+" / "+total.ToString(@"mm\:ss");};mediaView.MediaOpened+=delegate{if(mediaView.NaturalDuration.HasTimeSpan)seek.Maximum=Math.Max(1,mediaView.NaturalDuration.TimeSpan.TotalSeconds);mediaView.Play();updateTime();};play.Click+=delegate{if(playing){mediaView.Pause();playing=false;play.Content=BuilderIconLabel("play","Play",play.Foreground,23);}else{mediaView.Play();playing=true;play.Content=BuilderIconLabel("pause","Pause",play.Foreground,23);}};seek.PreviewMouseLeftButtonDown+=delegate{seeking=true;};seek.PreviewMouseLeftButtonUp+=delegate{mediaView.Position=TimeSpan.FromSeconds(seek.Value);seeking=false;updateTime();};playbackTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(200)};playbackTimer.Tick+=delegate{if(!seeking&&mediaView.NaturalDuration.HasTimeSpan){seek.Value=mediaView.Position.TotalSeconds;updateTime();}};playbackTimer.Start();panel.Children.Add(controls);}
  var title=Text(video?"Clip saved":"Screenshot saved",17);title.FontWeight=FontWeights.SemiBold;title.Margin=new Thickness(0,9,0,2);panel.Children.Add(title);panel.Children.Add(Text((File.Exists(path)?FileSize(new FileInfo(path).Length):"")+(video?" · "+cfg.CapturePreset+" · MP4":" · PNG"),12,mutedBrush));var primary=new WrapPanel{Margin=new Thickness(0,10,0,4)};primary.Children.Add(CaptureAction("copy","Copy",()=>CopyCapture(path,video)));if(video)primary.Children.Add(CaptureAction("gif","Export GIF",()=>ExportCaptureGif(path)));primary.Children.Add(CaptureAction("download","Downloads",()=>DownloadCapture(path)));primary.Children.Add(CaptureAction("trash","Dismiss",()=>captureReviewWindow.Close()));panel.Children.Add(primary);SetCaptureContent(captureReviewWindow,PopupSurface(panel,18),"Capture review",500,video?410:340);captureReviewWindow.Closed+=delegate{if(playbackTimer!=null)playbackTimer.Stop();if(mediaView!=null)mediaView.Close();string discard=captureReviewPath;bool keep=captureReviewKeep;captureReviewWindow=null;captureReviewPath="";captureReviewKeep=false;if(!keep&&!String.IsNullOrEmpty(discard))Dispatcher.BeginInvoke(new Action(()=>{try{File.Delete(discard);}catch{}}));if(captureWindow!=null){captureWindow.Show();PlaceCaptureWindow(captureWindow);}};captureReviewWindow.Show();
 } void CopyCapture(string path,bool video){try{if(video)captureReviewKeep=true;if(!video){var image=FileImage(path);if(image!=null)Clipboard.SetImage((BitmapSource)image);}else{var files=new System.Collections.Specialized.StringCollection();files.Add(path);Clipboard.SetFileDropList(files);}}catch(Exception error){Log("Capture copy: "+error.Message);}}
 void DownloadCapture(string path){try{string directory=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads");Directory.CreateDirectory(directory);string destination=Path.Combine(directory,Path.GetFileName(path));File.Copy(path,destination,true);Process.Start(new ProcessStartInfo("explorer.exe","/select,\""+destination+"\""){UseShellExecute=true});}catch(Exception error){MessageBox.Show(error.Message,"Save failed");}}
 async void ExportCaptureGif(string path){string ffmpeg=CaptureRuntime();string destination=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures),Path.GetFileNameWithoutExtension(path)+".gif");await Task.Run(()=>{var process=Process.Start(new ProcessStartInfo(ffmpeg,"-y -i \""+path+"\" -vf \"fps=10,scale=min(960\\,iw):-2:flags=lanczos\" \""+destination+"\""){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true});process.StandardError.ReadToEnd();process.WaitForExit();});if(File.Exists(destination))Process.Start(new ProcessStartInfo("explorer.exe","/select,\""+destination+"\""){UseShellExecute=true});}

 sealed class RollingRecorder{
  readonly Shell owner;readonly string ffmpeg,directory;readonly System.Drawing.Rectangle area;readonly int width,height;readonly Thread thread;readonly bool testPattern;volatile bool running;Process process;
  public RollingRecorder(Shell owner,string ffmpeg,System.Drawing.Rectangle area,string directory,bool testPattern=false){this.owner=owner;this.ffmpeg=ffmpeg;this.area=area;this.directory=directory;this.testPattern=testPattern;double scale=Math.Min(1,720.0/Math.Max(1,area.Height));width=Math.Max(2,((int)Math.Round(area.Width*scale))/2*2);height=Math.Max(2,((int)Math.Round(area.Height*scale))/2*2);thread=new Thread(Run){IsBackground=true,Name="Awl rolling capture"};}
  public void Start(){running=true;thread.Start();}
  public string[] Files(){try{return Directory.GetFiles(directory,"segment-*.mp4").Where(x=>new FileInfo(x).Length>1000).ToArray();}catch{return new string[0];}}
  void Run(){try{string pattern=Path.Combine(directory,"segment-%02d.mp4");string args="-y -f rawvideo -pixel_format bgra -video_size "+width+"x"+height+" -framerate 10 -i pipe:0 -an -c:v libopenh264 -b:v 2500000 -maxrate 2500000 -bufsize 5000000 -g 10 -pix_fmt yuv420p -f segment -segment_time 5 -segment_wrap 7 -reset_timestamps 1 \""+pattern+"\"";var errors=new System.Text.StringBuilder();process=Process.Start(new ProcessStartInfo(ffmpeg,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardError=true});process.ErrorDataReceived+=delegate(object sender,DataReceivedEventArgs e){if(e.Data!=null)errors.AppendLine(e.Data);};process.BeginErrorReadLine();var frame=TimeSpan.FromMilliseconds(100);while(running){var began=DateTime.UtcNow;using(var bitmap=testPattern?new System.Drawing.Bitmap(width,height,System.Drawing.Imaging.PixelFormat.Format32bppArgb):owner.CaptureBitmap(area,true,width,height)){var data=bitmap.LockBits(new System.Drawing.Rectangle(0,0,width,height),System.Drawing.Imaging.ImageLockMode.ReadOnly,System.Drawing.Imaging.PixelFormat.Format32bppArgb);try{int bytes=Math.Abs(data.Stride)*height;var buffer=new byte[bytes];Marshal.Copy(data.Scan0,buffer,0,bytes);process.StandardInput.BaseStream.Write(buffer,0,buffer.Length);}finally{bitmap.UnlockBits(data);}}var left=frame-(DateTime.UtcNow-began);if(left.TotalMilliseconds>1)Thread.Sleep(left);}try{process.StandardInput.Close();}catch{}if(!process.WaitForExit(8000))process.Kill();if(process.ExitCode!=0)Log("Rolling ffmpeg: "+errors.ToString());}catch(Exception error){Log("Rolling recorder: "+error.Message+(process!=null?" · ffmpeg exited="+process.HasExited:""));try{if(process!=null&&!process.HasExited)process.Kill();}catch{}}}
  public void Stop(){running=false;if(thread.IsAlive)thread.Join(10000);}
 }

 sealed class ScreenRecorder{
  readonly Shell owner;readonly string ffmpeg;readonly System.Drawing.Rectangle area;readonly int width,height,bitrate;readonly Thread thread;volatile bool running;long framesWritten;public volatile bool Paused;Process process;public string Output{get;private set;}public long Size{get{long actual=0;try{actual=File.Exists(Output)?new FileInfo(Output).Length:0;}catch{}long estimated=(long)(Interlocked.Read(ref framesWritten)*(long)bitrate/8/20*.72);return actual>1024?actual:estimated;}}
  public ScreenRecorder(Shell owner,string ffmpeg,System.Drawing.Rectangle area,int width,int height,int bitrate,string output){this.owner=owner;this.ffmpeg=ffmpeg;this.area=area;this.width=width;this.height=height;this.bitrate=bitrate;Output=output;thread=new Thread(Run){IsBackground=true,Name="Awl screen recorder"};}
  public void Start(){running=true;thread.Start();}
  void Run(){try{string args="-y -f rawvideo -pixel_format bgra -video_size "+width+"x"+height+" -framerate 20 -i pipe:0 -an -c:v libopenh264 -b:v "+bitrate+" -maxrate "+bitrate+" -bufsize "+(bitrate*2)+" -pix_fmt yuv420p -g 20 -flush_packets 1 -movflags +frag_keyframe+empty_moov+default_base_moof \""+Output+"\"";process=Process.Start(new ProcessStartInfo(ffmpeg,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardError=true});process.ErrorDataReceived+=delegate{};process.BeginErrorReadLine();var frame=TimeSpan.FromMilliseconds(50);while(running){var began=DateTime.UtcNow;if(!Paused)using(var bitmap=owner.CaptureBitmap(area,true,width,height)){var data=bitmap.LockBits(new System.Drawing.Rectangle(0,0,width,height),System.Drawing.Imaging.ImageLockMode.ReadOnly,System.Drawing.Imaging.PixelFormat.Format32bppArgb);try{int bytes=Math.Abs(data.Stride)*height;var buffer=new byte[bytes];Marshal.Copy(data.Scan0,buffer,0,bytes);process.StandardInput.BaseStream.Write(buffer,0,buffer.Length);Interlocked.Increment(ref framesWritten);}finally{bitmap.UnlockBits(data);}}var left=frame-(DateTime.UtcNow-began);if(left.TotalMilliseconds>1)Thread.Sleep(left);}try{process.StandardInput.Close();}catch{}if(!process.WaitForExit(8000))process.Kill();}catch(Exception error){Log("Recorder: "+error.Message);try{if(process!=null&&!process.HasExited)process.Kill();}catch{}}}
  public void Stop(){running=false;if(thread.IsAlive)thread.Join(10000);}
 }
} }
