using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Management;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Windows.UI.Notifications;
using Windows.UI.Notifications.Management;

namespace Awl { partial class Shell {
 bool topReserved;int topReservedHeight;uint topAppBarCallback=Native.RegisterWindowMessage("Awl.TopBar.AppBar");
 Window altTabWindow;List<Tuple<IntPtr,string,string>> altTabItems=new List<Tuple<IntPtr,string,string>>();Dictionary<IntPtr,ImageSource> altTabPreviews=new Dictionary<IntPtr,ImageSource>();int altTabIndex;volatile bool altTabShowing;

 void ApplyToolTipTheme(){
  var style=new Style(typeof(ToolTip));style.Setters.Add(new Setter(Control.ForegroundProperty,ink));style.Setters.Add(new Setter(Control.BackgroundProperty,panelBrush));style.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(12,8,12,8)));style.Setters.Add(new Setter(Control.FontSizeProperty,12.0));style.Setters.Add(new Setter(Control.FontFamilyProperty,new FontFamily("Segoe UI")));
  var template=new ControlTemplate(typeof(ToolTip));var border=new FrameworkElementFactory(typeof(Border));border.SetValue(Border.BackgroundProperty,new TemplateBindingExtension(Control.BackgroundProperty));border.SetValue(Border.BorderBrushProperty,accentBrush);border.SetValue(Border.BorderThicknessProperty,new Thickness(1));border.SetValue(Border.CornerRadiusProperty,new CornerRadius(11));border.SetValue(Border.PaddingProperty,new TemplateBindingExtension(Control.PaddingProperty));border.SetValue(Border.EffectProperty,new System.Windows.Media.Effects.DropShadowEffect{Color=Colors.Black,BlurRadius=18,ShadowDepth=4,Opacity=.36});var content=new FrameworkElementFactory(typeof(ContentPresenter));content.SetValue(ContentPresenter.ContentProperty,new TemplateBindingExtension(ContentControl.ContentProperty));content.SetValue(System.Windows.Documents.TextElement.ForegroundProperty,new TemplateBindingExtension(Control.ForegroundProperty));border.AppendChild(content);template.VisualTree=border;style.Setters.Add(new Setter(Control.TemplateProperty,template));Resources[typeof(ToolTip)]=style;
 }

 void UpdateTopWorkspace(bool reserve,bool fullscreen,int physicalHeight){
  top.Background=fullscreen?Brushes.Black:Brushes.Transparent;top.Opacity=fullscreen?1:Math.Max(.3,Math.Min(1,cfg.TopOpacity));
  if(reserve){if(!topReserved){var add=new Native.APPBAR{Size=Marshal.SizeOf(typeof(Native.APPBAR)),Hwnd=new System.Windows.Interop.WindowInteropHelper(top).Handle,Callback=topAppBarCallback,Edge=1};topReserved=Native.SHAppBarMessage(0,ref add)!=UIntPtr.Zero;}if(topReserved&&topReservedHeight!=physicalHeight){var bar=new Native.APPBAR{Size=Marshal.SizeOf(typeof(Native.APPBAR)),Hwnd=new System.Windows.Interop.WindowInteropHelper(top).Handle,Callback=topAppBarCallback,Edge=1,Rect=new Native.RECT{Left=0,Top=0,Right=System.Windows.Forms.Screen.PrimaryScreen.Bounds.Width,Bottom=physicalHeight}};Native.SHAppBarMessage(2,ref bar);bar.Rect.Bottom=bar.Rect.Top+physicalHeight;Native.SHAppBarMessage(3,ref bar);topReservedHeight=physicalHeight;}}
  else ReleaseTopWorkspace();
 }
 void ReleaseTopWorkspace(){if(!topReserved)return;var bar=new Native.APPBAR{Size=Marshal.SizeOf(typeof(Native.APPBAR)),Hwnd=top==null?IntPtr.Zero:new System.Windows.Interop.WindowInteropHelper(top).Handle};Native.SHAppBarMessage(1,ref bar);topReserved=false;topReservedHeight=0;}

 FrameworkElement AudioToolbarPanel(string kind){
  int flow=kind=="Volume"?0:1;float level;bool muted;var row=new Grid{Width=360,Height=54};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(62)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(66)});var icon=Action("",()=>{});icon.Content=NavIcon(kind,accentBrush,27,2.2);icon.Padding=new Thickness(0);icon.Margin=new Thickness(0,0,16,0);Grid.SetColumn(icon,0);row.Children.Add(icon);if(Audio.Read(flow,out level,out muted)){var slider=new Slider{Minimum=0,Maximum=100,Value=level*100,VerticalAlignment=VerticalAlignment.Center,Foreground=accentBrush};StyleSlider(slider);var value=Text(Math.Round(level*100)+"%",18);value.FontWeight=FontWeights.SemiBold;value.TextAlignment=TextAlignment.Right;slider.ValueChanged+=delegate{value.Text=Math.Round(slider.Value)+"%";Audio.Write(flow,(float)slider.Value/100,null);};icon.Opacity=muted?.45:1;icon.Click+=delegate{float current;bool state;if(Audio.Read(flow,out current,out state)&&Audio.Write(flow,null,!state))icon.Opacity=!state?.45:1;};Grid.SetColumn(slider,1);Grid.SetColumn(value,2);row.Children.Add(slider);row.Children.Add(value);}else{var unavailable=Text("Audio device unavailable",13,mutedBrush);Grid.SetColumn(unavailable,1);Grid.SetColumnSpan(unavailable,2);row.Children.Add(unavailable);}return row;
 }
 FrameworkElement BatteryToolbarPanel(){var power=System.Windows.Forms.SystemInformation.PowerStatus;double percent=Math.Max(0,Math.Min(100,power.BatteryLifePercent*100));var row=new Grid{Width=360,Height=54};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(62)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(66)});var icon=Action("",()=>Launch("ms-settings:batterysaver"));icon.Content=NavIcon("Battery",accentBrush,27,2.2);icon.Padding=new Thickness(0);icon.Margin=new Thickness(0,0,16,0);row.Children.Add(icon);var bar=new ProgressBar{Minimum=0,Maximum=100,Value=percent,Height=8,Foreground=accentBrush,Background=cardBrush,VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(bar,1);row.Children.Add(bar);var value=Text(Math.Round(percent)+"%",18);value.FontWeight=FontWeights.SemiBold;value.TextAlignment=TextAlignment.Right;Grid.SetColumn(value,2);row.Children.Add(value);return row;}
 int ReadBrightness(){try{using(var query=new ManagementObjectSearcher("root\\WMI","SELECT CurrentBrightness FROM WmiMonitorBrightness"))foreach(ManagementObject value in query.Get())return Convert.ToInt32(value["CurrentBrightness"]);}catch(Exception error){Log("Brightness: "+error.Message);}return -1;}
 void WriteBrightness(int value){try{using(var query=new ManagementObjectSearcher("root\\WMI","SELECT * FROM WmiMonitorBrightnessMethods"))foreach(ManagementObject monitor in query.Get()){monitor.InvokeMethod("WmiSetBrightness",new object[]{(uint)1,(byte)Math.Max(0,Math.Min(100,value))});break;}}catch(Exception error){Log("Brightness: "+error.Message);}}
 FrameworkElement BrightnessToolbarPanel(){int level=ReadBrightness();var row=new Grid{Width=360,Height=54};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(54)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(58)});var icon=NavIcon("Brightness",accentBrush,26,2);icon.HorizontalAlignment=HorizontalAlignment.Center;row.Children.Add(icon);if(level<0){var unavailable=Text("Brightness is controlled by this display",12,mutedBrush);Grid.SetColumn(unavailable,1);Grid.SetColumnSpan(unavailable,2);row.Children.Add(unavailable);return row;}var slider=new Slider{Minimum=0,Maximum=100,Value=level,VerticalAlignment=VerticalAlignment.Center,Foreground=accentBrush};StyleSlider(slider);var value=Text(level+"%",16);value.TextAlignment=TextAlignment.Right;slider.AddHandler(Thumb.DragCompletedEvent,new DragCompletedEventHandler(delegate{WriteBrightness((int)slider.Value);}));slider.PreviewMouseLeftButtonUp+=delegate{WriteBrightness((int)slider.Value);};slider.ValueChanged+=delegate{value.Text=Math.Round(slider.Value)+"%";};Grid.SetColumn(slider,1);Grid.SetColumn(value,2);row.Children.Add(slider);row.Children.Add(value);return row;}
 FrameworkElement CompactWifiPanel(){var content=new StackPanel{Width=380};var header=new DockPanel();var title=Text("Wi-Fi",18);title.FontWeight=FontWeights.SemiBold;header.Children.Add(title);content.Children.Add(header);var note=Text("Loading networks…",12,mutedBrush);note.Margin=new Thickness(0,6,0,8);content.Children.Add(note);WifiPanel(content,note);return content;}
 FrameworkElement StandardToolbarPanel(string kind){if(kind=="Volume"||kind=="Microphone")return AudioToolbarPanel(kind);if(kind=="Battery")return BatteryToolbarPanel();if(kind=="Brightness")return BrightnessToolbarPanel();if(kind=="Wi-Fi")return CompactWifiPanel();var content=new StackPanel{Width=360};var title=Text(kind,18);title.FontWeight=FontWeights.SemiBold;content.Children.Add(title);var note=Text("",12,mutedBrush);note.Margin=new Thickness(0,10,0,8);content.Children.Add(note);if(kind=="Wi-Fi")WifiPanel(content,note);else if(kind=="Bluetooth"){note.Text=bluetooth.Text;content.Children.Add(Switch("Bluetooth",bluetooth.Text.Contains("on"),v=>{try{var ignored=SetBluetooth(v);}catch{}}));content.Children.Add(Action("Open Bluetooth settings",()=>Launch("ms-settings:bluetooth")));}return content;}
 async System.Threading.Tasks.Task SetBluetooth(bool enabled){try{var radios=await System.WindowsRuntimeSystemExtensions.AsTask<IReadOnlyList<global::Windows.Devices.Radios.Radio>>(global::Windows.Devices.Radios.Radio.GetRadiosAsync());var radio=radios.FirstOrDefault(x=>x.Kind==global::Windows.Devices.Radios.RadioKind.Bluetooth);if(radio!=null)await System.WindowsRuntimeSystemExtensions.AsTask<global::Windows.Devices.Radios.RadioAccessStatus>(radio.SetStateAsync(enabled?global::Windows.Devices.Radios.RadioState.On:global::Windows.Devices.Radios.RadioState.Off));}catch(Exception error){Log("Bluetooth: "+error.Message);}}

 Border PopupSurface(FrameworkElement child,double radius=18){var surface=new Border{Background=SurfaceBrush(baseColor,.96,cfg.StartMenuGlass??cfg.GlassEffect),BorderBrush=new SolidColorBrush(Mix(baseColor,Colors.White,.22)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(radius),Padding=new Thickness(14),Effect=new System.Windows.Media.Effects.DropShadowEffect{Color=Colors.Black,BlurRadius=28,ShadowDepth=8,Opacity=.42},Child=child};System.Windows.Documents.TextElement.SetFontFamily(surface,new FontFamily("Segoe UI"));System.Windows.Documents.TextElement.SetForeground(surface,ink);return surface;}

 void NotificationPanel(StackPanel host){
  var header=new DockPanel();var clear=Action("Clear all",()=>{try{UserNotificationListener.Current.ClearNotifications();}catch{}if(systemPopup!=null)systemPopup.IsOpen=false;});clear.Foreground=accentBrush;DockPanel.SetDock(clear,Dock.Right);header.Children.Add(clear);var title=Text("Notifications",22);title.FontWeight=FontWeights.SemiBold;header.Children.Add(title);host.Children.Add(header);var list=new StackPanel{Margin=new Thickness(0,12,0,0)};list.Children.Add(Text("Loading notifications…",12,mutedBrush));host.Children.Add(new ScrollViewer{Content=list,MaxHeight=400,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden});host.Children.Add(NotificationQuickSettings());var ignored=LoadNotifications(list);
 }
 async System.Threading.Tasks.Task LoadNotifications(StackPanel list){
  try{var listener=UserNotificationListener.Current;var access=await System.WindowsRuntimeSystemExtensions.AsTask<UserNotificationListenerAccessStatus>(listener.RequestAccessAsync());if(access!=UserNotificationListenerAccessStatus.Allowed)throw new InvalidOperationException("Notification access is unavailable.");var notices=await System.WindowsRuntimeSystemExtensions.AsTask<IReadOnlyList<UserNotification>>(listener.GetNotificationsAsync(NotificationKinds.Toast));list.Children.Clear();var values=notices.OrderByDescending(x=>x.CreationTime).ToList();foreach(var period in new[]{"Today","Earlier"}){var periodItems=values.Where(x=>(x.CreationTime.LocalDateTime.Date==DateTime.Today)==(period=="Today")).ToList();if(periodItems.Count==0)continue;var heading=Text(period,14,mutedBrush);heading.Margin=new Thickness(2,8,0,8);list.Children.Add(heading);foreach(var group in periodItems.GroupBy(NotificationAppName)){list.Children.Add(NotificationGroup(group.Key,group.ToList()));}}if(values.Count==0)list.Children.Add(Text("No notifications",13,mutedBrush));}
  catch(Exception error){list.Children.Clear();list.Children.Add(Text("Windows notification history is unavailable",13));var detail=Text(error.Message,11,mutedBrush);detail.Margin=new Thickness(0,7,0,0);list.Children.Add(detail);}
 }
 string NotificationAppName(UserNotification notice){try{return notice.AppInfo.DisplayInfo.DisplayName;}catch{return "Windows";}}
 string[] NotificationText(UserNotification notice){try{var binding=notice.Notification.Visual.GetBinding(KnownNotificationBindings.ToastGeneric);return binding==null?new string[0]:binding.GetTextElements().Select(x=>x.Text).Where(x=>!String.IsNullOrWhiteSpace(x)).ToArray();}catch{return new string[0];}}
 FrameworkElement NotificationGroup(string app,List<UserNotification> notices){var stack=new StackPanel();var top=new DockPanel();var appName=Text(app,16);appName.FontWeight=FontWeights.SemiBold;top.Children.Add(appName);stack.Children.Add(top);foreach(var notice in notices){var texts=NotificationText(notice);var row=new DockPanel{Margin=new Thickness(0,7,0,3)};var time=Text(RelativeTime(notice.CreationTime.LocalDateTime),11,mutedBrush);DockPanel.SetDock(time,Dock.Right);row.Children.Add(time);var message=Text(texts.Length==0?"Notification":String.Join("\n",texts.Take(3)),13);row.Children.Add(message);stack.Children.Add(row);string combined=app+" "+String.Join(" ",texts);if(combined.IndexOf("update",StringComparison.OrdinalIgnoreCase)>=0){var action=Action("Review update",()=>{if(systemPopup!=null)systemPopup.IsOpen=false;if(app.IndexOf("Awl",StringComparison.OrdinalIgnoreCase)>=0){activeTab="Config";if(launcher==null||!launcher.IsVisible)ToggleLauncher();else DrawLauncher();}else Launch("ms-settings:windowsupdate");});action.HorizontalAlignment=HorizontalAlignment.Left;stack.Children.Add(action);}}return new Border{Background=cardBrush,CornerRadius=new CornerRadius(17),Padding=new Thickness(16),Margin=new Thickness(0,0,0,10),Child=stack};}
 string RelativeTime(DateTime value){var age=DateTime.Now-value;if(age.TotalMinutes<1)return "now";if(age.TotalHours<1)return Math.Max(1,(int)age.TotalMinutes)+"m";if(age.TotalDays<1)return (int)age.TotalHours+"h";return value.ToString("d MMM");}
 FrameworkElement PopupIconLabel(string icon,string label){var content=new StackPanel{HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};var art=NavIcon(icon,accentBrush,22,2);art.HorizontalAlignment=HorizontalAlignment.Center;art.Margin=new Thickness(0,0,0,7);content.Children.Add(art);var text=Text(label,13);text.HorizontalAlignment=HorizontalAlignment.Center;content.Children.Add(text);return content;}
 FrameworkElement NotificationQuickSettings(){var row=new UniformGrid{Columns=3,Margin=new Thickness(0,16,0,0)};var focus=Action("",()=>Launch("ms-settings:quiethours"));focus.Content=PopupIconLabel("Focus","Focus");var wifiButton=Action("",()=>{if(systemPopup!=null)systemPopup.IsOpen=false;Dispatcher.BeginInvoke(new Action(()=>SystemPanel("Wi-Fi")));});wifiButton.Content=PopupIconLabel("Wi-Fi","Wi-Fi");var bluetoothButton=Action("",()=>{if(systemPopup!=null)systemPopup.IsOpen=false;Dispatcher.BeginInvoke(new Action(()=>SystemPanel("Bluetooth")));});bluetoothButton.Content=PopupIconLabel("Bluetooth","Bluetooth");foreach(var button in new[]{focus,wifiButton,bluetoothButton}){button.Height=72;row.Children.Add(button);}return row;}

 List<Tuple<IntPtr,string,string>> AltTabCandidates(){var values=new List<Tuple<IntPtr,string,string>>();Native.EnumWindows(delegate(IntPtr h,IntPtr unused){if(!Native.IsWindowVisible(h)||(Native.GetWindowLong(h,-20)&0x80)!=0)return true;int cloaked;Native.DwmGetWindowAttribute(h,14,out cloaked,4);if(cloaked!=0)return true;uint pid;Native.GetWindowThreadProcessId(h,out pid);if(pid==selfPid)return true;var text=new StringBuilder(512);Native.GetWindowText(h,text,512);if(text.Length==0||text.ToString()=="Program Manager")return true;string path="";try{using(var process=Process.GetProcessById((int)pid))path=process.MainModule.FileName;}catch{}values.Add(Tuple.Create(h,text.ToString(),path));return true;},IntPtr.Zero);return values;}
 ImageSource CaptureWindowPreview(IntPtr hwnd){Native.RECT rect;if(!Native.GetWindowRect(hwnd,out rect))return null;int width=Math.Max(1,Math.Min(3840,rect.Right-rect.Left)),height=Math.Max(1,Math.Min(2160,rect.Bottom-rect.Top));if(width<2||height<2)return null;try{using(var bitmap=new System.Drawing.Bitmap(width,height,System.Drawing.Imaging.PixelFormat.Format32bppArgb))using(var graphics=System.Drawing.Graphics.FromImage(bitmap)){IntPtr hdc=graphics.GetHdc();bool drawn=false;try{drawn=Native.PrintWindow(hwnd,hdc,2);}finally{graphics.ReleaseHdc(hdc);}if(!drawn)return null;IntPtr handle=bitmap.GetHbitmap();try{var image=Imaging.CreateBitmapSourceFromHBitmap(handle,IntPtr.Zero,Int32Rect.Empty,BitmapSizeOptions.FromEmptyOptions());image.Freeze();return image;}finally{DeleteObject(handle);}}}catch(Exception error){Log("Window preview: "+error.Message);return null;}}
 void ShowAltTab(bool reverse){if(altTabWindow==null||!altTabWindow.IsVisible){altTabItems=AltTabCandidates();altTabPreviews.Clear();if(altTabItems.Count==0)return;altTabIndex=altTabItems.Count==1?0:reverse?altTabItems.Count-1:1;if(altTabWindow!=null)altTabWindow.Close();altTabWindow=new Window{Title="Awl switcher",WindowStyle=WindowStyle.None,AllowsTransparency=true,Background=Brushes.Transparent,ResizeMode=ResizeMode.NoResize,ShowInTaskbar=false,ShowActivated=false,Topmost=true,Width=Math.Min(1100,40+Math.Min(5,altTabItems.Count)*216),Height=230,WindowStartupLocation=WindowStartupLocation.CenterScreen};altTabWindow.Closed+=delegate{altTabShowing=false;altTabWindow=null;};altTabShowing=true;DrawAltTab();altTabWindow.Show();}else{altTabIndex=(altTabIndex+(reverse?-1:1)+altTabItems.Count)%altTabItems.Count;DrawAltTab();}}
 void DrawAltTab(){if(altTabWindow==null)return;var row=new StackPanel{Orientation=Orientation.Horizontal};int pageStart=(altTabIndex/5)*5;for(int i=0;i<5;i++){int index=pageStart+i;if(index>=altTabItems.Count)break;var item=altTabItems[index];var tile=new StackPanel{Width=198,Margin=new Thickness(5),Cursor=System.Windows.Input.Cursors.Hand};var preview=new Border{Height=140,CornerRadius=new CornerRadius(18),Background=cardBrush,BorderBrush=index==altTabIndex?accentBrush:new SolidColorBrush(Color.FromArgb(50,255,255,255)),BorderThickness=new Thickness(index==altTabIndex?3:1),ClipToBounds=true};var frame=new Grid();ImageSource capture;if(!altTabPreviews.TryGetValue(item.Item1,out capture)){capture=CaptureWindowPreview(item.Item1);altTabPreviews[item.Item1]=capture;}if(capture!=null)frame.Children.Add(new Image{Source=capture,Stretch=Stretch.Uniform,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center});var icon=AppIcon(item.Item3);if(icon!=null){var badge=new Border{Background=new SolidColorBrush(Color.FromArgb(205,20,28,27)),CornerRadius=new CornerRadius(8),Padding=new Thickness(6),Margin=new Thickness(8),HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Bottom,Child=new Image{Source=Tone(icon),Width=28,Height=28}};frame.Children.Add(badge);}preview.Child=frame;tile.Children.Add(preview);var name=Text(item.Item2,13);name.FontWeight=FontWeights.SemiBold;name.TextAlignment=TextAlignment.Center;name.TextTrimming=TextTrimming.CharacterEllipsis;name.TextWrapping=TextWrapping.NoWrap;name.Margin=new Thickness(4,8,4,0);tile.Children.Add(name);int chosen=index;tile.MouseLeftButtonUp+=delegate{altTabIndex=chosen;FinishAltTab(true);};row.Children.Add(tile);}altTabWindow.Content=PopupSurface(row,24);}
 void FinishAltTab(bool activate){var window=altTabWindow;if(window==null)return;var selected=altTabItems.Count>altTabIndex&&altTabIndex>=0?altTabItems[altTabIndex]:null;altTabShowing=false;altTabWindow=null;try{window.Close();}catch{}if(activate&&selected!=null)Dispatcher.BeginInvoke(DispatcherPriority.Input,new Action(delegate{if(Native.IsIconic(selected.Item1))Native.ShowWindowAsync(selected.Item1,9);Native.ShowWindowAsync(selected.Item1,5);Native.SetForegroundWindow(selected.Item1);}));}
}}
