using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;
namespace Awl { partial class Shell {
 FrameworkElement NavIcon(string name,Brush color,double size=20,double stroke=1.6){string path;
 switch(name){case "Config":path="M3,3 H9 V9 H3 Z M15,3 H21 V9 H15 Z M3,15 H9 V21 H3 Z M18,14 V22 M14,18 H22";break;
 case "Widgets":path="M3,3 H10 V12 H3 Z M14,3 H21 V8 H14 Z M3,16 H10 V21 H3 Z M14,12 H21 V21 H14 Z";break;
 case "Apps":path="M3,3 H9 V9 H3 Z M15,3 H21 V9 H15 Z M3,15 H9 V21 H3 Z M15,15 H21 V21 H15 Z";break;
 case "General":path="M3,5 H21 M3,12 H21 M3,19 H21 M7,3 V7 M17,10 V14 M10,17 V21";break;
 case "System":path="M2,12 H7 L10,5 L14,19 L17,12 H22";break;
 case "Bars":path="M4,4 H20 Q22,4 22,6 Q22,8 20,8 H4 Q2,8 2,6 Q2,4 4,4 Z M4,16 H20 Q22,16 22,18 Q22,20 20,20 H4 Q2,20 2,18 Q2,16 4,16 Z";break;
 case "Interface":path="M12,2 L15,8.5 L22,9.5 L17,14.5 L18,22 L12,18.5 L6,22 L7,14.5 L2,9.5 L9,8.5 Z";break;
 case "About":path="M12,2 A10,10 0 1 1 11.99,2 M12,10 V18 M12,6 V7";break;
 case "Power":path="M12,2 V12 M6,5 A9,9 0 1 0 18,5";break;
 case "Settings":path="M14.7,6.3 A4,4 0 0 0 9.7,1.3 L11.8,3.4 L9.4,5.8 L7.3,3.7 A4,4 0 0 0 12.3,8.7 L5,17 L7,19 L14.7,11.3 A4,4 0 0 0 19.7,6.3 L17.6,8.4 L15.2,6 L17.3,3.9";break;
 case "Position":path="M12,2 V22 M7,7 L12,2 L17,7 M7,17 L12,22 L17,17";break;
 case "Shading":path="M12,2 L22,12 L12,22 L2,12 Z M12,6 V18 M8,10 V14";break;
 case "Colors":path="M12,2 A10,10 0 1 0 22,12 Q22,9 18,10 Q14,12 14,8 Q16,3 12,2 M6,8 H7 M5,13 H6 M9,18 H10";break;
 case "Volume":path="M4,10 H8 L14,5 V19 L8,14 H4 Z M17,9 Q20,12 17,15 M19,6 Q24,12 19,18";break;
 case "Microphone":path="M9,5 A3,3 0 0 1 15,5 V12 A3,3 0 0 1 9,12 Z M5,11 A7,7 0 0 0 19,11 M12,18 V22 M8,22 H16";break;
 case "Battery":path="M3,7 H19 V17 H3 Z M19,10 H22 V14 H19 M6,10 H13 V14 H6 Z";break;
 case "Wi-Fi":case "Network":path="M3,9 Q12,1 21,9 M6,13 Q12,7 18,13 M9,17 Q12,14 15,17 M12,21 L12.01,21";break;
 case "Bluetooth":path="M8,6 L17,17 L12,22 V2 L17,7 L8,18";break;
 case "Notifications":path="M5,17 H19 L17,14 V10 A5,5 0 0 0 7,10 V14 Z M10,20 H14";break;
 case "Focus":path="M18,17 A8,8 0 1 1 10,4 A7,7 0 0 0 18,17";break;
 case "Brightness":path="M12,4 V1 M12,23 V20 M4,12 H1 M23,12 H20 M6.3,6.3 L4.2,4.2 M19.8,19.8 L17.7,17.7 M17.7,6.3 L19.8,4.2 M4.2,19.8 L6.3,17.7 M12,7 A5,5 0 1 1 11.99,7";break;
 case "Capture":case "Screenshot":path="M4,7 H8 L10,4 H15 L17,7 H20 Q22,7 22,9 V19 Q22,21 20,21 H4 Q2,21 2,19 V9 Q2,7 4,7 Z M12,10 A4,4 0 1 1 11.99,10";break;
 case "Region":path="M4,9 V4 H9 M15,4 H20 V9 M20,15 V20 H15 M9,20 H4 V15 M7,12 H17 M12,7 V17";break;
 case "Window":path="M3,5 H21 V19 H3 Z M3,8 H21 M6,6.5 L6.1,6.5 M9,6.5 L9.1,6.5";break;
 case "Full screen":path="M3,9 V3 H9 M15,3 H21 V9 M21,15 V21 H15 M9,21 H3 V15";break;
 case "History":path="M4,8 H1 V3 M2,7 A10,10 0 1 1 4,18 M12,6 V12 L16,15";break;
 default:path="M9,2 H15 L16,5 L19,6 L22,9 V15 L19,16 L18,19 L15,22 H9 L8,19 L5,18 L2,15 V9 L5,8 L6,5 Z M12,8 A4,4 0 1 1 11.99,8";break;}
 var shape=new System.Windows.Shapes.Path{Data=Geometry.Parse(path),Stroke=color,StrokeThickness=stroke,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round,StrokeLineJoin=PenLineJoin.Round,Stretch=Stretch.Uniform,Width=size,Height=size};return shape;
 }
 FrameworkElement NavLabel(string icon,string label,Brush color,double size){var row=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var art=NavIcon(icon,color,size,size>20?2.8:1.6);art.Margin=new Thickness(0,0,9,0);row.Children.Add(art);row.Children.Add(Text(label,size<20?11:14,color));return row;}
 void EmphasizeQuick(UIElement element){var stack=element as StackPanel;if(stack==null||stack.Children.Count==0)return;var title=stack.Children[0] as TextBlock;if(title==null)return;string label=title.Text;int split=label.IndexOf("  ");if(split>=0)label=label.Substring(split+2);string icon=label.Contains("position")?"Position":label.Contains("style")?"Bars":label.Contains("shading")?"Shading":"Colors";stack.Children.RemoveAt(0);stack.Children.Insert(0,NavLabel(icon,label,ink,26));}
 [DllImport("kernel32.dll")]static extern bool GetSystemTimes(out long idle,out long kernel,out long user);
 [StructLayout(LayoutKind.Sequential)]class MemoryState{public uint Length=(uint)Marshal.SizeOf(typeof(MemoryState)),Load;public ulong Total,Available,PageTotal,PageAvailable,VirtualTotal,VirtualAvailable,Extended;}
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GlobalMemoryStatusEx([In,Out]MemoryState state);
 [StructLayout(LayoutKind.Sequential)]struct IoState{public ulong ReadCount,WriteCount,OtherCount,ReadBytes,WriteBytes,OtherBytes;}
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetProcessIoCounters(IntPtr handle,out IoState state);
 class AppSample{public int Id;public long Start;public string Name,Path;public double Cpu=Double.NaN,Memory=Double.NaN,Io=Double.NaN;public long CpuTicks;public ulong Bytes;public bool IoValid;public IntPtr Window;}
 class SystemSample{public double Cpu=Double.NaN,MemoryTotal,MemoryUsed,DiskTotal,DiskUsed;public string Drive="";public AppSample Self;public List<AppSample> Apps=new List<AppSample>(),BackgroundApps=new List<AppSample>();}
 SystemSample systemSample=new SystemSample();Dictionary<int,AppSample> previousApps=new Dictionary<int,AppSample>();DateTime sampleTime=DateTime.MinValue;long previousIdle,previousTotal;bool systemBusy;DispatcherTimer systemTimer;StackPanel systemBody;ScrollViewer backgroundAppsScroll;double backgroundAppsOffset;string systemSort="CPU";List<double> cpuHistory=new List<double>(),memoryHistory=new List<double>(),diskHistory=new List<double>();TextBlock cpuTop,memoryTop,diskTop;
 void StartSystemMonitor(){if(systemTimer!=null)return;systemTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};systemTimer.Tick+=async delegate{await UpdateSystem();};systemTimer.Start();}
 async Task UpdateSystem(){bool visible=launcher!=null&&launcher.IsVisible&&activeTab=="System";if(systemBusy||!visible&&!cfg.SystemCpuTop&&!cfg.SystemMemoryTop&&!cfg.SystemDiskTop)return;systemBusy=true;try{var result=await Task.Run(()=>ReadSystem(visible));systemSample=result;Push(cpuHistory,result.Cpu);Push(memoryHistory,result.MemoryTotal>0?result.MemoryUsed/result.MemoryTotal*100:Double.NaN);Push(diskHistory,result.DiskTotal>0?result.DiskUsed/result.DiskTotal*100:Double.NaN);UpdateSystemLabels();if(launcher!=null&&launcher.IsVisible&&activeTab=="System"&&systemBody!=null)DrawSystemBody();}catch(Exception e){Log("System: "+e.Message);}finally{systemBusy=false;}}
 static void Push(List<double> series,double value){if(Double.IsNaN(value))return;series.Add(value);if(series.Count>40)series.RemoveAt(0);}
 SystemSample ReadSystem(bool appsNeeded){var result=new SystemSample();long idle,kernel,user;if(GetSystemTimes(out idle,out kernel,out user)){long total=kernel+user,delta=total-previousTotal;if(previousTotal>0&&delta>0)result.Cpu=Math.Max(0,Math.Min(100,100.0*(delta-(idle-previousIdle))/delta));previousIdle=idle;previousTotal=total;}var memory=new MemoryState();if(GlobalMemoryStatusEx(memory)){result.MemoryTotal=memory.Total;result.MemoryUsed=memory.Total-memory.Available;}try{var drive=new DriveInfo(System.IO.Path.GetPathRoot(Environment.SystemDirectory));result.Drive=drive.Name;result.DiskTotal=drive.TotalSize;result.DiskUsed=drive.TotalSize-drive.TotalFreeSpace;}catch{}
 if(appsNeeded){var now=DateTime.UtcNow;double elapsed=(now-sampleTime).TotalSeconds;var next=new Dictionary<int,AppSample>();int session;try{session=Process.GetCurrentProcess().SessionId;}catch{session=-1;}string systemFolder=Environment.SystemDirectory.TrimEnd('\\')+"\\";foreach(var process in Process.GetProcesses()){using(process){try{bool self=process.Id==selfPid;var item=new AppSample{Id=process.Id,Start=process.StartTime.ToUniversalTime().Ticks,Name=process.ProcessName,Window=process.MainWindowHandle,Memory=process.WorkingSet64};try{item.Path=process.MainModule.FileName;}catch{}try{item.CpuTicks=process.TotalProcessorTime.Ticks;AppSample prior=null;if(previousApps.TryGetValue(item.Id,out prior)&&prior.Start==item.Start&&elapsed>0)item.Cpu=Math.Max(0,Math.Min(100,(item.CpuTicks-prior.CpuTicks)/10000000.0/elapsed/Environment.ProcessorCount*100));IoState io;if(GetProcessIoCounters(process.Handle,out io)){item.IoValid=true;item.Bytes=io.ReadBytes+io.WriteBytes;if(prior!=null&&prior.Start==item.Start&&prior.IoValid&&elapsed>0&&item.Bytes>=prior.Bytes)item.Io=(item.Bytes-prior.Bytes)/elapsed;}}catch{}next[item.Id]=item;if(self)result.Self=item;else if(item.Window!=IntPtr.Zero)result.Apps.Add(item);else{bool sameSession=false;try{sameSession=process.SessionId==session;}catch{}bool systemProcess=String.IsNullOrEmpty(item.Path)||item.Path.StartsWith(systemFolder,StringComparison.OrdinalIgnoreCase);bool anotherAwl=String.Equals(item.Name,"Awl",StringComparison.OrdinalIgnoreCase);if(sameSession&&!systemProcess&&!anotherAwl)result.BackgroundApps.Add(item);}}catch{}}}previousApps=next;sampleTime=now;}return result;}
 string Percent(double value){return Double.IsNaN(value)?"—":value.ToString("0")+"%";}string Gigabytes(double value){return (value/1073741824.0).ToString("0.0")+" GB";}
 void SystemTopModules(){if(moduleViews==null||cpuTop!=null)return;cpuTop=Text("CPU —",12);memoryTop=Text("RAM —",12);diskTop=Text("Disk —",12);moduleViews["CPU"]=cpuTop;moduleViews["Memory"]=memoryTop;moduleViews["Disk space"]=diskTop;foreach(string name in new[]{"CPU","Memory","Disk space"})if(!cfg.ModuleOrder.Contains(name))cfg.ModuleOrder.Add(name);UpdateSystemLabels();}
 void UpdateSystemLabels(){if(cpuTop==null)return;cpuTop.Text="CPU "+Percent(systemSample.Cpu)+"  ";memoryTop.Text="RAM "+Gigabytes(systemSample.MemoryUsed)+"  ";diskTop.Text="Disk "+(systemSample.DiskTotal>0?Percent(systemSample.DiskUsed/systemSample.DiskTotal*100):"—")+"  ";cpuTop.Foreground=memoryTop.Foreground=diskTop.Foreground=ink;cpuTop.Visibility=cfg.SystemCpuTop&&!cfg.HiddenModules.Contains("CPU")?Visibility.Visible:Visibility.Collapsed;memoryTop.Visibility=cfg.SystemMemoryTop&&!cfg.HiddenModules.Contains("Memory")?Visibility.Visible:Visibility.Collapsed;diskTop.Visibility=cfg.SystemDiskTop&&!cfg.HiddenModules.Contains("Disk space")?Visibility.Visible:Visibility.Collapsed;}
 void SystemPage(){systemSort=cfg.SystemSort;Header("System");StartSystemMonitor();systemBody=new StackPanel();page.Children.Add(systemBody);DrawSystemBody();var ignored=UpdateSystem();}
 FrameworkElement Spark(List<double> values){var canvas=new Canvas{Height=34,Margin=new Thickness(0,8,0,0)};Action draw=()=>{canvas.Children.Clear();if(values.Count<2)return;var line=new Polyline{Stroke=accentBrush,StrokeThickness=1.5};for(int i=0;i<values.Count;i++)line.Points.Add(new Point(i*Math.Max(1,canvas.ActualWidth)/(values.Count-1),32-Math.Max(0,Math.Min(100,values[i]))*.3));canvas.Children.Add(line);};canvas.SizeChanged+=delegate{draw();};return canvas;}
 Border Metric(string name,string value,string detail,double percent,List<double> history,bool show,Action<bool> set){return Card("",()=>{var head=new DockPanel();var toggle=Switch("",show,v=>{set(v);string module=name=="Disk space"?"Disk space":name;if(v)cfg.HiddenModules.Remove(module);SaveConfig();SystemTopModules();ApplyModules();UpdateSystemLabels();});toggle.ToolTip="Show in top bar";DockPanel.SetDock(toggle,Dock.Right);head.Children.Add(toggle);var hint=Text("Show in top bar",9,mutedBrush);hint.Margin=new Thickness(3,0,3,0);DockPanel.SetDock(hint,Dock.Right);head.Children.Add(hint);head.Children.Add(Text(name,12,mutedBrush));page.Children.Add(head);var number=Text(value,23);number.FontWeight=FontWeights.SemiBold;number.Margin=new Thickness(0,10,0,8);page.Children.Add(number);var track=new Grid{Height=4,Background=cardBrush};var fill=new Border{Background=accentBrush,CornerRadius=new CornerRadius(2),HorizontalAlignment=HorizontalAlignment.Left};track.Children.Add(fill);track.SizeChanged+=delegate{fill.Width=track.ActualWidth*Math.Max(0,Math.Min(100,Double.IsNaN(percent)?0:percent))/100;};page.Children.Add(track);var caption=Text(detail,11,mutedBrush);caption.Margin=new Thickness(0,8,0,0);page.Children.Add(caption);page.Children.Add(Spark(history));});}
 void DrawSystemBody(){if(systemBody==null)return;if(backgroundAppsScroll!=null)backgroundAppsOffset=backgroundAppsScroll.VerticalOffset;var old=page;page=systemBody;page.Children.Clear();var cards=new UniformGrid{Columns=3};var a=Metric("CPU",Percent(systemSample.Cpu),Environment.ProcessorCount+" logical processors",systemSample.Cpu,cpuHistory,cfg.SystemCpuTop,v=>cfg.SystemCpuTop=v);a.Margin=new Thickness(0,0,10,16);cards.Children.Add(a);var b=Metric("Memory",systemSample.MemoryTotal>0?Gigabytes(systemSample.MemoryUsed):"—",systemSample.MemoryTotal>0?Gigabytes(systemSample.MemoryTotal)+" total":"Unavailable",systemSample.MemoryTotal>0?systemSample.MemoryUsed/systemSample.MemoryTotal*100:0,memoryHistory,cfg.SystemMemoryTop,v=>cfg.SystemMemoryTop=v);b.Margin=new Thickness(0,0,10,16);cards.Children.Add(b);cards.Children.Add(Metric("Disk space",systemSample.DiskTotal>0?Gigabytes(systemSample.DiskUsed):"—",systemSample.Drive+" · "+Gigabytes(systemSample.DiskTotal-systemSample.DiskUsed)+" free",systemSample.DiskTotal>0?systemSample.DiskUsed/systemSample.DiskTotal*100:0,diskHistory,cfg.SystemDiskTop,v=>cfg.SystemDiskTop=v));page.Children.Add(cards);
 page.Children.Add(Card("",()=>{var heading=new DockPanel();var sort=new StackPanel{Orientation=Orientation.Horizontal};foreach(string key in new[]{"CPU","Memory","I/O","Name"}){string value=key;sort.Children.Add(Action(key,()=>{systemSort=value;cfg.SystemSort=value;SaveConfig();DrawSystemBody();},systemSort==key));}DockPanel.SetDock(sort,Dock.Right);heading.Children.Add(sort);heading.Children.Add(Text("Running apps   "+systemSample.Apps.Count,13));page.Children.Add(heading);page.Children.Add(ProcessRow(null));var rows=new StackPanel();foreach(var item in SortedSystemApps(systemSample.Apps,systemSort))rows.Children.Add(ProcessRow(item));if(systemSample.Apps.Count==0)rows.Children.Add(Text("No accessible running apps",12,mutedBrush));double rowsHeight=Math.Max(70,Math.Min(220,systemSample.Apps.Count*46+8));page.Children.Add(new ScrollViewer{Height=rowsHeight,Content=rows,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled});}));
 page.Children.Add(Card("",()=>{var heading=Text("Background apps   "+systemSample.BackgroundApps.Count,13);heading.FontWeight=FontWeights.SemiBold;page.Children.Add(heading);page.Children.Add(ProcessRow(null,true));var rows=new StackPanel();foreach(var item in SortedSystemApps(systemSample.BackgroundApps,systemSort))rows.Children.Add(ProcessRow(item,true));if(systemSample.BackgroundApps.Count==0)rows.Children.Add(Text("No manageable background apps",12,mutedBrush));double rowsHeight=Math.Max(62,Math.Min(180,systemSample.BackgroundApps.Count*46+8));backgroundAppsScroll=new ScrollViewer{Height=rowsHeight,Content=rows,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};page.Children.Add(backgroundAppsScroll);Dispatcher.BeginInvoke(new Action(()=>{if(backgroundAppsScroll!=null)backgroundAppsScroll.ScrollToVerticalOffset(backgroundAppsOffset);}));}));
 page.Children.Add(SelfUsageCard());page=old;}
 FrameworkElement RingGauge(string label,string value,double percent){percent=Math.Max(0,Math.Min(100,Double.IsNaN(percent)?0:percent));var stack=new StackPanel{HorizontalAlignment=HorizontalAlignment.Center};var canvas=new Canvas{Width=66,Height=66};canvas.Children.Add(new Ellipse{Width=56,Height=56,Margin=new Thickness(5),Stroke=cardBrush,StrokeThickness=6});double angle=Math.Min(359.8,percent*3.6),r=28,cx=33,cy=33;var start=new Point(cx,cy-r);double radians=(angle-90)*Math.PI/180;var end=new Point(cx+r*Math.Cos(radians),cy+r*Math.Sin(radians));var figure=new PathFigure{StartPoint=start,IsClosed=false};figure.Segments.Add(new ArcSegment{Point=end,Size=new Size(r,r),SweepDirection=SweepDirection.Clockwise,IsLargeArc=angle>180});canvas.Children.Add(new System.Windows.Shapes.Path{Data=new PathGeometry(new[]{figure}),Stroke=accentBrush,StrokeThickness=6,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round});var number=Text(value,10);number.FontWeight=FontWeights.SemiBold;number.TextAlignment=TextAlignment.Center;number.HorizontalAlignment=HorizontalAlignment.Center;number.VerticalAlignment=VerticalAlignment.Center;number.TextWrapping=TextWrapping.Wrap;var holder=new Border{Width=56,Height=56,Child=number};Canvas.SetLeft(holder,5);Canvas.SetTop(holder,5);canvas.Children.Add(holder);stack.Children.Add(canvas);var caption=Text(label,10,mutedBrush);caption.HorizontalAlignment=HorizontalAlignment.Center;caption.Margin=new Thickness(0,2,0,0);stack.Children.Add(caption);return stack;}
 FrameworkElement SelfUsageCard(){return Card("Awl usage",()=>{var item=systemSample.Self;var row=new Grid();for(int i=0;i<4;i++)row.ColumnDefinitions.Add(new ColumnDefinition());double cpu=item==null?0:item.Cpu,memoryPercent=item==null||systemSample.MemoryTotal<=0?0:item.Memory/systemSample.MemoryTotal*100,io=item==null||Double.IsNaN(item.Io)?0:item.Io/1048576.0;var gauges=new[]{RingGauge("CPU",item==null?"—":Percent(item.Cpu),cpu),RingGauge("Memory",item==null?"—":(item.Memory/1048576).ToString("0")+" MB",memoryPercent),RingGauge("Disk I/O",item==null||Double.IsNaN(item.Io)?"—":io.ToString("0.00")+" MB/s",Math.Min(100,io*10))};for(int i=0;i<gauges.Length;i++){Grid.SetColumn(gauges[i],i);row.Children.Add(gauges[i]);}var task=Action("Open Task Manager",()=>Process.Start(new ProcessStartInfo("taskmgr.exe"){UseShellExecute=true}));task.HorizontalAlignment=HorizontalAlignment.Center;task.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(task,3);row.Children.Add(task);page.Children.Add(row);});}
 FrameworkElement ProcessRow(AppSample item,bool kill=false){var grid=new Grid{Margin=new Thickness(0,6,0,6)};grid.ColumnDefinitions.Add(new ColumnDefinition());foreach(double width in new[]{75.0,95.0,100.0,kill?58.0:32.0})grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(width)});if(item==null){string[] labels={"Process","CPU","Memory","I/O"};for(int i=0;i<labels.Length;i++){var text=Text(labels[i],11,mutedBrush);Grid.SetColumn(text,i);grid.Children.Add(text);}return grid;}var name=new StackPanel{Orientation=Orientation.Horizontal};var icon=new Image{Width=26,Height=26,Margin=new Thickness(0,0,10,0)};if(!String.IsNullOrEmpty(item.Path))QueueIcon(icon,item.Path);name.Children.Add(icon);var label=Text(item.Name,12);label.MaxWidth=240;label.TextWrapping=TextWrapping.NoWrap;label.TextTrimming=TextTrimming.CharacterEllipsis;label.ToolTip="PID "+item.Id;name.Children.Add(label);grid.Children.Add(name);string[] values={Percent(item.Cpu),Double.IsNaN(item.Memory)?"—":(item.Memory/1048576).ToString("0")+" MB",Double.IsNaN(item.Io)?"—":(item.Io/1048576).ToString("0.00")+" MB/s"};for(int i=0;i<3;i++){var text=Text(values[i],11,mutedBrush);Grid.SetColumn(text,i+1);grid.Children.Add(text);}var close=Action(kill?"Kill":"×",()=>{if(kill)KillSystemApp(item);else CloseSystemApp(item);});close.Padding=new Thickness(4);close.ToolTip=kill?"End background process":"Close app";Grid.SetColumn(close,4);grid.Children.Add(close);return new Border{BorderBrush=cardBrush,BorderThickness=new Thickness(0,0,0,1),Child=grid};}
 IEnumerable<AppSample> SortedSystemApps(IEnumerable<AppSample> source,string sort){if(sort=="CPU")return source.OrderByDescending(x=>Double.IsNaN(x.Cpu)?-1:x.Cpu).ThenBy(x=>x.Name);if(sort=="Memory")return source.OrderByDescending(x=>x.Memory).ThenBy(x=>x.Name);if(sort=="I/O")return source.OrderByDescending(x=>Double.IsNaN(x.Io)?-1:x.Io).ThenBy(x=>x.Name);return source.OrderBy(x=>x.Name,StringComparer.CurrentCultureIgnoreCase);}
 public string SystemSortSelfTest(){var values=new[]{new AppSample{Name="Zulu",Cpu=2,Memory=30,Io=8},new AppSample{Name="Alpha",Cpu=9,Memory=10,Io=3}};if(SortedSystemApps(values,"CPU").First().Name!="Alpha")return "FAILED: CPU order";if(SortedSystemApps(values,"Memory").First().Name!="Zulu")return "FAILED: memory order";if(SortedSystemApps(values,"I/O").First().Name!="Zulu")return "FAILED: I/O order";if(SortedSystemApps(values,"Name").First().Name!="Alpha")return "FAILED: name order";return "System CPU, memory, I/O, and name orders work";}
 void CloseSystemApp(AppSample item){try{using(var process=Process.GetProcessById(item.Id)){if(process.StartTime.ToUniversalTime().Ticks!=item.Start)return;if(!process.CloseMainWindow())MessageBox.Show(launcher,"This app did not accept a close request.","Close app");}}catch(ArgumentException){}catch(Exception e){MessageBox.Show(launcher,e.Message,"Unable to close app");}}
 void KillSystemApp(AppSample item){try{using(var process=Process.GetProcessById(item.Id)){if(process.StartTime.ToUniversalTime().Ticks!=item.Start)return;process.Kill();}}catch(ArgumentException){}catch(Exception e){MessageBox.Show(launcher,e.Message,"Unable to end background process");}}
} }
