using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using System.Web.Script.Serialization;
using Microsoft.Win32;

namespace Awl {
 public class ShellTemplateManifest {
  public int version=1;
  public string name="Template",created="",preview="preview.png",wallpaperKind="system",wallpaperEntry="",wallpaperLink="",wallpaperProject="";
  public bool requiresWallpaperEngine=false;
 }

 partial class Shell {
  string TemplateFolder { get { return Path.Combine(Root,"Templates"); } }
  string MyTemplateFolder { get { return Path.Combine(TemplateFolder,"My Templates"); } }
  string InbuiltTemplateFolder { get { return Path.Combine(TemplateFolder,"Inbuilt Templates"); } }
  string ImportedTemplateFolder { get { return Path.Combine(TemplateFolder,"Imported Templates"); } }
  string PublicTemplateFolder { get { return Path.Combine(TemplateFolder,"Public Templates"); } }
  string SafeTemplateName(string name){var invalid=Path.GetInvalidFileNameChars();var clean=new string((name??"").Where(c=>!invalid.Contains(c)).ToArray()).Trim();return String.IsNullOrWhiteSpace(clean)?"My Template":clean;}

  void ConfigPage(){
   Directory.CreateDirectory(MyTemplateFolder);Directory.CreateDirectory(InbuiltTemplateFolder);Directory.CreateDirectory(ImportedTemplateFolder);Directory.CreateDirectory(PublicTemplateFolder);
   Header("Config");
   var actions=new WrapPanel{Margin=new Thickness(0,0,0,12)};
   var save=Action("＋  Save template",BeginSaveTemplate);save.Content=NavLabel("Config","Save template",save.Foreground,18);actions.Children.Add(save);
   var import=Action("⇧  Import template",ImportShellTemplate);import.Content=NavLabel("Widgets","Import template",import.Foreground,18);actions.Children.Add(import);if(devMode){var builtIn=Action("Save as in-built",BeginSaveInbuiltTemplate);builtIn.Content=NavLabel("Config","Save as in-built",builtIn.Foreground,18);actions.Children.Add(builtIn);}page.Children.Add(actions);
   page.Children.Add(Card("Templates",()=>{TemplateSection("My templates",MyTemplateFiles(),"Save a template to add it here.");TemplateSection("In-built templates",TemplateFiles(InbuiltTemplateFolder),"Built-in presets will appear here.");TemplateSection("Imported templates",TemplateFiles(ImportedTemplateFolder),"Imported ZIP templates appear here.");TemplateSection("Public templates",TemplateFiles(PublicTemplateFolder),"Public templates appear here when added.");}));
  }

  string[] TemplateFiles(string folder){return Directory.Exists(folder)?Directory.GetFiles(folder,"*.zip").OrderByDescending(File.GetLastWriteTimeUtc).ToArray():new string[0];}
  void EnsureEmbeddedInbuiltTemplates(){
   try{Directory.CreateDirectory(InbuiltTemplateFolder);var assembly=System.Reflection.Assembly.GetExecutingAssembly();foreach(string resource in assembly.GetManifestResourceNames().Where(x=>x.StartsWith("Awl.InbuiltTemplates.",StringComparison.OrdinalIgnoreCase)&&x.EndsWith(".zip",StringComparison.OrdinalIgnoreCase))){byte[] bytes;using(var input=assembly.GetManifestResourceStream(resource)){if(input==null)continue;using(var memory=new MemoryStream()){input.CopyTo(memory);bytes=memory.ToArray();}}ShellTemplateManifest manifest;using(var memory=new MemoryStream(bytes))using(var zip=new ZipArchive(memory,ZipArchiveMode.Read))manifest=ReadTemplateManifest(zip);string destination=Path.Combine(InbuiltTemplateFolder,SafeTemplateName(manifest.name)+".zip");bool write=!File.Exists(destination);if(!write){var existing=new FileInfo(destination);write=existing.Length!=bytes.LongLength;}if(write){string temp=destination+".tmp";File.WriteAllBytes(temp,bytes);if(File.Exists(destination))File.Delete(destination);File.Move(temp,destination);}}}catch(Exception error){Log("Built-in templates: "+error.Message);}
  }
  string[] MyTemplateFiles(){var files=new List<string>();files.AddRange(TemplateFiles(MyTemplateFolder));if(Directory.Exists(TemplateFolder))files.AddRange(Directory.GetFiles(TemplateFolder,"*.zip"));return files.Distinct(StringComparer.OrdinalIgnoreCase).OrderByDescending(File.GetLastWriteTimeUtc).ToArray();}
  void TemplateSection(string title,string[] files,string emptyText){var heading=new DockPanel{Margin=new Thickness(0,files.Length==0?4:8,0,10)};heading.Children.Add(NavLabel("Config",title,ink,20));page.Children.Add(heading);if(files.Length==0){var empty=Text(emptyText,12,mutedBrush);empty.Margin=new Thickness(8,2,8,18);page.Children.Add(empty);return;}var grid=new UniformGrid{Columns=3,Margin=new Thickness(0,0,0,18)};foreach(var file in files)grid.Children.Add(TemplateCard(file));page.Children.Add(grid);}

  FrameworkElement TemplateCard(string file){
   ShellTemplateManifest manifest;ImageSource preview=null;try{using(var zip=ZipFile.OpenRead(file)){manifest=ReadTemplateManifest(zip);preview=LoadTemplatePreview(file,zip,manifest);}}catch(Exception error){manifest=new ShellTemplateManifest{name=Path.GetFileNameWithoutExtension(file)};Log("Template preview: "+error.Message);}
   bool blocked=manifest.requiresWallpaperEngine&&!HasWallpaperEngine(),active=String.Equals(cfg.ActiveTemplate,TemplateKey(file),StringComparison.OrdinalIgnoreCase)||String.Equals(cfg.ActiveTemplate,Path.GetFileName(file),StringComparison.OrdinalIgnoreCase);var outer=new Border{CornerRadius=new CornerRadius(16),Background=cardBrush,BorderBrush=active?accentBrush:new SolidColorBrush(Mix(baseColor,Colors.White,.15)),BorderThickness=new Thickness(active?2:1),Margin=new Thickness(6),Opacity=blocked?.38:1,ClipToBounds=true,Cursor=blocked?Cursors.Arrow:Cursors.Hand};
   var stack=new StackPanel();var hero=new Grid{Height=126,Background=preview==null?panelBrush:(Brush)new ImageBrush(preview){Stretch=Stretch.UniformToFill}};bool builtIn=Path.GetFullPath(file).StartsWith(Path.GetFullPath(InbuiltTemplateFolder).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);if(!builtIn||devMode){var menu=Action("•••",()=>{});menu.Width=38;menu.Height=30;menu.HorizontalAlignment=HorizontalAlignment.Left;menu.VerticalAlignment=VerticalAlignment.Top;menu.Margin=new Thickness(6);var context=new ContextMenu();ThemeContextMenu(context);var update=new MenuItem{Header="Update from current config"};update.Click+=delegate{UpdateTemplateConfig(file);};context.Items.Add(update);var edit=new MenuItem{Header="Edit template"};edit.Click+=delegate{EditTemplateDialog(file);};context.Items.Add(edit);var export=new MenuItem{Header="Export ZIP…"};export.Click+=delegate{ExportTemplateCopy(file);};context.Items.Add(export);var remove=new MenuItem{Header="Delete template",Foreground=Brushes.IndianRed};remove.Click+=delegate{DeleteShellTemplate(file,active);};context.Items.Add(remove);menu.Click+=delegate{menu.ContextMenu=context;context.PlacementTarget=menu;context.Placement=PlacementMode.Bottom;context.IsOpen=true;};hero.Children.Add(menu);}
   if(manifest.requiresWallpaperEngine){FrameworkElement mark;string enginePath=WallpaperEngineExecutable();if(!String.IsNullOrEmpty(enginePath)){var icon=new Image{Width=17,Height=17};QueueIcon(icon,enginePath);mark=icon;}else mark=Text("WE",10,Brushes.White);var badge=new Border{CornerRadius=new CornerRadius(10),Background=new SolidColorBrush(Color.FromArgb(225,34,39,44)),Padding=new Thickness(7,3,7,3),HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Top,Margin=new Thickness(7),ToolTip=blocked?"requires wallpaper engine":"Wallpaper Engine template",Child=mark};hero.Children.Add(badge);}
   stack.Children.Add(hero);var footer=new Grid{Margin=new Thickness(10,8,10,9)};footer.ColumnDefinitions.Add(new ColumnDefinition());footer.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var name=Text(manifest.name,13);name.FontWeight=FontWeights.SemiBold;footer.Children.Add(name);if(active){var label=Text("Active",10,accentBrush);label.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(label,1);footer.Children.Add(label);}stack.Children.Add(footer);outer.Child=stack;
   if(blocked)outer.ToolTip="requires wallpaper engine";else outer.MouseLeftButtonUp+=delegate(object sender,MouseButtonEventArgs e){DependencyObject node=e.OriginalSource as DependencyObject;while(node!=null&&node!=outer){if(node is Button)return;node=VisualTreeHelper.GetParent(node);}ApplyShellTemplate(file);};return outer;
  }

  ImageSource LoadTemplatePreview(string file,ZipArchive zip,ShellTemplateManifest manifest){var entry=zip.GetEntry(String.IsNullOrEmpty(manifest.preview)?"preview.png":manifest.preview);if(entry==null)return null;string cacheFolder=Path.Combine(Root,"TemplateData","Thumbnails");Directory.CreateDirectory(cacheFolder);string identity=SafeTemplateName(Path.GetFileNameWithoutExtension(file))+"-"+Math.Abs(Path.GetFullPath(file).ToLowerInvariant().GetHashCode()).ToString("x");string extension=Path.GetExtension(entry.Name);if(String.IsNullOrEmpty(extension))extension=".png";string cache=Path.Combine(cacheFolder,identity+extension),temp=cache+".tmp";using(var input=entry.Open())using(var output=File.Create(temp))input.CopyTo(output);if(File.Exists(cache))File.Delete(cache);File.Move(temp,cache);return FileImage(cache,420);}
  void ClearTemplatePreviewCache(string file){try{string folder=Path.Combine(Root,"TemplateData","Thumbnails"),prefix=SafeTemplateName(Path.GetFileNameWithoutExtension(file))+"-"+Math.Abs(Path.GetFullPath(file).ToLowerInvariant().GetHashCode()).ToString("x");if(Directory.Exists(folder))foreach(string cached in Directory.GetFiles(folder,prefix+".*"))File.Delete(cached);}catch{}}

  ShellTemplateManifest ReadTemplateManifest(ZipArchive zip){var entry=zip.GetEntry("manifest.json");if(entry==null)throw new InvalidDataException("This ZIP is not a Awl template.");using(var reader=new StreamReader(entry.Open())){var value=new JavaScriptSerializer().Deserialize<ShellTemplateManifest>(reader.ReadToEnd());if(value==null)throw new InvalidDataException("The template manifest is invalid.");return value;}}
  string TemplateKey(string file){try{string root=Path.GetFullPath(TemplateFolder).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,full=Path.GetFullPath(file);return full.StartsWith(root,StringComparison.OrdinalIgnoreCase)?full.Substring(root.Length).Replace('\\','/'):Path.GetFileName(file);}catch{return Path.GetFileName(file);}}
  void BeginSaveTemplate(){BeginSaveTemplate(MyTemplateFolder,"Save template");}
  void BeginSaveInbuiltTemplate(){BeginSaveTemplate(InbuiltTemplateFolder,"Save as in-built");}
  void BeginSaveTemplate(string targetFolder,string heading){
   var dialog=new Window{Title=heading,Owner=launcher,Width=440,Height=365,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,WindowStyle=WindowStyle.None,AllowsTransparency=true,Background=Brushes.Transparent};string thumbnail="";var host=new StackPanel{Margin=new Thickness(18)};host.Children.Add(Text(heading,18));var input=new TextBox{Text=targetFolder==InbuiltTemplateFolder?"Built-in Preset":"My Template",Margin=new Thickness(0,12,0,10),Padding=new Thickness(12,9,12,9),Background=cardBrush,Foreground=ink,BorderBrush=accentBrush,FontSize=14};host.Children.Add(input);var preview=new Border{Height=150,CornerRadius=new CornerRadius(12),Background=panelBrush,Margin=new Thickness(0,0,0,8),Child=Text("Choose a thumbnail image",13,mutedBrush)};host.Children.Add(preview);var choose=Action("▧  Choose thumbnail",()=>{var picker=new OpenFileDialog{Title="Choose template thumbnail",Filter="Images|*.jpg;*.jpeg;*.png;*.bmp;*.gif"};if(picker.ShowDialog(dialog)==true){thumbnail=picker.FileName;var image=FileImage(thumbnail,720);if(image!=null){preview.Child=null;preview.Background=new ImageBrush(image){Stretch=Stretch.UniformToFill};}}});host.Children.Add(choose);var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};buttons.Children.Add(Action("Cancel",()=>dialog.Close()));buttons.Children.Add(Action("Save",()=>{var name=SafeTemplateName(input.Text);dialog.Close();CaptureAndSaveTemplate(name,thumbnail,targetFolder);}));host.Children.Add(buttons);dialog.Content=new Border{CornerRadius=new CornerRadius(20),Background=SurfaceBrush(baseColor,.97,cfg.StartMenuGlass??cfg.GlassEffect),BorderBrush=accentBrush,BorderThickness=new Thickness(1),Child=host};dialog.ShowDialog();
  }
  void CaptureAndSaveTemplate(string name,string thumbnail,string targetFolder){
   activeTab="Quick";DrawLauncher();if(launcher!=null){launcher.Show();launcher.Activate();launcher.UpdateLayout();}if(dock!=null){dock.BeginAnimation(Window.OpacityProperty,null);dock.Opacity=1;dock.Show();}if(top!=null&&cfg.ShowTop){top.Opacity=1;top.Show();}if(clockWidget!=null&&cfg.DateTimeWidget.Enabled)clockWidget.Show();if(recentWindow!=null&&cfg.Recents.Enabled)recentWindow.Show();foreach(var widget in builderDesktopWindows.Values)widget.Show();
   Dispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle,new Action(delegate{try{Directory.CreateDirectory(targetFolder);string file=UniqueTemplatePath(targetFolder,name,null);string preview=Path.Combine(Path.GetTempPath(),"Awl-template-"+Guid.NewGuid().ToString("N")+".png");if(File.Exists(thumbnail))CreateThumbnail(thumbnail,preview);else CaptureDesktopPreview(preview);cfg.ActiveTemplate=TemplateKey(file);SaveConfig();WriteShellTemplate(file,name,preview);try{File.Delete(preview);}catch{}}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be saved");}finally{activeTab="Config";DrawLauncher();}}));
  }
  string UniqueTemplatePath(string folder,string name,string exclude){Directory.CreateDirectory(folder);string baseName=SafeTemplateName(name),path=Path.Combine(folder,baseName+".zip");int i=2;while(File.Exists(path)&&!String.Equals(Path.GetFullPath(path),exclude==null?"":Path.GetFullPath(exclude),StringComparison.OrdinalIgnoreCase))path=Path.Combine(folder,baseName+" "+i+++".zip");return path;}
  void CreateThumbnail(string source,string destination){using(var image=new System.Drawing.Bitmap(source))using(var thumb=new System.Drawing.Bitmap(720,405)){using(var graphics=System.Drawing.Graphics.FromImage(thumb)){graphics.Clear(System.Drawing.Color.FromArgb(baseColor.R,baseColor.G,baseColor.B));double scale=Math.Max(720.0/image.Width,405.0/image.Height);int width=(int)Math.Ceiling(image.Width*scale),height=(int)Math.Ceiling(image.Height*scale);graphics.DrawImage(image,(720-width)/2,(405-height)/2,width,height);}thumb.Save(destination,System.Drawing.Imaging.ImageFormat.Png);}}
  void CaptureDesktopPreview(string path){var bounds=System.Windows.Forms.SystemInformation.VirtualScreen;using(var source=new System.Drawing.Bitmap(bounds.Width,bounds.Height,System.Drawing.Imaging.PixelFormat.Format32bppArgb)){using(var graphics=System.Drawing.Graphics.FromImage(source))graphics.CopyFromScreen(bounds.Left,bounds.Top,0,0,bounds.Size);int width=720,height=Math.Max(360,(int)Math.Round(width*(double)bounds.Height/bounds.Width));using(var thumb=new System.Drawing.Bitmap(source,width,height))thumb.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}

  void WriteShellTemplate(string file,string name,string preview){
   var serializer=new JavaScriptSerializer();var clone=serializer.Deserialize<Preferences>(serializer.Serialize(cfg));RemovePersonalTemplateState(clone);var manifest=WallpaperManifest();manifest.name=name;manifest.created=DateTime.UtcNow.ToString("o");if(manifest.wallpaperKind=="file"&&File.Exists(manifest.wallpaperProject)){manifest.wallpaperEntry="wallpaper/"+Path.GetFileName(manifest.wallpaperProject);clone.DesktopWallpaper=manifest.wallpaperEntry;clone.Wallpaper=manifest.wallpaperEntry;}
   if(File.Exists(file))File.Delete(file);using(var zip=ZipFile.Open(file,ZipArchiveMode.Create)){AddText(zip,"manifest.json",Pretty(serializer.Serialize(manifest)));AddText(zip,"config.json",Pretty(serializer.Serialize(clone)));AddFile(zip,preview,"preview.png");WritePortableWidgetState(zip,serializer);string paletteFile=Path.Combine(Root,"palette.json");if(File.Exists(paletteFile))AddFile(zip,paletteFile,"palette.json");if(!String.IsNullOrEmpty(manifest.wallpaperEntry))AddFile(zip,manifest.wallpaperProject,manifest.wallpaperEntry);}
  }
  void AddText(ZipArchive zip,string name,string value){var entry=zip.CreateEntry(name,CompressionLevel.Optimal);using(var writer=new StreamWriter(entry.Open()))writer.Write(value);}
  void RemovePersonalTemplateState(Preferences value){value.StartPins=new List<AppEntry>();value.DockPins=new List<AppEntry>();value.PinnedOrder=new List<string>();value.RecentApps=new List<RecentEntry>();value.LaunchCounts=new Dictionary<string,int>();value.LastLaunch=new Dictionary<string,long>();value.WeatherLocation="";value.WeatherLatitude=0;value.WeatherLongitude=0;value.LaunchOnSignIn=null;}
  public string SanitizeInbuiltTemplateSources(){var results=new List<string>();string folder=Path.Combine(DevProjectRoot(),"templates","Inbuilt Templates");foreach(string file in TemplateFiles(folder)){try{using(var zip=ZipFile.Open(file,ZipArchiveMode.Update)){var entry=zip.GetEntry("config.json");if(entry==null)continue;Preferences value;using(var reader=new StreamReader(entry.Open()))value=new JavaScriptSerializer().Deserialize<Preferences>(reader.ReadToEnd());entry.Delete();RemovePersonalTemplateState(value);AddText(zip,"config.json",Pretty(new JavaScriptSerializer().Serialize(value)));}results.Add("Sanitized "+Path.GetFileName(file));}catch(Exception error){results.Add("FAILED "+Path.GetFileName(file)+": "+error.Message);}}return String.Join(Environment.NewLine,results);}
  void AddFile(ZipArchive zip,string source,string name){var entry=zip.CreateEntry(name.Replace('\\','/'),CompressionLevel.Optimal);using(var input=File.OpenRead(source))using(var output=entry.Open())input.CopyTo(output);}
  void WritePortableWidgetState(ZipArchive zip,JavaScriptSerializer serializer){
   var used=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var desktop=new WidgetBuilderDesktopState();try{if(File.Exists(BuilderDesktopFile))desktop=serializer.Deserialize<WidgetBuilderDesktopState>(File.ReadAllText(BuilderDesktopFile))??desktop;}catch{}foreach(var deployment in desktop.widgets.Where(x=>x.project!=null))PackageTemplateAssets(zip,deployment.project,"desktop-"+deployment.id,used);AddText(zip,"desktop-widgets.json",Pretty(serializer.Serialize(desktop)));
   try{string builderFile=Path.Combine(Root,"widget-builder.json");if(File.Exists(builderFile)){var project=serializer.Deserialize<WidgetBuilderProject>(File.ReadAllText(builderFile));if(project!=null){PackageTemplateAssets(zip,project,"builder",used);AddText(zip,"widget-builder.json",Pretty(serializer.Serialize(project)));}}}catch{}
  }
  void PackageTemplateAssets(ZipArchive zip,WidgetBuilderProject project,string group,HashSet<string> used){foreach(var node in PackageNodes(project)){BuilderValue property;if(!node.properties.TryGetValue("source",out property))continue;string source=Convert.ToString(property.value);if(!File.Exists(source))continue;string name=SafeWidgetName(group)+"/"+Path.GetFileName(source),candidate=name;int index=2;while(!used.Add(candidate))candidate=SafeWidgetName(group)+"/"+Path.GetFileNameWithoutExtension(source)+"-"+(index++)+Path.GetExtension(source);string entry="template-assets/"+candidate.Replace('\\','/');AddFile(zip,source,entry);property.value=entry;}}

  ShellTemplateManifest WallpaperManifest(){
   var value=new ShellTemplateManifest();if(!String.IsNullOrEmpty(cfg.DesktopWallpaper)&&File.Exists(cfg.DesktopWallpaper)){value.wallpaperKind="file";value.wallpaperProject=cfg.DesktopWallpaper;return value;}
   string project,link;if(TryWallpaperEngineProject(out project,out link)){value.wallpaperKind="wallpaper-engine";value.requiresWallpaperEngine=true;value.wallpaperProject=project;value.wallpaperLink=link;return value;}
   string current=WallpaperPath();if(File.Exists(current)){value.wallpaperKind="file";value.wallpaperProject=current;}return value;
  }
  bool TryWallpaperEngineProject(out string project,out string link){project="";link="";try{var serializer=new JavaScriptSerializer();var all=serializer.Deserialize<Dictionary<string,object>>(File.ReadAllText(cfg.WallpaperEngineConfig));var user=(Dictionary<string,object>)all[Environment.UserName];var general=(Dictionary<string,object>)user["general"];var wc=(Dictionary<string,object>)general["wallpaperconfig"];var selected=(Dictionary<string,object>)wc["selectedwallpapers"];var monitor=(Dictionary<string,object>)selected.Values.First();project=Convert.ToString(monitor["file"]);string json=Path.Combine(Path.GetDirectoryName(project),"project.json");var metadata=serializer.Deserialize<Dictionary<string,object>>(File.ReadAllText(json));object id,url;if(metadata.TryGetValue("workshopid",out id)&&!String.IsNullOrEmpty(Convert.ToString(id)))link="https://steamcommunity.com/sharedfiles/filedetails/?id="+Convert.ToString(id);else if(metadata.TryGetValue("workshopurl",out url))link=Convert.ToString(url);return File.Exists(project)||!String.IsNullOrEmpty(link);}catch{return false;}}
  string WallpaperEnginePreview(string project){try{string folder=Directory.Exists(project)?project:Path.GetDirectoryName(project);if(String.IsNullOrEmpty(folder))return "";string json=Path.Combine(folder,"project.json");if(File.Exists(json)){var metadata=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(File.ReadAllText(json));object value;if(metadata!=null&&metadata.TryGetValue("preview",out value)){string preview=Path.Combine(folder,Convert.ToString(value));if(File.Exists(preview))return preview;}}foreach(string name in new[]{"preview.jpg","preview.png","preview.gif","preview.jpeg"}){string preview=Path.Combine(folder,name);if(File.Exists(preview))return preview;}}catch{}return "";}

  void ImportShellTemplate(){var picker=new OpenFileDialog{Title="Import Awl template",Filter="Awl templates (*.zip)|*.zip|ZIP files (*.zip)|*.zip"};if(picker.ShowDialog(launcher)!=true)return;try{Directory.CreateDirectory(ImportedTemplateFolder);using(var zip=ZipFile.OpenRead(picker.FileName))ReadTemplateManifest(zip);string destination=UniqueTemplatePath(ImportedTemplateFolder,Path.GetFileNameWithoutExtension(picker.FileName),null);File.Copy(picker.FileName,destination);DrawLauncher();}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be imported");}}
  void ExportTemplateCopy(string source){var picker=new SaveFileDialog{Title="Export template",Filter="Awl template (*.zip)|*.zip",FileName=Path.GetFileName(source)};if(picker.ShowDialog(launcher)==true)File.Copy(source,picker.FileName,true);}
  void UpdateTemplateConfig(string file){try{var serializer=new JavaScriptSerializer();var clone=serializer.Deserialize<Preferences>(serializer.Serialize(cfg));RemovePersonalTemplateState(clone);clone.ActiveTemplate=TemplateKey(file);using(var zip=ZipFile.Open(file,ZipArchiveMode.Update)){var old=zip.GetEntry("config.json");if(old!=null)old.Delete();AddText(zip,"config.json",Pretty(serializer.Serialize(clone)));}ClearTemplatePreviewCache(file);DrawLauncher();}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be updated");}}
  void DeleteShellTemplate(string file,bool active){try{ClearTemplatePreviewCache(file);File.Delete(file);if(active){cfg.ActiveTemplate="";SaveConfig();}DrawLauncher();}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be deleted");}}
  void EditTemplateDialog(string file){
   ShellTemplateManifest manifest;ImageSource current=null;try{using(var zip=ZipFile.OpenRead(file)){manifest=ReadTemplateManifest(zip);var image=zip.GetEntry(manifest.preview);if(image!=null)using(var stream=image.Open()){var bitmap=new BitmapImage();bitmap.BeginInit();bitmap.CacheOption=BitmapCacheOption.OnLoad;bitmap.StreamSource=stream;bitmap.DecodePixelWidth=720;bitmap.EndInit();bitmap.Freeze();current=bitmap;}}}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be edited");return;}
   var dialog=new Window{Title="Edit template",Owner=launcher,Width=440,Height=365,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,WindowStyle=WindowStyle.None,AllowsTransparency=true,Background=Brushes.Transparent};string thumbnail="";var host=new StackPanel{Margin=new Thickness(18)};host.Children.Add(Text("Edit template",18));var input=new TextBox{Text=manifest.name,Margin=new Thickness(0,12,0,10),Padding=new Thickness(12,9,12,9),Background=cardBrush,Foreground=ink,BorderBrush=accentBrush,FontSize=14};host.Children.Add(input);var preview=new Border{Height=150,CornerRadius=new CornerRadius(12),Background=current==null?panelBrush:(Brush)new ImageBrush(current){Stretch=Stretch.UniformToFill},Margin=new Thickness(0,0,0,8)};host.Children.Add(preview);host.Children.Add(Action("▧  Replace thumbnail",()=>{var picker=new OpenFileDialog{Title="Choose template thumbnail",Filter="Images|*.jpg;*.jpeg;*.png;*.bmp;*.gif"};if(picker.ShowDialog(dialog)==true){thumbnail=picker.FileName;var image=FileImage(thumbnail,720);if(image!=null)preview.Background=new ImageBrush(image){Stretch=Stretch.UniformToFill};}}));var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};buttons.Children.Add(Action("Cancel",()=>dialog.Close()));buttons.Children.Add(Action("Save",()=>{dialog.Close();EditShellTemplate(file,SafeTemplateName(input.Text),thumbnail);}));host.Children.Add(buttons);dialog.Content=new Border{CornerRadius=new CornerRadius(20),Background=SurfaceBrush(baseColor,.97,cfg.StartMenuGlass??cfg.GlassEffect),BorderBrush=accentBrush,BorderThickness=new Thickness(1),Child=host};dialog.ShowDialog();
  }
  void EditShellTemplate(string file,string name,string thumbnail){try{bool active=String.Equals(cfg.ActiveTemplate,TemplateKey(file),StringComparison.OrdinalIgnoreCase)||String.Equals(cfg.ActiveTemplate,Path.GetFileName(file),StringComparison.OrdinalIgnoreCase);ClearTemplatePreviewCache(file);using(var zip=ZipFile.Open(file,ZipArchiveMode.Update)){var manifest=ReadTemplateManifest(zip);manifest.name=name;var manifestEntry=zip.GetEntry("manifest.json");if(manifestEntry!=null)manifestEntry.Delete();AddText(zip,"manifest.json",Pretty(new JavaScriptSerializer().Serialize(manifest)));if(File.Exists(thumbnail)){string temp=Path.Combine(Path.GetTempPath(),"Awl-thumb-"+Guid.NewGuid().ToString("N")+".png");CreateThumbnail(thumbnail,temp);var old=zip.GetEntry(manifest.preview);if(old!=null)old.Delete();AddFile(zip,temp,manifest.preview);try{File.Delete(temp);}catch{}}}string destination=UniqueTemplatePath(Path.GetDirectoryName(file),name,file);if(!String.Equals(Path.GetFullPath(destination),Path.GetFullPath(file),StringComparison.OrdinalIgnoreCase)){File.Move(file,destination);if(active){cfg.ActiveTemplate=TemplateKey(destination);SaveConfig();}}DrawLauncher();}catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be edited");}}

  void ApplyShellTemplate(string file){
   try{ShellTemplateManifest manifest;Preferences next;var serializer=new JavaScriptSerializer();string unpack=Path.Combine(Root,"TemplateData",Path.GetFileNameWithoutExtension(file));Directory.CreateDirectory(unpack);using(var zip=ZipFile.OpenRead(file)){manifest=ReadTemplateManifest(zip);if(manifest.requiresWallpaperEngine&&!HasWallpaperEngine())return;var config=zip.GetEntry("config.json");if(config==null)throw new InvalidDataException("The template has no config.json.");using(var reader=new StreamReader(config.Open()))next=serializer.Deserialize<Preferences>(reader.ReadToEnd());foreach(var asset in zip.Entries.Where(x=>x.FullName.StartsWith("template-assets/",StringComparison.OrdinalIgnoreCase)&&!String.IsNullOrEmpty(x.Name)))ExtractTemplateAsset(asset,unpack);RestorePortableWidgetState(zip,serializer,unpack);ExtractEntry(zip,"palette.json",Path.Combine(Root,"palette.json"));if(!String.IsNullOrEmpty(manifest.wallpaperEntry)){string destination=Path.Combine(unpack,Path.GetFileName(manifest.wallpaperEntry));ExtractEntry(zip,manifest.wallpaperEntry,destination);next.DesktopWallpaper=destination;next.Wallpaper=destination;}}
    next.StartPins=cfg.StartPins;next.DockPins=cfg.DockPins;next.PinnedOrder=cfg.PinnedOrder;next.RecentApps=cfg.RecentApps;next.LaunchCounts=cfg.LaunchCounts;next.LastLaunch=cfg.LastLaunch;next.WeatherLocation=cfg.WeatherLocation;next.WeatherLatitude=cfg.WeatherLatitude;next.WeatherLongitude=cfg.WeatherLongitude;next.LaunchOnSignIn=cfg.LaunchOnSignIn;next.ActiveTemplate=TemplateKey(file);cfg=next;SaveConfig();bool engineTemplate=manifest.wallpaperKind=="wallpaper-engine";if(engineTemplate){if(wallpaperWindow!=null){wallpaperWindow.Close();wallpaperWindow=null;wallpaperVideo=null;}cfg.DesktopWallpaper="";cfg.Wallpaper=WallpaperEnginePreview(manifest.wallpaperProject);SaveConfig();if(File.Exists(manifest.wallpaperProject))WallpaperEngineControl("openWallpaper -file \""+manifest.wallpaperProject+"\"");else if(!String.IsNullOrEmpty(manifest.wallpaperLink))Process.Start(new ProcessStartInfo(manifest.wallpaperLink){UseShellExecute=true});}else if(!String.IsNullOrEmpty(cfg.DesktopWallpaper)&&File.Exists(cfg.DesktopWallpaper))StartDesktopWallpaper(cfg.DesktopWallpaper);ReloadEverything();activeTab="Config";DrawLauncher();RefreshTemplateAppearance();ScheduleTemplateAppearanceRefresh(cfg.ActiveTemplate,engineTemplate);
   }catch(Exception error){MessageBox.Show(launcher,error.Message,"Template could not be applied");}
  }
  void ExtractEntry(ZipArchive zip,string name,string destination){var entry=zip.GetEntry(name.Replace('\\','/'));if(entry==null)return;Directory.CreateDirectory(Path.GetDirectoryName(destination));string temp=destination+".tmp";using(var input=entry.Open())using(var output=File.Create(temp))input.CopyTo(output);if(File.Exists(destination))File.Delete(destination);File.Move(temp,destination);}
  void ExtractTemplateAsset(ZipArchiveEntry entry,string unpack){string relative=entry.FullName.Replace('/',Path.DirectorySeparatorChar);string destination=Path.GetFullPath(Path.Combine(unpack,relative));string root=Path.GetFullPath(unpack)+Path.DirectorySeparatorChar;if(!destination.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Unsafe template asset path.");Directory.CreateDirectory(Path.GetDirectoryName(destination));entry.ExtractToFile(destination,true);}
  void RestorePortableWidgetState(ZipArchive zip,JavaScriptSerializer serializer,string unpack){
   var desktopEntry=zip.GetEntry("desktop-widgets.json");if(desktopEntry!=null){WidgetBuilderDesktopState state;using(var reader=new StreamReader(desktopEntry.Open()))state=serializer.Deserialize<WidgetBuilderDesktopState>(reader.ReadToEnd());if(state==null)state=new WidgetBuilderDesktopState();foreach(var deployment in state.widgets.Where(x=>x.project!=null))RestoreTemplateAssets(deployment.project,unpack);File.WriteAllText(BuilderDesktopFile,Pretty(serializer.Serialize(state)));}else if(File.Exists(BuilderDesktopFile))File.Delete(BuilderDesktopFile);
   var builderEntry=zip.GetEntry("widget-builder.json");string builderFile=Path.Combine(Root,"widget-builder.json");if(builderEntry!=null){WidgetBuilderProject project;using(var reader=new StreamReader(builderEntry.Open()))project=serializer.Deserialize<WidgetBuilderProject>(reader.ReadToEnd());if(project!=null){RestoreTemplateAssets(project,unpack);File.WriteAllText(builderFile,Pretty(serializer.Serialize(project)));}}else if(File.Exists(builderFile))File.Delete(builderFile);
  }
  void RestoreTemplateAssets(WidgetBuilderProject project,string unpack){foreach(var node in PackageNodes(project)){BuilderValue property;if(!node.properties.TryGetValue("source",out property))continue;string value=Convert.ToString(property.value);if(value.StartsWith("template-assets/",StringComparison.OrdinalIgnoreCase))property.value=Path.GetFullPath(Path.Combine(unpack,value.Replace('/',Path.DirectorySeparatorChar)));}}

  void ReloadEverything(){
   LoadConfig();ApplyStartupPreference();SampleWallpaper(true);ApplyTheme();if(clockWidget!=null)ApplyClockWidget();recentSignature="";if(cfg.Recents.Enabled)DrawRecents();else if(recentWindow!=null)recentWindow.Hide();
   ReloadBuilderDesktop();signature="";RefreshApps();RefreshPinnedMenu();if(launcher!=null)DrawLauncher();
  }
  void ReloadWallpaperTheme(){cfg.Automatic=true;cfg.PaletteMode="Auto";cfg.SelectedWallpaperColor="";SaveConfig();ReloadEverything();activeTab="Quick";if(launcher!=null)DrawLauncher();}
  void RefreshTemplateAppearance(){SampleWallpaper(true);ApplyTheme();if(clockWidget!=null)ApplyClockWidget();recentSignature="";if(cfg.Recents.Enabled)DrawRecents();else if(recentWindow!=null)recentWindow.Hide();foreach(var deployment in builderDesktopState==null?new WidgetBuilderDeployment[0]:builderDesktopState.widgets.Where(x=>x.enabled).ToArray())DrawBuilderDesktop(deployment);signature="";RefreshApps();RefreshPinnedMenu();if(launcher!=null)DrawLauncher();}
  void ScheduleTemplateAppearanceRefresh(string templateKey,bool wallpaperEngine){int ticks=0;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(wallpaperEngine?750:180)};timer.Tick+=delegate{ticks++;if(!String.Equals(cfg.ActiveTemplate,templateKey,StringComparison.OrdinalIgnoreCase)){timer.Stop();return;}if(wallpaperEngine&&ticks>=5){cfg.Wallpaper="";SaveConfig();}RefreshTemplateAppearance();if(!wallpaperEngine||ticks>=5)timer.Stop();};timer.Start();}
  public string TemplateSelfTest(){
   var results=new List<string>();string folder=Path.Combine(Path.GetTempPath(),"Awl-template-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);string wallpaper=Path.Combine(folder,"wallpaper.png"),preview=Path.Combine(folder,"preview.png"),package=Path.Combine(folder,"test.zip");try{using(var image=new System.Drawing.Bitmap(32,18)){using(var graphics=System.Drawing.Graphics.FromImage(image))graphics.Clear(System.Drawing.Color.Teal);image.Save(wallpaper,System.Drawing.Imaging.ImageFormat.Png);}CreateThumbnail(wallpaper,preview);using(var thumb=new System.Drawing.Bitmap(preview))if(thumb.Width!=720||thumb.Height!=405)throw new Exception("Thumbnail was not normalized");cfg=new Preferences{StartMenuGlass=false,TaskbarGlass=true,PinnedBarGlass=false,PinnedGridGlass=true,DesktopWallpaper=wallpaper,Wallpaper=wallpaper,ActiveTemplate="test.zip",WeatherLocation="Private location",WeatherLatitude=1,WeatherLongitude=2};cfg.StartPins.Add(new AppEntry{Name="Private app",Target=wallpaper});cfg.DockPins.Add(new AppEntry{Name="Private app",Target=wallpaper});cfg.DateTimeWidget.Enabled=true;cfg.Recents.Enabled=true;WriteShellTemplate(package,"Test",preview);using(var zip=ZipFile.OpenRead(package)){var names=zip.Entries.Select(x=>x.FullName).ToList();Action<bool,string> check=(ok,label)=>{if(!ok)throw new Exception(label);results.Add(label);};check(names.Contains("manifest.json"),"Template has manifest");check(names.Contains("config.json"),"Template has full config");check(names.Contains("preview.png"),"Template has custom thumbnail");check(names.Contains("desktop-widgets.json"),"Template has widget deployments");check(names.Any(x=>x.StartsWith("wallpaper/")),"Template has wallpaper payload");var manifest=ReadTemplateManifest(zip);check(manifest.wallpaperKind=="file"&&manifest.wallpaperEntry.StartsWith("wallpaper/"),"Wallpaper metadata is portable");Preferences saved;using(var reader=new StreamReader(zip.GetEntry("config.json").Open()))saved=new JavaScriptSerializer().Deserialize<Preferences>(reader.ReadToEnd());check(saved.StartMenuGlass==false&&saved.TaskbarGlass==true&&saved.PinnedBarGlass==false&&saved.PinnedGridGlass==true,"Independent glass settings persist");check(saved.DateTimeWidget.Enabled&&saved.Recents.Enabled,"Enabled widgets persist");check(saved.StartPins.Count==0&&saved.DockPins.Count==0&&String.IsNullOrEmpty(saved.WeatherLocation),"Personal pins and location are excluded");}}catch(Exception error){results.Add("FAILED: "+error);}finally{try{Directory.Delete(folder,true);}catch{}}return String.Join(Environment.NewLine,results);
  }
 }
}
