using System;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;
namespace Awl {partial class Shell {
 void EnableDesktopWidgetDrag(Window window,Func<bool> locked,Action<double,double> save){Point start=new Point();double left=0,topPosition=0;bool dragging=false;
 Func<Point> pointer=()=>{Native.POINT cursor;Native.GetCursorPos(out cursor);var source=PresentationSource.FromVisual(window);return source==null?new Point(cursor.X,cursor.Y):source.CompositionTarget.TransformFromDevice.Transform(new Point(cursor.X,cursor.Y));};
 Action finish=()=>{if(!dragging)return;dragging=false;window.ReleaseMouseCapture();HideSnapGrid();save(window.Left,window.Top);};
 window.QueryCursor+=delegate(object sender,QueryCursorEventArgs e){e.Cursor=locked()?Cursors.Arrow:Cursors.SizeAll;e.Handled=true;};
 window.PreviewMouseLeftButtonDown+=delegate(object sender,MouseButtonEventArgs e){if(locked())return;start=pointer();left=window.Left;topPosition=window.Top;dragging=true;window.CaptureMouse();ShowSnapGrid((Keyboard.Modifiers&ModifierKeys.Control)!=0);e.Handled=true;};
 window.PreviewMouseMove+=delegate(object sender,MouseEventArgs e){if(!dragging)return;if(locked()||e.LeftButton!=MouseButtonState.Pressed){finish();return;}var point=pointer();bool precision=(Keyboard.Modifiers&ModifierKeys.Control)!=0;window.Left=SnapWidgetCoordinate(left+point.X-start.X,true,window,precision);window.Top=SnapWidgetCoordinate(topPosition+point.Y-start.Y,false,window,precision);e.Handled=true;};
 window.PreviewMouseLeftButtonUp+=delegate(object sender,MouseButtonEventArgs e){if(!dragging)return;finish();e.Handled=true;};window.LostMouseCapture+=delegate{finish();};window.Closed+=delegate{finish();};}
 Window CreateWidgetEditorWindow(string title){return new Window{Title="Editing — "+title,Width=Math.Min(1280,SystemParameters.WorkArea.Width-40),Height=Math.Min(820,SystemParameters.WorkArea.Height-40),WindowStartupLocation=WindowStartupLocation.CenterScreen,WindowStyle=WindowStyle.None,AllowsTransparency=true,Background=Brushes.Transparent,ResizeMode=ResizeMode.NoResize,Topmost=true};}
 FrameworkElement WidgetEditorFrame(Window window,string title,FrameworkElement navigation,out Canvas stage,out StackPanel properties){var root=new Grid();root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());var header=new DockPanel{Margin=new Thickness(16)};var done=Action("Done",()=>window.Close());DockPanel.SetDock(done,Dock.Right);header.Children.Add(done);var caption=Text("Editing — "+title,18);caption.MouseLeftButtonDown+=delegate{window.DragMove();};header.Children.Add(caption);root.Children.Add(header);var body=new Grid();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(180)});body.ColumnDefinitions.Add(new ColumnDefinition());body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(300)});Grid.SetRow(body,1);root.Children.Add(body);body.Children.Add(new ScrollViewer{Content=navigation,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden});stage=new Canvas{Background=cardBrush,ClipToBounds=true};Grid.SetColumn(stage,1);body.Children.Add(stage);properties=new StackPanel{Margin=new Thickness(18)};var scroll=new ScrollViewer{Content=properties,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden};Grid.SetColumn(scroll,2);body.Children.Add(scroll);return new Border{Background=panelBrush,BorderBrush=accentBrush,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(20),Child=root};}
 FrameworkElement EditorLayerDropdown(string[] names,string selected,Action<string> choose){var list=new StackPanel();foreach(var name in names){string n=name;list.Children.Add(Action(n,()=>choose(n),n==selected));}return new Expander{Header="Layers",Foreground=ink,IsExpanded=false,Content=list,Margin=new Thickness(0,10,0,0)};}
 void BindWidgetDrag(UIElement target,Canvas stage,Func<bool> begin,Action<double,double> move,Action finish){bool active=false;Point start=new Point();target.PreviewMouseLeftButtonDown+=delegate(object s,MouseButtonEventArgs e){if(e.Handled||!begin())return;active=true;start=e.GetPosition(stage);target.CaptureMouse();e.Handled=true;};target.PreviewMouseMove+=delegate(object s,MouseEventArgs e){if(!active)return;var p=e.GetPosition(stage);move(p.X-start.X,p.Y-start.Y);e.Handled=true;};target.PreviewMouseLeftButtonUp+=delegate(object s,MouseButtonEventArgs e){if(!active)return;active=false;target.ReleaseMouseCapture();finish();e.Handled=true;};target.LostMouseCapture+=delegate{if(active){active=false;finish();}};}
 Thumb WidgetResizeHandle(Canvas stage,double x,double y,Func<bool> locked,Action<double,double> resize,Action finish){var thumb=new Thumb{Width=16,Height=16,Cursor=Cursors.SizeNWSE};StyleRecentThumb(thumb);Canvas.SetLeft(thumb,x);Canvas.SetTop(thumb,y);stage.Children.Add(thumb);thumb.DragDelta+=delegate(object s,DragDeltaEventArgs e){if(!locked())resize(e.HorizontalChange,e.VerticalChange);e.Handled=true;};thumb.DragCompleted+=delegate{if(!locked())finish();};return thumb;}
} }
