using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Awl {
 public class GithubAsset { public string name="",browser_download_url="",content_type="";public long size=0; }
 public class GithubRelease { public string tag_name="",name="",body="",html_url="",published_at="";public bool prerelease=false,draft=false;public List<GithubAsset> assets=new List<GithubAsset>(); }
 partial class Shell {
  bool updateBusy;
  FrameworkElement UpdatesCard(){return Card("↻  Updates",()=>{
   page.Children.Add(Text("Awl "+BuildInfo.Version+" · "+BuildInfo.Channel,13));
   var status=Text("Updates are published through GitHub Releases.",11,mutedBrush);status.TextWrapping=TextWrapping.Wrap;status.Margin=new Thickness(0,5,0,8);page.Children.Add(status);
   Select("Update channel",new[]{"Release","Beta","Alpha"},cfg.UpdateChannel,v=>{cfg.UpdateChannel=v;SaveConfig();});
   var actions=new StackPanel();page.Children.Add(actions);Button check=null;check=Action("Check now",()=>{check.IsEnabled=false;CheckForUpdates(true,status,actions,check);});actions.Children.Add(check);
  });}
  bool ChannelAccepts(GithubRelease release){string tag=(release.tag_name??"").ToLowerInvariant(),channel=cfg.UpdateChannel??"Release";if(channel=="Release")return !release.prerelease&&!tag.Contains("-alpha")&&!tag.Contains("-beta");if(channel=="Beta")return !tag.Contains("-alpha");return true;}
  Version ReleaseVersion(GithubRelease release){string value=(release.tag_name??"").Trim().TrimStart('v','V');int dash=value.IndexOf('-');if(dash>=0)value=value.Substring(0,dash);Version parsed;return Version.TryParse(value,out parsed)?parsed:new Version(0,0,0);}
  async Task<List<GithubRelease>> GithubReleases(){using(var client=new HttpClient()){client.DefaultRequestHeaders.UserAgent.ParseAdd("Awl/"+BuildInfo.Version);client.Timeout=TimeSpan.FromSeconds(12);string json=await client.GetStringAsync("https://api.github.com/repos/"+BuildInfo.Repository+"/releases?per_page=30");return new JavaScriptSerializer().Deserialize<List<GithubRelease>>(json)??new List<GithubRelease>();}}
  async void CheckForUpdates(bool manual,TextBlock status=null,StackPanel actions=null,Button check=null){if(updateBusy)return;updateBusy=true;try{if(status!=null)status.Text="Checking GitHub Releases…";var releases=await GithubReleases();var current=new Version(BuildInfo.Version);var release=releases.Where(x=>!x.draft&&ChannelAccepts(x)&&x.assets!=null&&x.assets.Any(a=>String.Equals(a.name,"Awl.exe",StringComparison.OrdinalIgnoreCase))).OrderByDescending(ReleaseVersion).FirstOrDefault();if(release==null||ReleaseVersion(release)<=current){if(status!=null)status.Text="Awl is up to date · "+BuildInfo.Version;if(manual&&release==null&&status!=null)status.Text="No "+cfg.UpdateChannel.ToLowerInvariant()+" releases are available yet.";return;}string version=ReleaseVersion(release).ToString(3);if(status!=null)status.Text="Awl "+version+" is available · "+(release.name??release.tag_name);if(actions!=null){actions.Children.Clear();actions.Children.Add(Action("Install "+version,()=>InstallUpdate(release,status)));if(!String.IsNullOrWhiteSpace(WhatsNewUrl(release)))actions.Children.Add(Action("What's new",()=>Launch(WhatsNewUrl(release))));}if(manual||!String.Equals(cfg.LastOfferedVersion,release.tag_name,StringComparison.OrdinalIgnoreCase)){cfg.LastOfferedVersion=release.tag_name;SaveConfig();ShowUpdatePrompt(release,status);}}
   catch(Exception error){if(status!=null)status.Text="Update check failed · "+error.Message;else Log("Update check: "+error.Message);}
   finally{updateBusy=false;if(check!=null)check.IsEnabled=true;}
  }
  string WhatsNewUrl(GithubRelease release){return release.html_url;}
  void ShowUpdatePrompt(GithubRelease release,TextBlock status){var dialog=new Window{Title="Awl update",Owner=launcher,Width=460,Height=260,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,WindowStyle=WindowStyle.None,AllowsTransparency=true,Background=Brushes.Transparent,ShowInTaskbar=false};var host=new StackPanel{Margin=new Thickness(20)};host.Children.Add(Text("Awl "+ReleaseVersion(release).ToString(3)+" is ready",20));var detail=Text((release.name??release.tag_name)+" · "+cfg.UpdateChannel+" channel",12,mutedBrush);detail.Margin=new Thickness(0,7,0,12);host.Children.Add(detail);var summary=Text(String.IsNullOrWhiteSpace(release.body)?"A new Awl build is available from GitHub.":StripHtml(release.body),12,mutedBrush);summary.TextWrapping=TextWrapping.Wrap;summary.MaxHeight=70;host.Children.Add(summary);var buttons=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0,14,0,0)};if(!String.IsNullOrWhiteSpace(WhatsNewUrl(release)))buttons.Children.Add(Action("What's new",()=>Launch(WhatsNewUrl(release))));buttons.Children.Add(Action("Later",()=>dialog.Close()));buttons.Children.Add(Action("Install update",()=>{dialog.Close();InstallUpdate(release,status);}));host.Children.Add(buttons);dialog.Content=new Border{Background=SurfaceBrush(baseColor,.98,cfg.StartMenuGlass??cfg.GlassEffect),BorderBrush=accentBrush,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(20),Effect=ShellShadow(),Child=host};dialog.Show();}
  string StripHtml(string value){if(String.IsNullOrWhiteSpace(value))return "";string plain=System.Text.RegularExpressions.Regex.Replace(value,"<[^>]+>"," ");plain=System.Net.WebUtility.HtmlDecode(plain);return System.Text.RegularExpressions.Regex.Replace(plain,"\\s+"," ").Trim();}
  async void InstallUpdate(GithubRelease release,TextBlock status){try{if(status!=null)status.Text="Downloading Awl "+ReleaseVersion(release).ToString(3)+"…";var binary=release.assets.First(x=>String.Equals(x.name,"Awl.exe",StringComparison.OrdinalIgnoreCase));var checksum=release.assets.FirstOrDefault(x=>String.Equals(x.name,"Awl.exe.sha256",StringComparison.OrdinalIgnoreCase));if(checksum==null)throw new InvalidDataException("This release has no checksum.");byte[] bytes;string expected;using(var client=new HttpClient()){client.DefaultRequestHeaders.UserAgent.ParseAdd("Awl/"+BuildInfo.Version);bytes=await client.GetByteArrayAsync(binary.browser_download_url);expected=(await client.GetStringAsync(checksum.browser_download_url)).Trim().Split(new[]{' ','\t','\r','\n'},StringSplitOptions.RemoveEmptyEntries)[0];}string actual;using(var sha=SHA256.Create())actual=BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();if(!String.Equals(expected,actual,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("The downloaded update failed checksum verification.");string staged=Path.Combine(Path.GetTempPath(),"Awl-update-"+Guid.NewGuid().ToString("N")+".exe");File.WriteAllBytes(staged,bytes);LaunchUpdater(staged);if(status!=null)status.Text="Installing update…";if(launcher!=null)launcher.Hide();Quit();}catch(Exception error){if(status!=null)status.Text="Install failed · "+error.Message;MessageBox.Show(launcher,error.Message,"Awl update could not be installed");}}
  void LaunchUpdater(string staged){string current=typeof(Shell).Assembly.Location,script=Path.Combine(Path.GetTempPath(),"Awl-update-"+Guid.NewGuid().ToString("N")+".cmd");string q="\"";var body=new StringBuilder();body.AppendLine("@echo off");body.AppendLine("timeout /t 2 /nobreak >nul");body.AppendLine(":retry");body.AppendLine("copy /y "+q+staged+q+" "+q+current+q+" >nul");body.AppendLine("if errorlevel 1 (timeout /t 1 /nobreak >nul & goto retry)");body.AppendLine("start \"\" "+q+current+q);body.AppendLine("del /q "+q+staged+q);body.AppendLine("del /q \"%~f0\"");File.WriteAllText(script,body.ToString(),Encoding.ASCII);bool elevate=false;try{string probe=Path.Combine(Path.GetDirectoryName(current),".awl-update-test");File.WriteAllText(probe,"");File.Delete(probe);}catch{elevate=true;}var start=new ProcessStartInfo("cmd.exe","/c \"\""+script+"\"\""){UseShellExecute=elevate,CreateNoWindow=!elevate,WindowStyle=ProcessWindowStyle.Hidden};if(elevate)start.Verb="runas";Process.Start(start);}
 }
}
