using System;using System.IO;using System.Linq;using System.Diagnostics;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;using System.Windows.Interop;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace Awl {partial class Shell {
 Window wallpaperWindow;MediaElement wallpaperVideo;
 [DllImport("user32.dll")]static extern IntPtr FindWindowEx(IntPtr parent,IntPtr after,string cls,string title);
 [DllImport("user32.dll")]static extern IntPtr SetParent(IntPtr child,IntPtr parent);
 [DllImport("user32.dll")]static extern IntPtr SendMessageTimeout(IntPtr h,uint msg,IntPtr w,IntPtr l,uint flags,uint timeout,out IntPtr result);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool SystemParametersInfo(uint action,uint parameter,string value,uint flags);
 string WallpaperEngineExecutable(){
  foreach(string name in new[]{"wallpaper64","wallpaper32"})foreach(var process in Process.GetProcessesByName(name)){try{string active=process.MainModule.FileName;if(File.Exists(active))return active;}catch{}finally{process.Dispose();}}
  var candidates=new System.Collections.Generic.List<string>();
  if(!String.IsNullOrEmpty(cfg.WallpaperEngineConfig)){var root=Path.GetDirectoryName(cfg.WallpaperEngineConfig);if(!String.IsNullOrEmpty(root)){candidates.Add(Path.Combine(root,"wallpaper64.exe"));candidates.Add(Path.Combine(root,"wallpaper32.exe"));}}
  candidates.Add(@"C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper64.exe");candidates.Add(@"C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper32.exe");
  try{using(var key=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Valve\Steam")){string steam=Convert.ToString(key==null?null:key.GetValue("SteamPath"));if(!String.IsNullOrEmpty(steam)){candidates.Add(Path.Combine(steam,"steamapps","common","wallpaper_engine","wallpaper64.exe"));candidates.Add(Path.Combine(steam,"steamapps","common","wallpaper_engine","wallpaper32.exe"));}}}catch{}
  return candidates.FirstOrDefault(File.Exists);
 }
 bool HasWallpaperEngine(){return !String.IsNullOrEmpty(WallpaperEngineExecutable());}
 string VideoWallpaperPreview(string path){if(String.IsNullOrEmpty(path)||!File.Exists(path))return "";string preview=Path.Combine(Root,"desktop-wallpaper-preview.png"),stamp=preview+".source";string identity=Path.GetFullPath(path)+"|"+File.GetLastWriteTimeUtc(path).Ticks;try{if(File.Exists(preview)&&File.Exists(stamp)&&File.ReadAllText(stamp)==identity)return preview;IShellImage item=null;IntPtr bitmap=IntPtr.Zero;var id=typeof(IShellImage).GUID;if(SHCreateItemFromParsingName(path,IntPtr.Zero,ref id,out item)!=0||item.GetImage(new NativeSize{X=720,Y=405},0x108,out bitmap)!=0||bitmap==IntPtr.Zero)return "";try{using(var image=System.Drawing.Image.FromHbitmap(bitmap))image.Save(preview,System.Drawing.Imaging.ImageFormat.Png);File.WriteAllText(stamp,identity);return preview;}finally{DeleteObject(bitmap);if(item!=null)Marshal.ReleaseComObject(item);}}catch(Exception error){Log("Video wallpaper preview: "+error.Message);return "";}}
 bool WallpaperEngineControl(string command){string exe=WallpaperEngineExecutable();if(String.IsNullOrEmpty(exe))return false;try{Process.Start(new ProcessStartInfo(exe,"-control "+command){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden});return true;}catch{return false;}}
 void RestoreWallpaperEngine(){if(!WallpaperEngineControl("play"))return;if(wallpaperWindow!=null){wallpaperWindow.Close();wallpaperWindow=null;wallpaperVideo=null;}cfg.DesktopWallpaper="";cfg.Wallpaper="";SampleWallpaper(true);Changed();}
 void ChooseDesktopWallpaper(){var picker=new Microsoft.Win32.OpenFileDialog{Title="Set wallpaper",Filter="Images and videos|*.jpg;*.jpeg;*.png;*.bmp;*.mp4;*.wmv;*.m4v;*.mov|All files|*.*"};if(picker.ShowDialog(launcher)!=true)return;try{StartDesktopWallpaper(picker.FileName);}catch(Exception error){MessageBox.Show(launcher,error.Message,"Wallpaper could not be loaded");}}
 void StartDesktopWallpaper(string path){if(!File.Exists(path))throw new FileNotFoundException("Wallpaper file is missing",path);string ext=Path.GetExtension(path).ToLowerInvariant();bool video=ext==".mp4"||ext==".wmv"||ext==".m4v"||ext==".mov";
 if(!video){var image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.UriSource=new Uri(path);image.EndInit();string bmp=Path.Combine(Root,"desktop-wallpaper.bmp");var encoder=new BmpBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using(var output=File.Create(bmp))encoder.Save(output);if(!SystemParametersInfo(20,0,bmp,3))throw new InvalidOperationException("Windows could not set the wallpaper.");WallpaperEngineControl("stop");if(wallpaperWindow!=null){wallpaperWindow.Close();wallpaperWindow=null;}cfg.DesktopWallpaper=path;cfg.Wallpaper=path;SampleWallpaper(true);Changed();return;}
 var progman=Native.FindWindow("Progman",null);IntPtr result;SendMessageTimeout(progman,0x052C,IntPtr.Zero,IntPtr.Zero,2,1000,out result);IntPtr worker=IntPtr.Zero;Native.EnumWindows(delegate(IntPtr h,IntPtr unused){if(FindWindowEx(h,IntPtr.Zero,"SHELLDLL_DefView",null)!=IntPtr.Zero)worker=FindWindowEx(IntPtr.Zero,h,"WorkerW",null);return true;},IntPtr.Zero);if(worker==IntPtr.Zero)throw new InvalidOperationException("Windows desktop wallpaper host is unavailable.");
 string sample=VideoWallpaperPreview(path);cfg.DesktopWallpaper=path;cfg.Wallpaper=sample;SampleWallpaper(true);Changed();var player=new MediaElement{LoadedBehavior=MediaState.Manual,UnloadedBehavior=MediaState.Close,Stretch=Stretch.UniformToFill,IsMuted=true,Source=new Uri(path)};var window=new Window{Title="Awl Wallpaper",WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,ShowInTaskbar=false,ShowActivated=false,Width=SystemParameters.VirtualScreenWidth,Height=SystemParameters.VirtualScreenHeight,Left=0,Top=0,Content=player};window.SourceInitialized+=delegate{var handle=new WindowInteropHelper(window).Handle;Native.SetWindowLong(handle,-16,(Native.GetWindowLong(handle,-16)&~unchecked((int)0x80000000))|0x40000000);SetParent(handle,worker);};player.MediaEnded+=delegate{player.Position=TimeSpan.Zero;player.Play();};player.MediaFailed+=delegate(object sender,ExceptionRoutedEventArgs e){window.Close();Log("Wallpaper playback failed: "+e.ErrorException.Message);WallpaperEngineControl("play");MessageBox.Show("This video could not be played. Try an H.264 MP4.","Wallpaper playback");};player.MediaOpened+=delegate{WallpaperEngineControl("stop");if(wallpaperWindow!=null&&wallpaperWindow!=window)wallpaperWindow.Close();wallpaperWindow=window;wallpaperVideo=player;SaveConfig();};window.Closed+=delegate{player.Close();};window.Show();player.Play();}
} }

