using System;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Shapes;using System.Windows.Interop;
namespace Awl {partial class Shell {
 Window snapGrid;
 Point LayerPosition(WidgetLayer layer){var w=cfg.DateTimeWidget;if(layer.Anchor=="Free")return new Point(layer.X,layer.Y);string anchor=layer.Anchor;double x=anchor.Contains("left")?0:anchor.Contains("right")?w.Width-layer.Width:(w.Width-layer.Width)/2;double y=anchor.StartsWith("Top")?0:anchor.StartsWith("Bottom")?w.Height-layer.Size*1.4:(w.Height-layer.Size*1.4)/2;return new Point(x+layer.X,y+layer.Y);}
 void AnchorControls(WidgetLayer layer){Select("Anchor",new[]{"Free","Top left","Top middle","Top right","Middle left","Center","Middle right","Bottom left","Bottom middle","Bottom right"},layer.Anchor,v=>{layer.Anchor=v;layer.X=0;layer.Y=0;SaveConfig();DrawWidgetPreview();WidgetProperties();});}
 double SnapCoordinate(double value,double origin){var w=cfg.DateTimeWidget;double step=Clamp(w.GridSize,4,200);return w.Snap?origin+Math.Round((value-origin)/step)*step:value;}
 double WidgetPositionFromRatio(double ratio,bool horizontal,double size){double origin=horizontal?SystemParameters.VirtualScreenLeft:SystemParameters.VirtualScreenTop,span=horizontal?SystemParameters.VirtualScreenWidth:SystemParameters.VirtualScreenHeight;return origin+Clamp(ratio,0,1)*Math.Max(0,span-size);}
 double WidgetPositionRatio(double value,bool horizontal,double size){double origin=horizontal?SystemParameters.VirtualScreenLeft:SystemParameters.VirtualScreenTop,span=horizontal?SystemParameters.VirtualScreenWidth:SystemParameters.VirtualScreenHeight,usable=Math.Max(1,span-size);return Clamp((value-origin)/usable,0,1);}
 double SnapWidgetCoordinate(double value,bool horizontal,Window window,bool precision){if(!cfg.DateTimeWidget.Snap)return value;double origin=horizontal?SystemParameters.VirtualScreenLeft:SystemParameters.VirtualScreenTop,span=horizontal?SystemParameters.VirtualScreenWidth:SystemParameters.VirtualScreenHeight,size=horizontal?window.Width:window.Height;if(precision)return SnapCoordinate(value,origin);double usable=Math.Max(0,span-size),ratio=usable<=0?0:(value-origin)/usable;return origin+Math.Round(Clamp(ratio,0,1)*4)/4*usable;}
 void ShowSnapGrid(){ShowSnapGrid(false);}
 void ShowSnapGrid(bool precision){if(!cfg.DateTimeWidget.Snap||snapGrid!=null)return;var canvas=new Canvas{IsHitTestVisible=false};snapGrid=new Window{Left=SystemParameters.VirtualScreenLeft,Top=SystemParameters.VirtualScreenTop,Width=SystemParameters.VirtualScreenWidth,Height=SystemParameters.VirtualScreenHeight,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,ShowInTaskbar=false,ShowActivated=false,Topmost=false,IsHitTestVisible=false,Content=canvas};double step=Clamp(cfg.DateTimeWidget.GridSize,8,200);var drawing=new DrawingGroup();if(precision){for(double x=0;x<snapGrid.Width;x+=step)for(double y=0;y<snapGrid.Height;y+=step)drawing.Children.Add(new GeometryDrawing(accentBrush,null,new EllipseGeometry(new Point(x,y),1,1)));}else{for(int i=0;i<=4;i++){double x=snapGrid.Width*i/4,y=snapGrid.Height*i/4;drawing.Children.Add(new GeometryDrawing(null,new Pen(accentBrush,1),new LineGeometry(new Point(x,0),new Point(x,snapGrid.Height))));drawing.Children.Add(new GeometryDrawing(null,new Pen(accentBrush,1),new LineGeometry(new Point(0,y),new Point(snapGrid.Width,y))));}}var image=new Image{Source=new DrawingImage(drawing),Width=snapGrid.Width,Height=snapGrid.Height,Opacity=.5};canvas.Children.Add(image);snapGrid.SourceInitialized+=delegate{var h=new WindowInteropHelper(snapGrid).Handle;Native.SetWindowLong(h,-20,Native.GetWindowLong(h,-20)|0x20|0x80|0x08000000);};snapGrid.Show();}
 void HideSnapGrid(){if(snapGrid!=null){snapGrid.Close();snapGrid=null;}}
 ClockWidgetPreferences CopyLayout(ClockWidgetPreferences source){var json=new System.Web.Script.Serialization.JavaScriptSerializer();return json.Deserialize<ClockWidgetPreferences>(json.Serialize(source));}
 void SaveLayoutTemplate(string name){name=(name??"").Trim();if(name.Length==0)return;cfg.WidgetTemplates[name]=CopyLayout(cfg.DateTimeWidget);SaveConfig();}
 void LoadLayoutTemplate(string name){ClockWidgetPreferences saved;if(cfg.DateTimeWidget.Locked||!cfg.WidgetTemplates.TryGetValue(name,out saved))return;cfg.DateTimeWidget=CopyLayout(saved);cfg.DateTimeWidget.Locked=false;SaveWidget();DrawLauncher();}
 void WidgetMovementControls(){Setting("Lock movement",cfg.DateTimeWidget.Locked,v=>{cfg.DateTimeWidget.Locked=v;SaveWidget();DrawLauncher();});Setting("Snap to grid",cfg.DateTimeWidget.Snap,v=>{cfg.DateTimeWidget.Snap=v;SaveWidget();});SliderRow("Grid spacing",cfg.DateTimeWidget.GridSize,4,200,v=>{cfg.DateTimeWidget.GridSize=v;SaveWidget();},"px");var name=new TextBox{Background=cardBrush,Foreground=ink,CaretBrush=ink,Padding=new Thickness(8),BorderThickness=new Thickness(0),MaxLength=60,ToolTip="Template name"};page.Children.Add(Text("Layout templates",14));page.Children.Add(name);page.Children.Add(Action("Save layout as template",()=>{SaveLayoutTemplate(name.Text);DrawLauncher();}));foreach(string key in cfg.WidgetTemplates.Keys.OrderBy(x=>x).ToArray()){string template=key;var row=new DockPanel();var remove=Action("×",()=>{cfg.WidgetTemplates.Remove(template);SaveConfig();DrawLauncher();});DockPanel.SetDock(remove,Dock.Right);row.Children.Add(remove);var load=Action(template,()=>LoadLayoutTemplate(template));load.IsEnabled=!cfg.DateTimeWidget.Locked;row.Children.Add(load);page.Children.Add(row);}}
} }
