using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows;
using System.Windows.Controls;
namespace Awl {
sealed class WifiClient:IDisposable {
 IntPtr handle;public Guid Adapter;
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] struct AdapterInfo{public Guid Id;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=256)]public string Name;public int State;}
 [StructLayout(LayoutKind.Sequential)] public struct Ssid{public uint Length;[MarshalAs(UnmanagedType.ByValArray,SizeConst=32)]public byte[] Bytes;}
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] public struct Network{[MarshalAs(UnmanagedType.ByValTStr,SizeConst=256)]public string Profile;public Ssid Ssid;public int Bss;public uint BssCount;public int Connectable;public uint Reason,PhyCount;[MarshalAs(UnmanagedType.ByValArray,SizeConst=8)]public int[] Phys;public int More;public uint Signal;public int Secure,Auth,Cipher;public uint Flags,Reserved;public string Name{get{return Encoding.UTF8.GetString(Ssid.Bytes,0,(int)Math.Min(32,Ssid.Length));}}}
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] struct ConnectParams{public int Mode;[MarshalAs(UnmanagedType.LPWStr)]public string Profile;public IntPtr Ssid,Bssid;public int Bss;public uint Flags;}
 [StructLayout(LayoutKind.Sequential)] struct Radio{public uint Index;public int Software,Hardware;}
 [DllImport("wlanapi.dll")] static extern uint WlanOpenHandle(uint version,IntPtr reserved,out uint negotiated,out IntPtr handle);
 [DllImport("wlanapi.dll")] static extern uint WlanCloseHandle(IntPtr handle,IntPtr reserved);
 [DllImport("wlanapi.dll")] static extern uint WlanEnumInterfaces(IntPtr handle,IntPtr reserved,out IntPtr list);
 [DllImport("wlanapi.dll")] static extern void WlanFreeMemory(IntPtr data);
 [DllImport("wlanapi.dll")] static extern uint WlanGetAvailableNetworkList(IntPtr handle,ref Guid guid,uint flags,IntPtr reserved,out IntPtr list);
 [DllImport("wlanapi.dll")] static extern uint WlanScan(IntPtr handle,ref Guid guid,IntPtr ssid,IntPtr ie,IntPtr reserved);
 [DllImport("wlanapi.dll")] static extern uint WlanDisconnect(IntPtr handle,ref Guid guid,IntPtr reserved);
 [DllImport("wlanapi.dll")] static extern uint WlanQueryInterface(IntPtr handle,ref Guid guid,int opcode,IntPtr reserved,out uint size,out IntPtr data,out int type);
 [DllImport("wlanapi.dll")] static extern uint WlanSetInterface(IntPtr handle,ref Guid guid,int opcode,uint size,ref Radio data,IntPtr reserved);
 [DllImport("wlanapi.dll",CharSet=CharSet.Unicode)] static extern uint WlanConnect(IntPtr handle,ref Guid guid,ref ConnectParams data,IntPtr reserved);
 static void Check(uint code){if(code!=0)throw new Exception(code==5?"Windows denied Wi-Fi access. Check Location permissions.":new System.ComponentModel.Win32Exception((int)code).Message);}
 public WifiClient(){uint version;Check(WlanOpenHandle(2,IntPtr.Zero,out version,out handle));IntPtr list=IntPtr.Zero;try{Check(WlanEnumInterfaces(handle,IntPtr.Zero,out list));if(Marshal.ReadInt32(list)==0)throw new Exception("No Wi-Fi adapter");Adapter=((AdapterInfo)Marshal.PtrToStructure(IntPtr.Add(list,8),typeof(AdapterInfo))).Id;}catch{Dispose();throw;}finally{if(list!=IntPtr.Zero)WlanFreeMemory(list);}}
 public List<Network> Networks(){IntPtr list=IntPtr.Zero;try{Check(WlanGetAvailableNetworkList(handle,ref Adapter,0,IntPtr.Zero,out list));int count=Marshal.ReadInt32(list);var result=new List<Network>();int size=Marshal.SizeOf(typeof(Network));for(int i=0;i<count;i++)result.Add((Network)Marshal.PtrToStructure(IntPtr.Add(list,8+i*size),typeof(Network)));return result;}finally{if(list!=IntPtr.Zero)WlanFreeMemory(list);}}
 public bool On(){uint size;int type;IntPtr data;Check(WlanQueryInterface(handle,ref Adapter,4,IntPtr.Zero,out size,out data,out type));try{if(Marshal.ReadInt32(data)==0)return false;var r=(Radio)Marshal.PtrToStructure(IntPtr.Add(data,4),typeof(Radio));return r.Software==1&&r.Hardware==1;}finally{WlanFreeMemory(data);}}
 public void Power(bool on){uint size;int type;IntPtr data;Check(WlanQueryInterface(handle,ref Adapter,4,IntPtr.Zero,out size,out data,out type));try{int count=Marshal.ReadInt32(data);for(int i=0;i<count;i++){var r=(Radio)Marshal.PtrToStructure(IntPtr.Add(data,4+i*12),typeof(Radio));r.Software=on?1:2;Check(WlanSetInterface(handle,ref Adapter,4,12,ref r,IntPtr.Zero));}}finally{WlanFreeMemory(data);}}
 public void Scan(){Check(WlanScan(handle,ref Adapter,IntPtr.Zero,IntPtr.Zero,IntPtr.Zero));}
 public void Disconnect(){Check(WlanDisconnect(handle,ref Adapter,IntPtr.Zero));}
 public void Connect(Network n,string password){var p=new ConnectParams{Bss=n.Bss};if(!String.IsNullOrEmpty(n.Profile)){p.Mode=0;p.Profile=n.Profile;}else{if(n.Secure!=0&&!(n.Auth==7&&n.Cipher==4))throw new Exception("This network needs a saved Windows profile (enterprise/WPA3).");if(n.Secure!=0&&(password.Length<8||password.Length>63))throw new Exception("Password must contain 8–63 characters.");string hex=BitConverter.ToString(n.Ssid.Bytes,0,(int)n.Ssid.Length).Replace("-","");string safe=System.Security.SecurityElement.Escape(n.Name);string key=System.Security.SecurityElement.Escape(password);p.Mode=3;p.Profile="<?xml version=\"1.0\"?><WLANProfile xmlns=\"http://www.microsoft.com/networking/WLAN/profile/v1\"><name>"+safe+"</name><SSIDConfig><SSID><hex>"+hex+"</hex></SSID></SSIDConfig><connectionType>ESS</connectionType><connectionMode>manual</connectionMode><MSM><security><authEncryption><authentication>"+(n.Secure!=0?"WPA2PSK":"open")+"</authentication><encryption>"+(n.Secure!=0?"AES":"none")+"</encryption><useOneX>false</useOneX></authEncryption>"+(n.Secure!=0?"<sharedKey><keyType>passPhrase</keyType><protected>false</protected><keyMaterial>"+key+"</keyMaterial></sharedKey>":"")+"</security></MSM></WLANProfile>";}Check(WlanConnect(handle,ref Adapter,ref p,IntPtr.Zero));}
 public void Dispose(){if(handle!=IntPtr.Zero){WlanCloseHandle(handle,IntPtr.Zero);handle=IntPtr.Zero;}}
}
partial class Shell {
 public string WifiSelfTest(){try{using(var wlan=new WifiClient()){var networks=wlan.Networks();return "Wi-Fi popup can enumerate "+networks.Count+" network(s)";}}catch(Exception error){return "Wi-Fi status: "+error.Message;}}
 void WifiPanel(StackPanel content,TextBlock note){try{using(var wlan=new WifiClient()){bool on=wlan.On();content.Children.Add(Switch("Wi-Fi",on,v=>{try{using(var w=new WifiClient())w.Power(v);systemPopup.IsOpen=false;SystemPanel("Wi-Fi");}catch(Exception e){note.Text=e.Message;}}));var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(Action("↻ Scan",async()=>{try{using(var w=new WifiClient())w.Scan();note.Text="Scanning…";await System.Threading.Tasks.Task.Delay(1800);if(systemPopup!=null&&systemPopup.IsOpen&&(string)systemPopup.Tag=="Wi-Fi"){systemPopup.IsOpen=false;SystemPanel("Wi-Fi");}}catch(Exception e){note.Text=e.Message;if(e.Message.IndexOf("Location",StringComparison.OrdinalIgnoreCase)>=0)content.Children.Add(Action("Enable location access",()=>Launch("ms-settings:privacy-location")));}}));row.Children.Add(Action("Disconnect",()=>{try{using(var w=new WifiClient())w.Disconnect();note.Text="Disconnect requested";}catch(Exception e){note.Text=e.Message;}}));content.Children.Add(row);if(!on){note.Text="Wi-Fi off";return;}note.Text="Networks";var list=new StackPanel();foreach(var n in wlan.Networks()){if(n.Ssid.Length==0)continue;var network=n;var item=new StackPanel();var choose=Action((n.Secure!=0?"🔒 ":"○ ")+n.Name+"  "+n.Signal+"%"+((n.Flags&1)!=0?" ✓":""),()=>{});choose.HorizontalContentAlignment=HorizontalAlignment.Left;choose.Click+=delegate{if(String.IsNullOrEmpty(network.Profile)&&network.Secure!=0){if(item.Children.Count>1)return;var password=new PasswordBox{Margin=new Thickness(6),Padding=new Thickness(8),ToolTip="Network password"};item.Children.Add(password);item.Children.Add(Action("Connect",()=>{try{using(var w=new WifiClient())w.Connect(network,password.Password);password.Clear();note.Text="Connection requested · refresh to verify";}catch(Exception e){note.Text=e.Message;}}));}else try{using(var w=new WifiClient())w.Connect(network,"");note.Text="Connection requested · refresh to verify";}catch(Exception e){note.Text=e.Message;}};item.Children.Add(choose);list.Children.Add(item);}content.Children.Add(new ScrollViewer{Content=list,MaxHeight=330,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden});}}catch(Exception e){note.Text=e.Message;if(e.Message.IndexOf("Location",StringComparison.OrdinalIgnoreCase)>=0)content.Children.Add(Action("Enable location access",()=>Launch("ms-settings:privacy-location")));}}
}
}
